### ISSUE TITLE
SSL error when loading the client

### ISSUE THREAD

**Issue by 4guu** [space-wizards/space-station-14#10187]
C:\Program Files (x86)\Steam\steamapps\common\Space Station 14 Playtest>SETX DOTNET_ROOT "C:\Program Files (x86)\Steam\steamapps\common\Space Station 14 Playtest\dotnet"

Успех. Указанное значение сохранено.

C:\Program Files (x86)\Steam\steamapps\common\Space Station 14 Playtest>dotnet\dotnet.exe bin\SS14.Launcher.dll
We are primary launcher (or primary launcher is out for lunch)
[15:30:58 DBG] Migrating with prefix SS14.Launcher.Models.Data.Migrations
[15:30:58 INF] Committing migrations
[15:30:58 DBG] Did migrations in 00:00:00.1083979
[15:30:58 INF] Runtime: .NET 6.0.4 win7-x64
[15:30:58 INF] OS: Microsoft Windows 6.1.7601 Service Pack 1 X64
[15:30:58 INF] Launcher version: 0.14.0.0
[15:30:58 DBG] Playtest build: True
[15:30:59 DBG] Migrating content database...
[15:30:59 DBG] Migrating with prefix SS14.Launcher.Models.ContentManagement.Migrations
[15:30:59 INF] Committing migrations
[15:30:59 DBG] Did content DB migrations in 00:00:00.0017042
[15:31:04 DBG] Refreshing all tokens.
[15:31:04 DBG] Token for 4gu/token still valid? True
[15:31:04 DBG] Setting status for login 4gu/token to Available
[15:31:10 DBG] Checking to see if we already have version for fork wizards/8a2f40f39ea33b49bb368b9b70840c320075cf39 ZipHash: b166fcaeec73fb810aa71aa5ea83c2242131e464b75fc25d885005ffe1d6d835 ManifestHash: 596B7F245E2AC6D8A95EA0A2C486A1CF48DAFECF9F6687B06CE79838508D6D87
[15:31:10 DBG] Did not find matching version
[15:31:10 DBG] Downloading content manifest from https://cdn.centcomm.spacestation14.com/cdn/version/8a2f40f39ea33b49bb368b9b70840c320075cf39/manifest
[15:31:10 ERR] Exception while trying to run updates
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): Получено непредвиденное сообщение или оно имеет неправильный формат.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at SS14.Launcher.Utility.HttpUtility.SendZStdAsync(HttpClient client, HttpRequestMessage message, HttpCompletionOption completionOption, CancellationToken cancel)
   at SS14.Launcher.Models.Updater.IngestContentManifest(ServerBuildInformation buildInfo, SqliteConnection con, Int64 versionId, Stopwatch swSqlite, CancellationToken cancel)
   at SS14.Launcher.Models.Updater.DownloadNewVersionManifest(ServerBuildInformation buildInfo, SqliteConnection con, Int64 versionId, CancellationToken cancel)
   at SS14.Launcher.Models.Updater.DownloadNewVersion(ServerBuildInformation buildInfo, SqliteConnection con, Lazy`1 moduleManifest, CancellationToken cancel, String engineVersion)
   at SS14.Launcher.Models.Updater.TouchOrDownloadContentUpdate(ServerBuildInformation buildInfo, SqliteConnection con, Lazy`1 moduleManifest, CancellationToken cancel)
   at SS14.Launcher.Models.Updater.RunUpdate(ServerBuildInformation buildInfo, CancellationToken cancel)
   at SS14.Launcher.Models.Updater.RunUpdateForLaunchAsync(ServerBuildInformation buildInformation, CancellationToken cancel)
[15:31:10 ERR] Failed to connect: UpdateError
SS14.Launcher.Models.Connector+ConnectException: Exception of type 'SS14.Launcher.Models.Connector+ConnectException' was thrown.
   at SS14.Launcher.Models.Connector.RunUpdateAsync(ServerInfo info, CancellationToken cancel)
   at SS14.Launcher.Models.Connector.ConnectInternalAsync(String address, CancellationToken cancel)
   at SS14.Launcher.Models.Connector.Connect(String address, CancellationToken cancel)

**Comment by Morb0** [comment]
Try to install all Windows 7 latest updates

**Comment by moonheart08** [comment]
Windows 7 is not supported. The above advice (making sure your system is fully up to date) is the most we can offer.
