### ISSUE TITLE
Drinking a bottle of Kahlua causes the server to crash

### ISSUE THREAD

**Issue by unusualcrow** [space-wizards/space-station-14#1026]
Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.

**Comment by PJB3005** [comment]
That assert isn't very useful.

**Comment by FL-OZ** [comment]
My PR probably fixes this. https://github.com/space-wizards/space-station-14/pull/1009

**Comment by unusualcrow** [comment]
> Unhandled exception. Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in E:\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 48
   at Robust.Shared.GameObjects.Entity.TryGetComponent[T](T& component) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 284
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.get_GridID() in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Transform\TransformComponent.cs:line 80
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.get_GridPosition() in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Transform\TransformComponent.cs:line 209
   at Content.Server.GameObjects.Components.Nutrition.DrinkComponent.Finish(IEntity user) in E:\space-station-14\Content.Server\GameObjects\Components\Nutrition\DrinkComponent.cs:line 193
   at Content.Server.GameObjects.Components.Nutrition.DrinkComponent.UseDrink(IEntity user) in E:\space-station-14\Content.Server\GameObjects\Components\Nutrition\DrinkComponent.cs:line 171
   at Content.Server.GameObjects.Components.Nutrition.DrinkComponent.Content.Server.GameObjects.EntitySystems.IUse.UseEntity(UseEntityEventArgs eventArgs) in E:\space-station-14\Content.Server\GameObjects\Components\Nutrition\DrinkComponent.cs:line 126
   at Content.Server.GameObjects.EntitySystems.InteractionSystem.UseInteraction(IEntity user, IEntity used) in E:\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionSystem.cs:line 649
   at Content.Server.GameObjects.EntitySystems.InteractionSystem.TryUseInteraction(IEntity user, IEntity used) in E:\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionSystem.cs:line 619
   at Content.Server.GameObjects.HandsComponent.ActivateItem() in E:\space-station-14\Content.Server\GameObjects\Components\GUI\ServerHandsComponent.cs:line 435
   at Content.Server.GameObjects.EntitySystems.HandsSystem.HandleActivateItem(ICommonSession session) in E:\space-station-14\Content.Server\GameObjects\EntitySystems\HandsSystem.cs:line 153
   at Robust.Shared.Input.InputCmdHandler.StateInputCmdHandler.Enabled(ICommonSession session) in E:\space-station-14\RobustToolbox\Robust.Shared\Input\InputCmdHandler.cs:line 45
   at Robust.Shared.Input.InputCmdHandler.StateInputCmdHandler.HandleCmdMessage(ICommonSession session, InputCmdMessage message) in E:\space-station-14\RobustToolbox\Robust.Shared\Input\InputCmdHandler.cs:line 64
   at Robust.Server.GameObjects.EntitySystems.InputSystem.InputMessageHandler(InputCmdMessage message) in E:\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySystems\InputSystem.cs:line 69
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(EntityEventArgs ev) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 152
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, EntityEventArgs eventArgs) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 278
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, EntityEventArgs toRaise) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 203
   at Robust.Shared.GameObjects.EntityManager.<Initialize>b__22_1(Object sender, EntitySystemMessage systemMsg) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 65
   at Robust.Server.GameObjects.ServerEntityNetworkManager.HandleEntityNetworkMessage(MsgEntity message) in E:\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 82
   at Robust.Shared.Network.NetManager.<>c__DisplayClass61_0`1.<RegisterNetMessage>b__0(NetMessage msg) in E:\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 710
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in E:\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 663
   at Robust.Shared.Network.NetManager.ProcessPackets() in E:\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 309
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in E:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 371
   at Robust.Server.BaseServer.<MainLoop>b__32_0(Object sender, FrameEventArgs args) in E:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 274
   at Robust.Shared.Timing.GameLoop.Run() in E:\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 180
   at Robust.Server.BaseServer.MainLoop() in E:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 277
   at Robust.Server.Program.ParsedMain(CommandLineArgs args) in E:\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 64
   at Robust.Server.Program.Start(String[] args) in E:\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 34
   at Robust.Server.Program.Main(String[] args) in E:\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 20
   at Robust.Server.ContentStart.Start(String[] args) in E:\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in E:\space-station-14\Content.Server\Program.cs:line 9

**Comment by unusualcrow** [comment]
branch wasn't up to date when i thought it was, doesn't happen on latest
whoopsie
