### ISSUE TITLE
System.Globalization.CultureNotFoundException when joining server

### ISSUE THREAD

**Issue by zigol01** [space-wizards/space-station-14#10305]
## Description
When I join the server the client window pops up, stays for a bit and then closes. I downloaded also a Github version and tried to run it but the same error remained.

**Reproduction**
1. Download game (either from Steam or Github)
2. Play
3. Join random server/Run client

**Logs**
```
[FATL] unhandled: System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Content.Shared.Localizations.Localization.Init() in /home/runner/work/Nyanotrasen/Nyanotrasen/Content.Shared/Localizations/Localization.cs:line 24
   at Robust.Shared.ContentPack.BaseModLoader.BroadcastRunLevel(ModRunLevel level) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/ContentPack/BaseModLoader.cs:line 74
   at Robust.Client.GameController.StartupContinue(DisplayMode displayMode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 129
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 124
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 116
   at Robust.Client.GameController.<>c__DisplayClass86_0.<Run>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 83
   at System.Threading.Thread.StartCallback()
```

**Additional context**
Operating System: Arch Linux
Qt: 5.15.5
KDE Frameworks: 5.95.0
kf5-config: 1.0
UName: Linux 5.18.9-1-ck-generic-v3 #1 SMP PREEMPT_DYNAMIC Sun Jul 3 08:03:05 EDT 2022 x86_64 GNU/Linux

**Comment by waylon531** [comment]
This happens to me too, also on Arch. Does anyone know what values for locale actually work?

**Comment by waylon531** [comment]
Here's a snippet of my error log:

```
Unhandled exception. System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name)
   at Content.Shared.Localizations.ContentLocalizationManager.Initialize() in /home/runner/work/space-station-14/space-station-14/Content.Shared/Localizations/ContentLocalizationManager.cs:line 25
   at Content.Client.Entry.EntryPoint.Init() in /home/runner/work/space-station-14/space-station-14/Content.Client/Entry/EntryPoint.cs:line 83
   at Robust.Shared.ContentPack.BaseModLoader.BroadcastRunLevel(ModRunLevel level) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/ContentPack/BaseModLoader.cs:line 79
   at Robust.Client.GameController.StartupContinue(DisplayMode displayMode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 138
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 126
```

**Comment by waylon531** [comment]
And hopefully as my final comment: I have no clue why this is an issue but its probably tied to some arch linux library version stuff, because I see en-US hardcoded into `ContentLocalizationManager.cs`. Maybe it has something to do with some C# global settings that are different? To work around this you can set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="0"` as an environment variable
