### ISSUE TITLE
SS14 crashes on Mac and uses old binary icon.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1057]
<img width="955" alt="Screen Shot 2020-05-31 at 11 59 22 AM" src="https://user-images.githubusercontent.com/49448379/83360472-75e93280-a336-11ea-8f23-3a38c895b3b5.png">

<img width="514" alt="Screen Shot 2020-05-31 at 12 03 08 PM" src="https://user-images.githubusercontent.com/49448379/83360518-b648b080-a336-11ea-87bf-78ab62c020d3.png">

Reproduced by downloading the launcher and trying to connect to Wizard's Den.

**Comment by SweptWasTaken** [comment]
Gotten multiple reports on this so it's not isolated to my machine.

**Comment by stvnksslr** [comment]
Not sure if its related but in the current master branch building the client also crashes, it seems to be related to the audio device selector in the engine. 

if you comment out ALC extension loader the client boots fine on macos.
```             
foreach (var extension in ALC.GetString(ALDevice.Null, AlcGetString.Extensions).Split(' '))
            {
                _alcExtensions.Add(extension);
            }
 ```

```
[INFO] cfg: Configuration Loaded from '/Users/stvnksslr/Library/Application Support/Space Station 14/client_config.toml'
[DEBG] clyde.win: GLFW initialized, version: 3.3.0 Cocoa NSGL EGL OSMesa dynamic.
[DEBG] clyde.ogl: KHR_debug not present, OpenGL debug logging not enabled.
[DEBG] clyde.ogl: OpenGL Vendor: Intel Inc.
[DEBG] clyde.ogl: OpenGL Renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
[DEBG] clyde.ogl: OpenGL Version: 4.1 INTEL-14.6.18
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Robust.Client.Graphics.Clyde.Clyde._audioOpenDevice() in /Users/stvnksslr/Projects/oss/space-station-14/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 75
   at Robust.Client.Graphics.Clyde.Clyde._initializeAudio() in /Users/stvnksslr/Projects/oss/space-station-14/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 43
   at Robust.Client.Graphics.Clyde.Clyde.Initialize() in /Users/stvnksslr/Projects/oss/space-station-14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.cs:line 86
   at Robust.Client.GameController.Startup() in /Users/stvnksslr/Projects/oss/space-station-14/RobustToolbox/Robust.Client/GameController.cs:line 133
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in /Users/stvnksslr/Projects/oss/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 56
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in /Users/stvnksslr/Projects/oss/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 37
   at Robust.Client.ContentStart.Start(String[] args) in /Users/stvnksslr/Projects/oss/space-station-14/RobustToolbox/Robust.Client/ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in /Users/stvnksslr/Projects/oss/space-station-14/Content.Client/Program.cs:line 9
```

**Comment by ShadowCommander** [comment]
@stvnksslr Do sounds still play if you remove that line? Does all the rendering stuff look fine?

**Comment by stvnksslr** [comment]
@ShadowCommander sounds don't play but the client seems to run and load up the map and i can walk around and interact with things. I'm assuming there is a crash case waiting here though, just started poking around with the code recently.

**Comment by hiddenfloret** [comment]
@stvnksslr had the same issue as you. This PR fixed it:
https://github.com/space-wizards/RobustToolbox/pull/1137

**Comment by ShadowCommander** [comment]
@SweptWasTaken Did this get fixed?

**Comment by SweptWasTaken** [comment]
Yes forgot to close, my bad.
