### ISSUE TITLE
Description trick crashes the game

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#10582]
## Description

@moonheart08 Just spent an hour mapping and noticed the new trick menu, tried it out, naming works but as soon as I tried the description one it crashed the server and lost a ton of progress.

**Reproduction**

Boot up locally and try using either the right click > tricks > description or description and name verbs. Put something in the box and hit okay. It'll crash.
**Screenshots**

```
[FATL] unhandled: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Content.Server.Administration.LongString'.
   at Content.Server.Administration.QuickDialogSystem.TryParseQuickDialog[T](QuickDialogEntryType entryType, String input, T& output) in C:\Users\user\D
ocuments\GitHub\space-station-14\Content.Server\Administration\QuickDialogSystem.cs:line 142
   at Content.Server.Administration.QuickDialogSystem.<>c__DisplayClass12_0`1.<OpenDialog>b__0(QuickDialogResponseEvent ev) in C:\Users\user\Documents\G
itHub\space-station-14\Content.Server\Administration\QuickDialogSystem.OpenDialog.cs:line 32
   at Content.Server.Administration.QuickDialogSystem.Handler(QuickDialogResponseEvent msg, EntitySessionEventArgs args) in C:\Users\user\Documents\GitH
ub\space-station-14\Content.Server\Administration\QuickDialogSystem.cs:line 51
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in C:\Users\user\Documents\GitHub\space-station-14\Robus
tToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in C:\Users\user\Documents\GitHub\space-station-14\
RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 169
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in C:\Users\user
\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in C:\Users\user\Doc
uments\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 309
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\Users\user\Documents\GitHub\space-station-14\RobustT
oolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 255
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__9_0(Object _, Object systemMsg) in C:\Users\user\Documents\GitHub\space-station-14\Ro
bustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 40
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in C:\Users\user\Documents\GitHub\space-station-14\R
obustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 285
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\Users\user\Documents\
GitHub\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 140
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\Base
Server.cs:line 676
   at Robust.Server.BaseServer.<SetupMainLoop>b__56_1(Object sender, FrameEventArgs args) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolb
ox\Robust.Server\BaseServer.cs:line 493
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 211
   at Robust.Server.BaseServer.MainLoop() in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 520
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\Users\user\Documents\GitHub\space-statio
n-14\RobustToolbox\Robust.Server\Program.cs:line 75
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\Users\user\Documents\GitHub\space-station-14\RobustT
oolbox\Robust.Server\Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:lin
e 10
   at Content.Server.Program.Main(String[] args) in C:\Users\user\Documents\GitHub\space-station-14\Content.Server\Program.cs:line 9
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Content.Server.Administration.LongString'.
   at Content.Server.Administration.QuickDialogSystem.TryParseQuickDialog[T](QuickDialogEntryType entryType, String input, T& output) in C:\Users\user\D
ocuments\GitHub\space-station-14\Content.Server\Administration\QuickDialogSystem.cs:line 142
   at Content.Server.Administration.QuickDialogSystem.<>c__DisplayClass12_0`1.<OpenDialog>b__0(QuickDialogResponseEvent ev) in C:\Users\user\Documents\G
itHub\space-station-14\Content.Server\Administration\QuickDialogSystem.OpenDialog.cs:line 32
   at Content.Server.Administration.QuickDialogSystem.Handler(QuickDialogResponseEvent msg, EntitySessionEventArgs args) in C:\Users\user\Documents\GitH
ub\space-station-14\Content.Server\Administration\QuickDialogSystem.cs:line 51
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in C:\Users\user\Documents\GitHub\space-station-14\Robus
tToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in C:\Users\user\Documents\GitHub\space-station-14\
RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 169
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in C:\Users\user
\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in C:\Users\user\Doc
uments\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 309
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\Users\user\Documents\GitHub\space-station-14\RobustT
oolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 255
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__9_0(Object _, Object systemMsg) in C:\Users\user\Documents\GitHub\space-station-14\Ro
bustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 40
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in C:\Users\user\Documents\GitHub\space-station-14\R
obustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 285
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\Users\user\Documents\
GitHub\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 140
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\Base
Server.cs:line 676
   at Robust.Server.BaseServer.<SetupMainLoop>b__56_1(Object sender, FrameEventArgs args) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolb
ox\Robust.Server\BaseServer.cs:line 493
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 211
   at Robust.Server.BaseServer.MainLoop() in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 520
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\Users\user\Documents\GitHub\space-statio
n-14\RobustToolbox\Robust.Server\Program.cs:line 75
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\Users\user\Documents\GitHub\space-station-14\RobustT
oolbox\Robust.Server\Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:lin
e 10
   at Content.Server.Program.Main(String[] args) in C:\Users\user\Documents\GitHub\space-station-14\Content.Server\Program.cs:line 9

Process finished```

**Additional context**
<!-- Add any other context about the problem here. Anything you think is related to the issue. -->

**Comment by IProduceWidgets** [comment]
No idea when this was fixed, but I do this daily and it works a treat.
