### ISSUE TITLE
Pneumatic Cannon NAN exception

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#10645]
```
Caught exception in entsys
System.ArgumentException: TimeSpan does not accept floating point Not-a-Number values.
   at Content.Shared.Throwing.ThrowingSystem.TryThrow(EntityUid uid, Vector2 direction, Single strength, Nullable`1 user, Single pushbackRatio, PhysicsComponent physics, TransformComponent transform, Nullable`1 physicsQuery, Nullable`1 xformQuery) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Throwing/ThrowingSystem.cs:line 90
   at Content.Server.PneumaticCannon.PneumaticCannonSystem.Fire(PneumaticCannonComponent comp, FireData data) in /home/runner/work/space-station-14/space-station-14/Content.Server/PneumaticCannon/PneumaticCannonSystem.cs:line 239
   at Content.Server.PneumaticCannon.PneumaticCannonSystem.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/PneumaticCannon/PneumaticCannonSystem.cs:line 80
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 317
 Catcher=entsys Sawmill=runtime
```

**Comment by OctoRocket** [comment]
Can you add more information on when this occurs, otherwise it will be much harder to fix?

**Comment by metalgearsloth** [comment]
It's from grafana.

**Comment by ElectroJr** [comment]
All the info I have is just the stack trace. This came from live servers, I haven't actually reproduced the issue myself.
If you want to try figure it out, `PneumaticCannonSystem.Update()` calls `PneumaticCannonSystem.Fire()` which then calls `ThrowingSystem.TryThrow()`, which uses a NAN value at some point. So I guess go back though those functions and figure out what could be causing a nan value.
