### ISSUE TITLE
Entity names with special characters can break chat

### ISSUE THREAD

**Issue by Elijahrane** [space-wizards/space-station-14#11002]
## Description

1. Take any entity that can talk
2. Talk, see it works.
3. VV your metadata component and instead of being called "entity", name the entity "{entity}" (several of the names in the borg and AI lists use characters like these)
4. Talk, see string formatter breaks

**Comment by Mervill** [comment]
I've done some investigating

The same bug(s) can happen in normal gameplay by setting the cvar `ic.restricted_names = false` to disable the part of name validation that strips special characters from character names.

https://github.com/space-wizards/space-station-14/blob/28ee48ae2fc4f7a8121746b37f591e2951d7fc16/Content.Shared/Preferences/HumanoidCharacterProfile.cs#L386-L390

The bug you reported is actually super interesting because what's happening is, by using the `{}` characters, you're technically inserting an invalid format object into the string formatter:

Name: **Godwin {Hall}**
```
[INFO] CON: > say "hello"
[ERRO] net: [::1]:1212: exception in message handler for MsgChatMessage:
System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at Content.Client.Chat.UI.ChatBox.WriteChatMessage(StoredChatMessage message) in F:\Users\Mervill\Desktop\C#\space-station-14\Content.Client\Chat\UI\ChatBox.xaml.cs:line 408
   at Content.Client.Chat.Managers.ChatManager.OnChatMessage(MsgChatMessage msg) in F:\Users\Mervill\Desktop\C#\space-station-14\Content.Client\Chat\Managers\ChatManager.cs:line 397
   at Robust.Shared.Network.NetManager.<>c__DisplayClass101_0`1.<RegisterNetMessage>b__0(NetMessage msg) in F:\Users\Mervill\Desktop\C#\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 947
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in F:\Users\Mervill\Desktop\C#\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 903
```

Which means, if you know how the code works, you can create this amazing bug:

Name: **Godwin {0}**
![2022-09-29 23_24_00-Window](https://user-images.githubusercontent.com/6798456/193204396-cd178547-467c-4fe6-944a-69327f8d0f89.png)

There's a way to get around this by escaping any `{}` symbols meant to end up as text by using the escape sequences `{{` and `}}`. _Where_ that escaping should be done is something I haven't investigated. You can't necessarily do it right at the name validation step because things that don't use string.format might still want to render the name accurately. 

Also

Name: **Godwin [Hall]**
```
[INFO] CON: > say "Hello"
[ERRO] net: [::1]:1212: exception in message handler for MsgChatMessage:
Pidgin.ParseException: Parse error.
    unexpected H
    expected "color", or "/"
    at line 1, col 9
   at Pidgin.ParserExtensions.GetValueOrThrow[TToken,T](Result`2 result)
   at Robust.Shared.Utility.FormattedMessage.AddMarkup(String markup) in F:\Users\Mervill\Desktop\C#\space-station-14\RobustToolbox\Robust.Shared\Utility\FormattedMessage.MarkupParser.cs:line 69
   at Content.Client.Chat.UI.ChatBox.AddLine(String message, ChatChannel channel, Color color) in F:\Users\Mervill\Desktop\C#\space-station-14\Content.Client\Chat\UI\ChatBox.xaml.cs:line 518
   at Content.Client.Chat.UI.ChatBox.WriteChatMessage(StoredChatMessage message) in F:\Users\Mervill\Desktop\C#\space-station-14\Content.Client\Chat\UI\ChatBox.xaml.cs:line 423
   at Content.Client.Chat.Managers.ChatManager.OnChatMessage(MsgChatMessage msg) in F:\Users\Mervill\Desktop\C#\space-station-14\Content.Client\Chat\Managers\ChatManager.cs:line 397
   at Robust.Shared.Network.NetManager.<>c__DisplayClass101_0`1.<RegisterNetMessage>b__0(NetMessage msg) in F:\Users\Mervill\Desktop\C#\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 947
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in F:\Users\Mervill\Desktop\C#\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 903
```

Using square brackets breaks the Pidgin formatter, so hopefully that also supports escape characters.
