### ISSUE TITLE
Xenoarchaeology telepathic artifact null reference exception

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#11434]
From grafana:
```
Caught exception while dispatching SystemMessage: System.NullReferenceException: Object reference not set to an instance of an object.
   at Content.Server.Xenoarchaeology.XenoArtifacts.Effects.Systems.TelepathicArtifactSystem.OnActivate(EntityUid uid, TelepathicArtifactComponent component, ArtifactActivatedEvent args) in /home/runner/work/space-station-14/space-station-14/Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/TelepathicArtifactSystem.cs:line 25
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 252
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 391
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 176
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 105
   at Content.Server.Xenoarchaeology.XenoArtifacts.ArtifactSystem.ForceActivateArtifact(EntityUid uid, Nullable`1 user, ArtifactComponent component) in /home/runner/work/space-station-14/space-station-14/Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs:line 77
   at Content.Server.Administration.Systems.AdminVerbSystem.<>c__DisplayClass17_1.<AddAdminVerbs>b__3() in /home/runner/work/space-station-14/space-station-14/Content.Server/Administration/Systems/AdminVerbSystem.cs:line 122
   at Content.Server.Verbs.VerbSystem.ExecuteVerb(Verb verb, EntityUid user, EntityUid target, Boolean forced) in /home/runner/work/space-station-14/space-station-14/Content.Server/Verbs/VerbSystem.cs:line 88
   at Content.Shared.Verbs.SharedVerbSystem.HandleExecuteVerb(ExecuteVerbEvent args, EntitySessionEventArgs eventArgs) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Verbs/SharedVerbSystem.cs:line 42
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 47
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 321
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__9_0(Object _, Object systemMsg) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 40
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 295
 Sawmill=net.ent
```

AFAICT this has nothing to do with the verb that was being used to trigger it here, there were a bunch of errors like this in grafana using various activation methods, all erroring in `OnActivate()`.

**Comment by mirrorcult** [comment]
hasnt been seen in the last 30 days and cant repro
