### ISSUE TITLE
Url link buttons in the credits do not work.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1145]
To replicate load into the game and start the lobby. Go into the credits window and try to click on the Patreon or Contributor links. They don't fuckin' work.
![2020-06-16_12-39-57](https://user-images.githubusercontent.com/49448379/84823372-be2e7300-b00d-11ea-9267-e45dad59c226.gif)

Bit of a bruh moment.

**Comment by F77F** [comment]
```Exception has occurred: CLR/System.ComponentModel.Win32Exception
An exception of type 'System.ComponentModel.Win32Exception' occurred in System.Diagnostics.Process.dll but was not handled in user code: 'The system cannot find the file specified.'
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at Robust.Client.UserInterface.UriOpenerWindows.DoOpen(Uri uri) in D:\dev\SpaceStation14\RobustToolbox\Robust.Client\UserInterface\UriOpener.cs:line 100
   at Robust.Client.UserInterface.UriOpenerBase.<>c__DisplayClass0_0.<OpenUri>b__0() in D:\dev\SpaceStation14\RobustToolbox\Robust.Client\UserInterface\UriOpener.cs:line 51
```

**Comment by PJB3005** [comment]
Try again with the latest version of the engine, I probably fixed this.

**Comment by F77F** [comment]
Was already on latest. Same error.

**Comment by PJB3005** [comment]
I forgot to push, try again with https://github.com/space-wizards/RobustToolbox/commit/52833e23c375ce162f4db1b492d6e713deb4c8a3

**Comment by F77F** [comment]
Tested and is working on Windows 10.

**Comment by SweptWasTaken** [comment]
Tested, works. Closing.
