### ISSUE TITLE
Medibots are unrobust

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#11719]
1. They can spam their speech out (kinda bandaided in https://github.com/space-wizards/space-station-14/pull/11718)
2. They require the target to sit still and not move 1 pixel or they won't interact
3. Despite using speechoperator earlier they then use their own speech in the inject operator
4. MedibotInjectOperator has custom stuff for injections which is dirty and I'd prefer NPCs go through the same interaction paths that clients do (checking LOS or whatever is okay).

**Comment by Streaky-Haddock** [comment]
![image](https://user-images.githubusercontent.com/93771043/194703422-f43e5173-00d3-446c-94c8-1abfd135eea6.png)

Since I logged off yesterday ( about 9pm BST) whatever's been committed has made their spam MUCH worse. In the above picture, I deleted its speech component five minutes ago and the speech bubbles were STILL coming up.

**Comment by metalgearsloth** [comment]
Nothing's been committed.

**Comment by ElectroJr** [comment]
> MedibotInjectOperator has custom stuff for injections

It also seems to break and spam exceptions:
```
Caught exception in entsys
System.ArgumentException: Entity is not valid. (Parameter 'uid')
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid, T component, Boolean overwrite) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 267
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 208
   at Content.Server.NPC.HTN.PrimitiveTasks.Operators.Specific.MedibotInjectOperator.Update(NPCBlackboard blackboard, Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/NPC/HTN/PrimitiveTasks/Operators/Specific/MedibotInjectOperator.cs:line 54
   at Content.Server.NPC.HTN.HTNSystem.Update(HTNComponent component, Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/NPC/HTN/HTNSystem.cs:line 250
   at Content.Server.NPC.HTN.HTNSystem.UpdateNPC(Int32& count, Int32 maxUpdates, Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/NPC/HTN/HTNSystem.cs:line 220
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 317
 Catcher=entsys Sawmill=runtime
```
