### ISSUE TITLE
Client crash when controlling and uncontrolling a stunned entity

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1192]
Steps to reproduce:

Spawn Urist
Give yourself a baton and stun Urist
Control Urist with the debug verb
Go back to controlling your original character before the stun ends
Wait for the stun to run out

	Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'Stun' was not present in the dictionary.
		at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
		at Content.Client.GameObjects.Components.Mobs.ClientStatusEffectsComponent.FrameUpdate(Single frameTime) in E:\Projects\C#\space-station-14\Content.Client\GameObjects\Components\Mobs\ClientStatusEffectsComponent.cs:line 137
		at Content.Client.GameObjects.EntitySystems.StatusEffectsSystem.FrameUpdate(Single frameTime) in E:\Projects\C#\space-station-14\Content.Client\GameObjects\EntitySystems\StatusEffectsSystem.cs:line 30
		at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 237
		at Robust.Shared.GameObjects.EntityManager.FrameUpdate(Single frameTime) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 93
		at Content.Client.State.StateBase.FrameUpdate(FrameEventArgs e) in E:\Projects\C#\space-station-14\Content.Client\State\StateBase.cs:line 29
		at Content.Client.State.GameScreenBase.FrameUpdate(FrameEventArgs e) in E:\Projects\C#\space-station-14\Content.Client\State\GameScreenBase.cs:line 55
		at Robust.Client.State.StateManager.FrameUpdate(FrameEventArgs e) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\State\StateManager.cs:line 28
		at Robust.Client.GameController._frameProcessMain(FrameEventArgs frameEventArgs) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 283
		at Robust.Client.GameController.<MainLoop>b__61_3(Object sender, FrameEventArgs args) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 108
		at Robust.Shared.Timing.GameLoop.Run() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 234
		at Robust.Client.GameController.MainLoop(DisplayMode mode) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113
		at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 59
		at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
		at Robust.Client.ContentStart.Start(String[] args) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
		at Content.Client.Program.Main(String[] args) in E:\Projects\C#\space-station-14\Content.Client\Program.cs:line 9

**Comment by DrSmugleaf** [comment]
Fixed by #1388
