### ISSUE TITLE
Surveillance camera exception

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#11960]
From grafana:
```
Can't resolve "Content.Server.SurveillanceCamera.SurveillanceCameraComponent" on entity 338876!
   at Content.Server.SurveillanceCamera.SurveillanceCameraSystem.RemoveActiveViewers(EntityUid camera, HashSet`1 players, Nullable`1 monitor, SurveillanceCameraComponent component) in /home/runner/work/space-station-14/space-station-14/Content.Server/SurveillanceCamera/Systems/SurveillanceCameraSystem.cs:line 363
   at Content.Server.SurveillanceCamera.SurveillanceCameraMonitorSystem.RemoveActiveCamera(EntityUid uid, SurveillanceCameraMonitorComponent monitor) in /home/runner/work/space-station-14/space-station-14/Content.Server/SurveillanceCamera/Systems/SurveillanceCameraMonitorSystem.cs:line 462
   at Content.Server.SurveillanceCamera.SurveillanceCameraMonitorSystem.DisconnectCamera(EntityUid uid, Boolean removeViewers, SurveillanceCameraMonitorComponent monitor) in /home/runner/work/space-station-14/space-station-14/Content.Server/SurveillanceCamera/Systems/SurveillanceCameraMonitorSystem.cs:line 244
   at Content.Server.SurveillanceCamera.SurveillanceCameraMonitorSystem.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/SurveillanceCamera/Systems/SurveillanceCameraMonitorSystem.cs:line 40
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 302
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 133
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 147
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 673
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 213
   at Robust.Server.BaseServer.MainLoop() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 520
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 75
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.Program.Main(String[] args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 25
```

**Comment by IProduceWidgets** [comment]
At a wild guess, this might be the one that occurs when you:

as aghost use a camera monitor, then select a camera you can see with FOV disabled but is behind a wall, experience error/crash.
