### ISSUE TITLE
Eyes in NullSpace

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#12084]
## Description
Just now, about 25% of the server population wasn't able to play the game, as their windows were black as soon as the round started. They could still move around and hear, but saw nothing. I've managed to get these pictures from grafana and a client with error:

Error shown to me as soon as I logged in:
![image](https://user-images.githubusercontent.com/52474532/197084889-c7b02ac7-4ea6-4735-993a-586820c5b709.png)

Error from one of the players with black screen:
![image](https://user-images.githubusercontent.com/52474532/197084929-febc5082-8ee2-4599-8cb6-6daa37d9bbd0.png)

When I logged in as ghost, after receiving that first error, everything was show really weird. If I moved around, different things would show up while the previous shown things would disappear.
![image](https://user-images.githubusercontent.com/52474532/197085001-8f9e7fda-cc4b-46b0-9873-b2c71af1ece3.png)

Grafana Log from that same round (this was repeated so much it spawned the whole grafana log page)
![image](https://user-images.githubusercontent.com/52474532/197085021-dd28f268-0bf1-46d2-b5ce-38f3f4448730.png)

Apparently restarting the server solved it.

No reproduction steps available, terribly sorry. This was very random.

**Comment by Elijahrane** [comment]
I had this problem a few days ago on Nyano. Respawning someone with a black screen would occasionally send them to the ghost world instead, but it didn't fix it like it does for other black screen situations.

**Comment by ElectroJr** [comment]
This specific instance was **probably** caused by a series of errors, where an npc error caused grid deletion / round shutdown errors, which in turn caused a bunch of PVS errors and finally client-side null eye & transform issues.

Hopefully #12085 and space-wizards/RobustToolbox/pull/3355 should stop this from happening again.

**Comment by ElectroJr** [comment]
It seemingly happened again but with a different error, so #12085 probably worked? Note that the engine wasn't yet updated, but has been now.

From grafana:
```
Caught exception in GameTicker
System.NullReferenceException: Object reference not set to an instance of an object.
   at Robust.Server.GameObjects.ActorSystem.OnActorShutdown(EntityUid entity, ActorComponent component, ComponentShutdown args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/ActorSystem.cs:line 124
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 252
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 391
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args, Boolean dispatchByReference) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 581
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 140
   at Robust.Shared.GameObjects.Component.LifeShutdown(IEntityManager entManager) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Component.cs:line 126
   at Robust.Shared.GameObjects.EntityManager.RecursiveDeleteEntity(MetaDataComponent metadata, EntityQuery`1 metaQuery, EntityQuery`1 xformQuery, SharedTransformSystem xformSys) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 388
   at Robust.Shared.GameObjects.EntityManager.RecursiveDeleteEntity(MetaDataComponent metadata, EntityQuery`1 metaQuery, EntityQuery`1 xformQuery, SharedTransformSystem xformSys) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 388
   at Robust.Shared.GameObjects.EntityManager.DeleteEntity(EntityUid e) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 302
   at Content.Server.GameTicking.GameTicker.ResettingCleanup() in /home/runner/work/space-station-14/space-station-14/Content.Server/GameTicking/GameTicker.RoundFlow.cs:line 410
 Catcher=GameTicker Sawmill=runtime
Caught exception while trying to delete entity  (205066), this might corrupt the game state...
 Sawmill=ticker
```

**Comment by slarticodefast** [comment]
This bug is so ancient, it's probably resolved by now.
If it happens again, leave a comment.
