### ISSUE TITLE
Client shudown triggers body system error

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#12168]
Seems to happen pretty consistently after some entity gets gibbed and then the client shuts down.
```
[FATL] unhandled: System.Collections.Generic.KeyNotFoundException: Entity 12081 does not exist, cannot dirty it.
   at Robust.Shared.GameObjects.EntityManager.DirtyEntity(EntityUid uid, MetaDataComponent metadata) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 260
   at Robust.Client.GameObjects.ClientEntityManager.DirtyEntity(EntityUid uid, MetaDataComponent meta) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityManager.cs:line 55
   at Content.Shared.Body.Systems.SharedBodySystem.OnPartRemoved(EntityUid uid, BodyPartComponent part, ComponentRemove args) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\Content.Shared\Body\Systems\SharedBodySystem.Parts.cs:line 57
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 252
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 390
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args, Boolean dispatchByReference) in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 592
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent args) in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 134
   at Robust.Shared.GameObjects.Component.LifeRemoveFromEntity(IEntityManager entManager) in space-station-14\RobustToolbox\Robust.Shared\GameObjects\Component.cs:line 148
   at Robust.Shared.GameObjects.EntityManager.RemoveComponentImmediate(Component component, EntityUid uid, Boolean terminating) in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.Components.cs:line 533
   at Robust.Shared.GameObjects.EntityManager.DisposeComponents(EntityUid uid) in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.Components.cs:line 462
   at Robust.Shared.GameObjects.EntityManager.RecursiveDeleteEntity(MetaDataComponent metadata, EntityQuery`1 metaQuery, EntityQuery`1 xformQuery, SharedTransformSystem xformSys) in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 373
   at Robust.Shared.GameObjects.EntityManager.DeleteEntity(EntityUid e) in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 329
   at Robust.Shared.GameObjects.EntityManager.FlushEntities() in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 419
   at Robust.Shared.GameObjects.EntityManager.Shutdown() in space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 106
   at Robust.Client.GameController.CleanupGameThread() in space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 671
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 134
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 117
   at Robust.Client.GameController.<>c__DisplayClass86_0.<Run>b__0() in space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 84
   at System.Threading.Thread.StartCallback()
```

**Comment by lzk228** [comment]
cannot replicate
