### ISSUE TITLE
Xenoarchaeology exception

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#12459]
From grafana:
```
Caught exception in entsys
System.Collections.Generic.KeyNotFoundException: Entity 87087 does not have a component of type Robust.Shared.GameObjects.TransformComponent
   at Content.Server.Xenoarchaeology.XenoArtifacts.Triggers.Systems.ArtifactDeathTriggerSystem.OnMobStateChanged(MobStateChangedEvent ev) in /home/runner/work/space-station-14/space-station-14/Content.Server/Xenoarchaeology/XenoArtifacts/Triggers/Systems/ArtifactDeathTriggerSystem.cs:line 21
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 321
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 176
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 105
   at Content.Shared.MobState.EntitySystems.SharedMobStateSystem.SetMobState(MobStateComponent component, Nullable`1 old, Nullable`1 current, Nullable`1 origin) in /home/runner/work/space-station-14/space-station-14/Content.Shared/MobState/EntitySystems/SharedMobStateSystem.cs:line 328
   at Content.Shared.MobState.EntitySystems.SharedMobStateSystem.UpdateState(MobStateComponent component, FixedPoint2 damage, Nullable`1 origin) in /home/runner/work/space-station-14/space-station-14/Content.Shared/MobState/EntitySystems/SharedMobStateSystem.cs:line 297
   at Content.Shared.MobState.EntitySystems.SharedMobStateSystem.UpdateState(EntityUid _, MobStateComponent component, DamageChangedEvent args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/MobState/EntitySystems/SharedMobStateSystem.cs:line 193
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 252
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 391
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 176
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 105
   at Content.Shared.Damage.DamageableSystem.DamageChanged(DamageableComponent component, DamageSpecifier damageDelta, Boolean interruptsDoAfters, Nullable`1 origin) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Damage/Systems/DamageableSystem.cs:line 127
   at Content.Shared.Damage.DamageableSystem.TryChangeDamage(Nullable`1 uid, DamageSpecifier damage, Boolean ignoreResistances, Boolean interruptsDoAfters, DamageableComponent damageable, Nullable`1 origin) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Damage/Systems/DamageableSystem.cs:line 192
   at Content.Server.Explosion.EntitySystems.ExplosionSystem.ProcessEntity(EntityUid uid, MapCoordinates epicenter, DamageSpecifier damage, Single throwForce, String id, EntityQuery`1 damageQuery, EntityQuery`1 physicsQuery, TransformComponent xform) in /home/runner/work/space-station-14/space-station-14/Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs:line 399
   at Content.Server.Explosion.EntitySystems.ExplosionSystem.ExplodeTile(BroadphaseComponent lookup, IMapGrid grid, Vector2i tile, Single throwForce, DamageSpecifier damage, MapCoordinates epicenter, HashSet`1 processed, String id, EntityQuery`1 xformQuery, EntityQuery`1 damageQuery, EntityQuery`1 physicsQuery, LookupFlags flags) in /home/runner/work/space-station-14/space-station-14/Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs:line 223
   at Content.Server.Explosion.EntitySystems.Explosion.Process(Int32 processingTarget) in /home/runner/work/space-station-14/space-station-14/Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs:line 753
   at Content.Server.Explosion.EntitySystems.ExplosionSystem.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs:line 128
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 317
 Catcher=entsys Sawmill=runtime
```

**Comment by EmoGarbage404** [comment]
So it begins
