### ISSUE TITLE
AI breaks easily around crates

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#1252]
Crates seem to break the AI pretty easily. 
```
[ERRO] job: Job failed on exception:
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Content.Server.GameObjects.EntitySystems.JobQueues.Job`1.ProcessWrap() in C:\Users\Desktop\GitHub\space-station-14\Content.Server\GameObjects\EntitySystems\JobQueues\Job.cs:line 167
[ERRO] unobserved: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The operation was canceled.)
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Content.Server.GameObjects.EntitySystems.JobQueues.Job`1.ProcessWrap() in C:\Users\Desktop\GitHub\space-station-14\Content.Server\GameObjects\EntitySystems\JobQueues\Job.cs:line 167
   --- End of inner exception stack trace --- 
```

Kept getting the above exception while having a couple AI chase me through a bunch of crates I had strewn about. Couldn't pin down an exact cause, I think the crates just sorta break the AIs pathing because once I got this exception the AI would just stop moving and wouldn't come back.

Also, AI won't open the crates to attack you if you're hiding in them. They could just open them but instead they'll just bang away at the outside of the crate. 

@metalgearsloth

**Comment by metalgearsloth** [comment]
Crates are ignored for pathfinding and they would only be used for collision avoidance.

I'm not 100% on the cause but when the pathfinding is cancelled it can throw an exception if the game's lagging. I tried a few different things but didn't seem to be able to resolve it as I don't know enough about Tasks.

**Comment by SweptWasTaken** [comment]
Pretty sure this was fixed by the above pr.
