### ISSUE TITLE
Ghosting crashes the client

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#1256]
1. Die/ghost
2. Re-enter corpse
3. Crash
The latest commit with this bug is 9f1bdb4b0 wich leads me to think that #1202 is the culprit

**Comment by DrSmugleaf** [comment]
Also happens when your entity is deleted.

	Unhandled exception. System.Collections.Generic.KeyNotFoundException: Entity 3322 does not have a component of type Content.Client.GameObjects.Components.Actor.CharacterInterface
		at Robust.Shared.GameObjects.ComponentManager.GetComponent(EntityUid uid, Type type) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\ComponentManager.cs:line 355
		at Robust.Shared.GameObjects.Entity.RemoveComponent[T]() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 249
		at Content.Client.EntryPoint.DetachPlayerFromEntity(EntityDetachedEventArgs eventArgs) in E:\Projects\C#\space-station-14\Content.Client\EntryPoint.cs:line 130
		at Robust.Client.Player.LocalPlayer.DetachEntity() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\Player\LocalPlayer.cs:line 114
		at Robust.Client.Player.LocalPlayer.AttachEntity(IEntity entity) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\Player\LocalPlayer.cs:line 77
		at Robust.Client.Player.PlayerManager.UpdateAttachedEntity(Nullable`1 entity) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\Player\PlayerManager.cs:line 136
		at Robust.Client.Player.PlayerManager.ApplyPlayerStates(IEnumerable`1 list) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\Player\PlayerManager.cs:line 103
		at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 357
		at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 187
		at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 273
		at Robust.Client.GameController.<MainLoop>b__61_0(Object sender, FrameEventArgs args) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 84
		at Robust.Shared.Timing.GameLoop.Run() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 191
		at Robust.Client.GameController.MainLoop(DisplayMode mode) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113
		at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 59
		at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
		at Robust.Client.ContentStart.Start(String[] args) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
		at Content.Client.Program.Main(String[] args) in E:\Projects\C#\space-station-14\Content.Client\Program.cs:line 9
