### ISSUE TITLE
Controlling another player's mob crashes the server

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1266]
Unhandled exception. System.ArgumentException: Visit target already has a session. (Parameter 'entity')
		at Content.Server.Mobs.Mind.TransferTo(IEntity entity) in E:\Projects\C#\space-station-14\Content.Server\Mobs\Mind.cs:line 177
		at Content.Server.GlobalVerbs.ControlMobVerb.Activate(IEntity user, IEntity target) in E:\Projects\C#\space-station-14\Content.Server\GlobalVerbs\ControlMobVerb.cs:line 59
		at Content.Server.GameObjects.EntitySystems.VerbSystem.UseVerb(UseVerbMessage use, EntitySessionEventArgs eventArgs) in E:\Projects\C#\space-station-14\Content.Server\GameObjects\EntitySystems\VerbSystem.cs:line 77
		at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 23
		at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(Object ev) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 151
		at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 285
		at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 201
		at Robust.Shared.GameObjects.EntityManager.<Initialize>b__22_1(Object sender, Object systemMsg) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 64
		at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 161
		at Robust.Server.GameObjects.ServerEntityNetworkManager.Update() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 56
		at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 84
		at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 965
		at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 465
		at Robust.Server.BaseServer.<MainLoop>b__40_0(Object sender, FrameEventArgs args) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 335
		at Robust.Shared.Timing.GameLoop.Run() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 191
		at Robust.Server.BaseServer.MainLoop() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 343
		at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 89
		at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 54
		at System.Threading.Tasks.Task.InnerInvoke()
		at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
		at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by SweptWasTaken** [comment]
This doesn't crash the server anymore, but it does something else so i'm making a new issue.
