### ISSUE TITLE
Nuke Ops doesn't work (again ((for like the 18th time now)))

### ISSUE THREAD

**Issue by Ablankmann** [space-wizards/space-station-14#12960]
## Description

Name explains it all. The gamemode Nuclear Operatives doesn't work.

**Reproduction**

Start up a game with the Nukeops gamerule
Notice that the game doesn't start, and instantly restarts

**Additional context**

Might've been https://github.com/space-wizards/space-station-14/pull/12948 that caused it, unsure, but it's the only recent PR i've noticed that's touched nuke ops with a stick

**Comment by DrSmugleaf** [comment]
> Might've been #12948 that caused it, unsure, but it's the only recent PR i've noticed that's touched nuke ops with a stick

It's not, but here's a nuke ops related error from Grafana:
```
Caught exception in GameTicker
System.ArgumentException: An item with the same key has already been added. Key: Commander Pi
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Content.Server.GameTicking.Rules.NukeopsRuleSystem.OnPlayersSpawning(RulePlayerSpawningEvent ev) in /home/runner/work/space-station-14/space-station-14/Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs:line 552
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 321
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T toRaise) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 260
   at Content.Server.GameTicking.GameTicker.SpawnPlayers(List`1 readyPlayers, Dictionary`2 profiles, Boolean force) in /home/runner/work/space-station-14/space-station-14/Content.Server/GameTicking/GameTicker.Spawning.cs:line 40
   at Content.Server.GameTicking.GameTicker.StartRound(Boolean force) in /home/runner/work/space-station-14/space-station-14/Content.Server/GameTicking/GameTicker.RoundFlow.cs:line 236
 Catcher=GameTicker Sawmill=runtime
```

Here's the most recent PR that changed that line:
https://github.com/space-wizards/space-station-14/commit/250fde746f8834f2f80a4fde3f715b97288463f0
