### ISSUE TITLE
bluespace portal exception

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#13338]
## Description

```[ERRO] root: Caught exception while trying to call shutdown on component of entity 'bluespace portal (123401, PortalRed)'
System.Collections.Generic.KeyNotFoundException: Entity 125491 does not have a component of type Robust.Shared.GameObjects.MetaDataComponent
   at Content.Shared.Teleportation.Systems.LinkedEntitySystem.OnLinkShutdown(EntityUid uid, LinkedEntityComponent component, ComponentShutdown args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Teleportation/Systems/LinkedEntitySystem.cs:line 43
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args, Boolean dispatchByReference) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 581
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 140
   at Robust.Shared.GameObjects.Component.LifeShutdown(IEntityManager entManager) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Component.cs:line 127
   at Robust.Shared.GameObjects.EntityManager.RecursiveDeleteEntity(MetaDataComponent metadata, EntityQuery`1 metaQuery, EntityQuery`1 xformQuery, SharedTransformSystem xformSys) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 446
[ERRO] root: Caught exception during immediate component removal. Entity=bluespace portal (123401, PortalRed), type=Content.Shared.Teleportation.Components.LinkedEntityComponent
[ERRO] runtime: Caught exception in "RemoveComponentImmediate"
System.Collections.Generic.KeyNotFoundException: Entity 125491 does not have a component of type Robust.Shared.GameObjects.MetaDataComponent
   at Content.Shared.Teleportation.Systems.LinkedEntitySystem.OnLinkShutdown(EntityUid uid, LinkedEntityComponent component, ComponentShutdown args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Teleportation/Systems/LinkedEntitySystem.cs:line 43
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args, Boolean dispatchByReference) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 581
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 140
   at Robust.Shared.GameObjects.Component.LifeShutdown(IEntityManager entManager) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Component.cs:line 127
   at Robust.Shared.GameObjects.EntityManager.RemoveComponentImmediate(Component component, EntityUid uid, Boolean terminating) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 557
```

**Reproduction**

Saw it happen after round end, no clue.
**Screenshots**

**Additional context**

**Comment by mirrorcult** [comment]
ree
