### ISSUE TITLE
Having the AHelp window open while joining the game causes an exception

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#13699]
**Reproduction**
1. Run `golobby`
2. Run `startround`
3. Open the AHelp window
4. Press the Join button and pick any job

**Additional context**

```
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 32
   at Content.Client.UserInterface.Systems.Bwoink.AHelpUIController.OnStateEntered(GameplayState state) in space-station-14/Content.Client/UserInterface/Systems/Bwoink/AHelpUIController.cs:line 42
   at Robust.Client.UserInterface.UserInterfaceManager.OnStateChanged(StateChangedEventArgs args) in space-station-14/RobustToolbox/Robust.Client/UserInterface/Controllers/UserInterfaceManager.Controllers.cs:line 298
   at Robust.Client.State.StateManager.SwitchToState(Type type) in space-station-14/RobustToolbox/Robust.Client/State/StateManager.cs:line 51
   at Robust.Client.State.StateManager.RequestStateChange(Type type) in space-station-14/RobustToolbox/Robust.Client/State/StateManager.cs:line 36
   at Robust.Client.State.StateManager.RequestStateChange[T]() in space-station-14/RobustToolbox/Robust.Client/State/StateManager.cs:line 28
   at Content.Client.GameTicking.Managers.ClientGameTicker.JoinGame(TickerJoinGameEvent message) in space-station-14/Content.Client/GameTicking/Managers/ClientGameTicker.cs:line 111
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 169
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 309
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 255
   at Robust.Client.GameObjects.ClientEntityManager.<Initialize>b__9_0(Object _, Object systemMsg) in space-station-14/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 32
   at Robust.Client.GameObjects.ClientEntityManager.DispatchReceivedNetworkMsg(EntityEventArgs msg) in space-station-14/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 179
   at Robust.Client.GameObjects.ClientEntityManager.DispatchReceivedNetworkMsg(MsgEntity message) in space-station-14/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 170
   at Robust.Client.GameObjects.ClientEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in space-station-14/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 121
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 371
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 517
   at Robust.Client.GameController.<StartupContinue>b__50_0(Object sender, FrameEventArgs args) in space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 182
   at Robust.Shared.Timing.GameLoop.Run() in space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 218
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 133
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 118
   at Robust.Client.GameController.<>c__DisplayClass91_0.<Run>b__0() in space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 85
```

**Comment by lzk228** [comment]
cannot reproduce, seems to be resolved
