### ISSUE TITLE
fatal unhandled in client

### ISSUE THREAD

**Issue by aeosynth** [space-wizards/space-station-14#1385]
I was punching a plant and then I disconnected from the server? the gui was still alive but I started sliding right

<details><summary>log</summary>
<p>

```
[FATL] unhandled: System.InvalidOperationException: Map 0 does not have a set map entity.
   at Robust.Shared.Map.MapManager.GetMapEntity(MapId mapId) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/Map/MapManager.cs:line 377
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.DetachParent() in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs:line 424
   at Robust.Server.GameObjects.Components.Container.BaseContainer.Remove(IEntity toremove) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/Components/Container/Container.cs:line 181
   at Content.Server.GameObjects.Components.EntityStorageComponent.EmptyContents() in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 271
   at Content.Server.GameObjects.Components.EntityStorageComponent.OpenStorage() in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 179
   at Content.Server.GameObjects.Components.EntityStorageComponent.TryOpenStorage(IEntity user) in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 312
   at Content.Server.GameObjects.Components.EntityStorageComponent.ToggleOpen(IEntity user) in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 141
   at Content.Server.GameObjects.Components.EntityStorageComponent.Activate(ActivateEventArgs eventArgs) in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 124
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.InteractionActivate(IEntity user, IEntity used) in /home/james/code/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 137
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.Interaction(IEntity user, IEntity attacked) in /home/james/code/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 434
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.UserInteraction(IEntity player, GridCoordinates coordinates, EntityUid clickedUid) in /home/james/code/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 327
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.HandleClientUseItemInHand(ICommonSession session, GridCoordinates coords, EntityUid uid) in /home/james/code/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 219
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass2_0.<.ctor>b__0(PointerInputCmdArgs& args) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 92
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(ICommonSession session, InputCmdMessage message) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 112
   at Robust.Server.GameObjects.EntitySystems.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/InputSystem.cs:line 65
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 23
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(Object ev) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.cs:line 151
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.cs:line 285
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.cs:line 201
   at Robust.Shared.GameObjects.EntityManager.<Initialize>b__22_1(Object sender, Object systemMsg) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 64
   at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityNetworkManager.cs:line 161
   at Robust.Server.GameObjects.ServerEntityNetworkManager.Update() in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityNetworkManager.cs:line 56
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 84
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 959
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 529
   at Robust.Server.BaseServer.<MainLoop>b__41_0(Object sender, FrameEventArgs args) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 402
   at Robust.Shared.Timing.GameLoop.Run() in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 191
   at Robust.Server.BaseServer.MainLoop() in /home/james/code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 407
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 89
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in /home/james/code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 49
   at Robust.Server.ContentStart.Start(String[] args) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/james/code/space-station-14/Content.Server/Program.cs:line 9
Unhandled exception. System.InvalidOperationException: Map 0 does not have a set map entity.
   at Robust.Shared.Map.MapManager.GetMapEntity(MapId mapId) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/Map/MapManager.cs:line 377
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.DetachParent() in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs:line 424
   at Robust.Server.GameObjects.Components.Container.BaseContainer.Remove(IEntity toremove) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/Components/Container/Container.cs:line 181
   at Content.Server.GameObjects.Components.EntityStorageComponent.EmptyContents() in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 271
   at Content.Server.GameObjects.Components.EntityStorageComponent.OpenStorage() in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 179
   at Content.Server.GameObjects.Components.EntityStorageComponent.TryOpenStorage(IEntity user) in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 312
   at Content.Server.GameObjects.Components.EntityStorageComponent.ToggleOpen(IEntity user) in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 141
   at Content.Server.GameObjects.Components.EntityStorageComponent.Activate(ActivateEventArgs eventArgs) in /home/james/code/space-station-14/Content.Server/GameObjects/Components/Items/Storage/EntityStorageComponent.cs:line 124
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.InteractionActivate(IEntity user, IEntity used) in /home/james/code/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 137
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.Interaction(IEntity user, IEntity attacked) in /home/james/code/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 434
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.UserInteraction(IEntity player, GridCoordinates coordinates, EntityUid clickedUid) in /home/james/code/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 327
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.HandleClientUseItemInHand(ICommonSession session, GridCoordinates coords, EntityUid uid) in /home/james/code/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 219
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass2_0.<.ctor>b__0(PointerInputCmdArgs& args) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 92
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(ICommonSession session, InputCmdMessage message) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 112
   at Robust.Server.GameObjects.EntitySystems.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/InputSystem.cs:line 65
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 23
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(Object ev) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.cs:line 151
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.cs:line 285
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.cs:line 201
   at Robust.Shared.GameObjects.EntityManager.<Initialize>b__22_1(Object sender, Object systemMsg) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 64
   at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityNetworkManager.cs:line 161
   at Robust.Server.GameObjects.ServerEntityNetworkManager.Update() in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityNetworkManager.cs:line 56
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime) in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 84
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 959
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 529
   at Robust.Server.BaseServer.<MainLoop>b__41_0(Object sender, FrameEventArgs args) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 402
   at Robust.Shared.Timing.GameLoop.Run() in /home/james/code/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 191
   at Robust.Server.BaseServer.MainLoop() in /home/james/code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 407
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 89
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in /home/james/code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 49
   at Robust.Server.ContentStart.Start(String[] args) in /home/james/code/space-station-14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/james/code/space-station-14/Content.Server/Program.cs:line 9

```
</p>
</details>

**Comment by F77F** [comment]
unable to reproduce.  tried every plant.

**Comment by MemeProof** [comment]
May be related to https://github.com/space-wizards/space-station-14/issues/1422

**Comment by metalgearsloth** [comment]
Should be okay now and if it isn't then we'll re-open and re-investigate.
