### ISSUE TITLE
Duplicate Overlay after reconnecting while dead

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1392]
Steps:
1. Join Server
2. Die (and stay in the body)
3. Reconnect

While rejoining:
```
[FATL] unhandled: System.InvalidOperationException: We already have an overlay with ID 'CircleMaskOverlay'
   at Robust.Client.Graphics.Overlays.OverlayManager.AddOverlay(Overlay overlay) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\Graphics\Overlays\OverlayManager.cs:line 32
   at Content.Client.GameObjects.Components.Mobs.ClientOverlayEffectsComponent.AddOverlay(OverlayContainer container) in D:\Visual Studio\Github\space-station-14\Content.Client\GameObjects\Components\Mobs\ClientOverlayEffectsComponent.cs:line 113
   at Content.Client.GameObjects.Components.Mobs.ClientOverlayEffectsComponent.SetEffects(List`1 newOverlays) in D:\Visual Studio\Github\space-station-14\Content.Client\GameObjects\Components\Mobs\ClientOverlayEffectsComponent.cs:line 97
   at Content.Client.GameObjects.Components.Mobs.ClientOverlayEffectsComponent.HandleMessage(ComponentMessage message, IComponent component) in D:\Visual Studio\Github\space-station-14\Content.Client\GameObjects\Components\Mobs\ClientOverlayEffectsComponent.cs:line 54
   at Robust.Shared.GameObjects.Entity.SendMessage(IComponent owner, ComponentMessage message) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 215
   at Robust.Client.Player.LocalPlayer.AttachEntity(IEntity entity) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\Player\LocalPlayer.cs:line 89
   at Robust.Client.Player.PlayerManager.UpdateAttachedEntity(Nullable`1 entity) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\Player\PlayerManager.cs:line 136
   at Robust.Client.Player.PlayerManager.ApplyPlayerStates(IEnumerable`1 list) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\Player\PlayerManager.cs:line 103
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 357
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 187
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 273
   at Robust.Client.GameController.<MainLoop>b__62_0(Object sender, FrameEventArgs args) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 84
   at Robust.Shared.Timing.GameLoop.Run() in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 191
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 59
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
   at Robust.Client.ContentStart.Start(String[] args) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in D:\Visual Studio\Github\space-station-14\Content.Client\Program.cs:line 9
Unhandled exception. System.InvalidOperationException: We already have an overlay with ID 'CircleMaskOverlay'
   at Robust.Client.Graphics.Overlays.OverlayManager.AddOverlay(Overlay overlay) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\Graphics\Overlays\OverlayManager.cs:line 32
   at Content.Client.GameObjects.Components.Mobs.ClientOverlayEffectsComponent.AddOverlay(OverlayContainer container) in D:\Visual Studio\Github\space-station-14\Content.Client\GameObjects\Components\Mobs\ClientOverlayEffectsComponent.cs:line 113
   at Content.Client.GameObjects.Components.Mobs.ClientOverlayEffectsComponent.SetEffects(List`1 newOverlays) in D:\Visual Studio\Github\space-station-14\Content.Client\GameObjects\Components\Mobs\ClientOverlayEffectsComponent.cs:line 97
   at Content.Client.GameObjects.Components.Mobs.ClientOverlayEffectsComponent.HandleMessage(ComponentMessage message, IComponent component) in D:\Visual Studio\Github\space-station-14\Content.Client\GameObjects\Components\Mobs\ClientOverlayEffectsComponent.cs:line 54
   at Robust.Shared.GameObjects.Entity.SendMessage(IComponent owner, ComponentMessage message) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 215
   at Robust.Client.Player.LocalPlayer.AttachEntity(IEntity entity) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\Player\LocalPlayer.cs:line 89
   at Robust.Client.Player.PlayerManager.UpdateAttachedEntity(Nullable`1 entity) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\Player\PlayerManager.cs:line 136
   at Robust.Client.Player.PlayerManager.ApplyPlayerStates(IEnumerable`1 list) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\Player\PlayerManager.cs:line 103
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 357
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 187
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 273
   at Robust.Client.GameController.<MainLoop>b__62_0(Object sender, FrameEventArgs args) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 84
   at Robust.Shared.Timing.GameLoop.Run() in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 191
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 59
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
   at Robust.Client.ContentStart.Start(String[] args) in D:\Visual Studio\Github\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in D:\Visual Studio\Github\space-station-14\Content.Client\Program.cs:line 9
```

If you do this on a release build, you can't respawn.

**Comment by F77F** [comment]
```cs
        public void AddOverlay(Overlay overlay)
        {
            if (!_overlays.ContainsKey(overlay.ID))
            {
                //throw new InvalidOperationException($"We already have an overlay with ID '{overlay.ID}'");
                _overlays.Add(overlay.ID, overlay);
            }
        }
```
wouldn't this fix the problem? why would it need to throw an exception?

**Comment by exp111** [comment]
We could leave the exception and wrap a TryAddOverlay method around it, cause no method that calls this, catches the exception.
Or just remove it.

Just noticed: Shouldn't this be moved to RobustToolbox?

**Comment by DrSmugleaf** [comment]
Both of these problems have been fixed.
