### ISSUE TITLE
Opening some emergency closets crashes the server

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#1418]
- For all of the lockers found so far, one of their oxygen masks (unknown whether it's the one that they spawn with or one that a toolbox within them is depositing outside of itself and into its containing locker) has an invalid map id of 0 on the server, but of 1 on the client except in some rare cases where refreshing the transform component makes it correctly display map id 0 in ViewVariables.
- In one rare case the top locker didn't crash when opening it.
- Removing all of the code from EmergencyClosetFillComponent does not fix it.

![image](https://user-images.githubusercontent.com/10968691/87851170-8d847680-c8f6-11ea-8c7b-df85b686eaa1.png)
![dotnet_7NmpM42H1n](https://user-images.githubusercontent.com/10968691/87851842-d17a7a00-c8fc-11ea-9054-6a0f1769145a.png)

<details>
<summary>Error message</summary>

```
System.InvalidOperationException: Map 0 does not have a set map entity.
	at Robust.Shared.Map.MapManager.GetMapEntity(MapId mapId) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Map\MapManager.cs:377
	at Robust.Shared.GameObjects.Components.Transform.TransformComponent.DetachParent() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Transform\TransformComponent.cs:424
	at Robust.Server.GameObjects.Components.Container.BaseContainer.Remove(IEntity toremove) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\GameObjects\Components\Container\Container.cs:181
	at Content.Server.GameObjects.Components.EntityStorageComponent.EmptyContents() in E:\Projects\C#\space-station-14\Content.Server\GameObjects\Components\Items\Storage\EntityStorageComponent.cs:271
	at Content.Server.GameObjects.Components.EntityStorageComponent.OpenStorage() in E:\Projects\C#\space-station-14\Content.Server\GameObjects\Components\Items\Storage\EntityStorageComponent.cs:179
	at Content.Server.GameObjects.Components.EntityStorageComponent.TryOpenStorage(IEntity user) in E:\Projects\C#\space-station-14\Content.Server\GameObjects\Components\Items\Storage\EntityStorageComponent.cs:312
	at Content.Server.GameObjects.Components.EntityStorageComponent.ToggleOpen(IEntity user) in E:\Projects\C#\space-station-14\Content.Server\GameObjects\Components\Items\Storage\EntityStorageComponent.cs:141
	at Content.Server.GameObjects.Components.EntityStorageComponent.Activate(ActivateEventArgs eventArgs) in E:\Projects\C#\space-station-14\Content.Server\GameObjects\Components\Items\Storage\EntityStorageComponent.cs:124
	at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.InteractionActivate(IEntity user, IEntity used) in E:\Projects\C#\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionSystem.cs:137
	at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.Interaction(IEntity user, IEntity attacked) in E:\Projects\C#\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionSystem.cs:434
	at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.UserInteraction(IEntity player, GridCoordinates coordinates, EntityUid clickedUid) in E:\Projects\C#\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionSystem.cs:327
	at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.HandleClientUseItemInHand(ICommonSession session, GridCoordinates coords, EntityUid uid) in E:\Projects\C#\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionSystem.cs:219
	at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass2_0.<.ctor>b__0(PointerInputCmdArgs& args) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:92
	at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(ICommonSession session, InputCmdMessage message) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:112
	at Robust.Server.GameObjects.EntitySystems.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySystems\InputSystem.cs:65
	at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:23
	at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(Object ev) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:151
	at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:285
	at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:201
	at Robust.Shared.GameObjects.EntityManager.<Initialize>b__22_1(Object sender, Object systemMsg) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:64
	at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:161
	at Robust.Server.GameObjects.ServerEntityNetworkManager.Update() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:56
	at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:84
	at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:959
	at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:529
	at Robust.Server.BaseServer.<MainLoop>b__41_0(Object sender, FrameEventArgs args) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:402
	at Robust.Shared.Timing.GameLoop.Run() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:191
	at Robust.Server.BaseServer.MainLoop() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:407
	at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\Program.cs:89
	at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\Program.cs:54
	at at System.Threading.Tasks.Task.InnerInvoke()
	at at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
	at at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	at at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	at at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	at Robust.Server.Program.Start(String[] args, Boolean contentStart) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\Program.cs:49
	at Robust.Server.ContentStart.Start(String[] args) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:10
	at Content.Server.Program.Main(String[] args) in E:\Projects\C#\space-station-14\Content.Server\Program.cs:9
```
</details>

**Comment by DrSmugleaf** [comment]
This was fixed at some point for the two lockers in the images. It's still a good idea to clean up saltern.yml in #1422 however.
