### ISSUE TITLE
Clicking EntityButton of deleted object crashes the client: 'Tried to get component on a deleted entity.'

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#1454]
**To reproduce:**
Use left mouse button to drag your character somewhere
While holding left mouse button, press right mouse button
'drag shadow' should appear as a button
Let go of left mouse button and click the button
The client will crash, giving `Tried to get component on a deleted entity.`

Clicking any EntityButton of a deleted item will give this error. Right clicking an item, deleting it via the server and then clicking the EntityButton will also crash the client.

<details><summary>Error</summary>

```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 48
   at Robust.Shared.GameObjects.Entity.TryGetComponent[T](T& component) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 291
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.get_GridID() in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Transform\TransformComponent.cs:line 67
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.get_GridPosition() in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Transform\TransformComponent.cs:line
198
   at Content.Client.GameObjects.EntitySystems.VerbSystem.EntityButton.KeyBindDown(GUIBoundKeyEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\Content.Client\GameObjects\EntitySystems\VerbSystem.cs:line 447
   at Robust.Client.UserInterface.UserInterfaceManager.<>c.<KeyBindDown>b__76_0(Control c, GUIBoundKeyEventArgs ev) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.
cs:line 292
   at Robust.Client.UserInterface.UserInterfaceManager._doGuiInput[T](Control control, T guiEvent, Action`2 action, Boolean ignoreStop) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\UserInterface\U
serInterfaceManager.cs:line 676
   at Robust.Client.UserInterface.UserInterfaceManager.KeyBindDown(BoundKeyEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 292
   at Robust.Client.UserInterface.UserInterfaceManager.OnUIKeyBindStateChanged(BoundKeyEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 772
   at Robust.Client.Input.InputManager.SetBindState(KeyBinding binding, BoundKeyState state, Boolean uiOnly) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 247
   at Robust.Client.Input.InputManager.DownBind(KeyBinding binding, Boolean uiOnly, Boolean isRepeat) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 224
   at Robust.Client.Input.InputManager.KeyDown(KeyEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 165
   at Robust.Client.GameController.KeyDown(KeyEventArgs keyEvent) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Input.cs:line 12
   at Robust.Client.Graphics.Clyde.Clyde.EmitKeyEvent(Key key, InputAction action, KeyModifiers mods) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Clyde.Windowing.cs:line 361
   at Robust.Client.Graphics.Clyde.Clyde.OnGlfwMouseButton(Window* window, MouseButton button, InputAction action, KeyModifiers mods) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Cl
yde.Windowing.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at Robust.Client.Graphics.Clyde.Clyde.ProcessInput(FrameEventArgs frameEventArgs) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Clyde.Windowing.cs:line 489
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 269
   at Robust.Client.GameController.<MainLoop>b__66_2(Object sender, FrameEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 100
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 162
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 59
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
   at Robust.Client.ContentStart.Start(String[] args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in C:\Users\vince\RiderProjects\space-station-14\Content.Client\Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 48
   at Robust.Shared.GameObjects.Entity.TryGetComponent[T](T& component) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 291
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.get_GridID() in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Transform\TransformComponent.cs:line 67
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.get_GridPosition() in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Transform\TransformComponent.cs:line
198
   at Content.Client.GameObjects.EntitySystems.VerbSystem.EntityButton.KeyBindDown(GUIBoundKeyEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\Content.Client\GameObjects\EntitySystems\VerbSystem.cs:line 447
   at Robust.Client.UserInterface.UserInterfaceManager.<>c.<KeyBindDown>b__76_0(Control c, GUIBoundKeyEventArgs ev) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.
cs:line 292
   at Robust.Client.UserInterface.UserInterfaceManager._doGuiInput[T](Control control, T guiEvent, Action`2 action, Boolean ignoreStop) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\UserInterface\U
serInterfaceManager.cs:line 676
   at Robust.Client.UserInterface.UserInterfaceManager.KeyBindDown(BoundKeyEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 292
   at Robust.Client.UserInterface.UserInterfaceManager.OnUIKeyBindStateChanged(BoundKeyEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 772
   at Robust.Client.Input.InputManager.SetBindState(KeyBinding binding, BoundKeyState state, Boolean uiOnly) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 247
   at Robust.Client.Input.InputManager.DownBind(KeyBinding binding, Boolean uiOnly, Boolean isRepeat) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 224
   at Robust.Client.Input.InputManager.KeyDown(KeyEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 165
   at Robust.Client.GameController.KeyDown(KeyEventArgs keyEvent) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Input.cs:line 12
   at Robust.Client.Graphics.Clyde.Clyde.EmitKeyEvent(Key key, InputAction action, KeyModifiers mods) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Clyde.Windowing.cs:line 361
   at Robust.Client.Graphics.Clyde.Clyde.OnGlfwMouseButton(Window* window, MouseButton button, InputAction action, KeyModifiers mods) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Cl
yde.Windowing.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at Robust.Client.Graphics.Clyde.Clyde.ProcessInput(FrameEventArgs frameEventArgs) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Clyde.Windowing.cs:line 489
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 269
   at Robust.Client.GameController.<MainLoop>b__66_2(Object sender, FrameEventArgs args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 100
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 162
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 59
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
   at Robust.Client.ContentStart.Start(String[] args) in C:\Users\vince\RiderProjects\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in C:\Users\vince\RiderProjects\space-station-14\Content.Client\Program.cs:line 9
```
</details>

**Comment by PJB3005** [comment]
This one's pretty good.
