### ISSUE TITLE
Opening/closing any crate that is not the default 'crate' throws a exception

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1489]
Open up/close the internals, radiation gear, medical, plastic, hydroponics crate & freezer to get:
```
[ERRO] go.comp.sprite: Layer with key 'Welded' does not exist, cannot set visibility! Trace:
   at System.Environment.get_StackTrace()
   at Robust.Client.GameObjects.SpriteComponent.LayerSetVisible(Object layerKey, Boolean visible) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs:line 834
   at Content.Client.GameObjects.Components.Storage.StorageVisualizer.OnChangeData(AppearanceComponent component)
   at Robust.Client.GameObjects.EntitySystems.AppearanceSystem.UpdateComponent(AppearanceComponent component) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameObjects/EntitySystems/AppearanceSystem.cs:line 30
   at Robust.Client.GameObjects.EntitySystems.AppearanceSystem.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameObjects/EntitySystems/AppearanceSystem.cs:line 15
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 245
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController.cs:line 304
   at Robust.Shared.Timing.GameLoop.Run() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 243
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 115
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 61
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 37
   at Robust.Client.GameController.Main(String[] args) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 22
```

This may be fixed by #1253

**Comment by SweptWasTaken** [comment]
This will be fixed by my crate pr. I will close this issue when it's fixed.

**Comment by SweptWasTaken** [comment]
Fixed by my crate pr, as promised.
