### ISSUE TITLE
Placing the last tile in a stack crashes the server

### ISSUE THREAD

**Issue by StrawberryMoses** [space-wizards/space-station-14#1496]
To reproduce:

- Use a crowbar to pry up one tile
- Place the tile back where it was

```[FATL] unhandled: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Tried to get component on a deleted entity.)) (Tried to get component on a deleted entity.)
 ---> Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 48
   at Robust.Shared.GameObjects.Entity.TryGetComponent[T](T& component) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 291
   at Robust.Server.GameObjects.ServerEntityManager.AddContainedRecursive(IEntity ent, HashSet`1 set) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 304
   at Robust.Server.GameObjects.ServerEntityManager.AddContainedRecursive(IEntity ent, HashSet`1 set) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 317
   at Robust.Server.GameObjects.ServerEntityManager.IncludeRelatives(IEnumerable`1 children, HashSet`1 set) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 289
   at Robust.Server.GameObjects.ServerEntityManager.UpdatePlayerSeenEntityStates(GameTick fromTick, IPlayerSession player, Single range) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManage
r.cs:line 482
   at Robust.Server.GameStates.ServerGameStateManager.<>c__DisplayClass17_0.<SendGameStateUpdate>g__GenerateMail|0(IPlayerSession session) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameStates\ServerGameStateMa
nager.cs:line 143
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, In
t32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Robust.Server.GameStates.ServerGameStateManager.SendGameStateUpdate() in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameStates\ServerGameStateManager.cs:line 175
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 534
   at Robust.Server.BaseServer.<MainLoop>b__41_0(Object sender, FrameEventArgs args) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 403
   at Robust.Shared.Timing.GameLoop.Run() in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 195
   at Robust.Server.BaseServer.MainLoop() in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 408
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 89
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 49
   at Robust.Server.ContentStart.Start(String[] args) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in E:\Code\ss14\space-station-14\Content.Server\Program.cs:line 9
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (Tried to get component on a deleted entity.)) (Tried to get component on a deleted entity.)
 ---> Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 48
   at Robust.Shared.GameObjects.Entity.TryGetComponent[T](T& component) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 291
   at Robust.Server.GameObjects.ServerEntityManager.AddContainedRecursive(IEntity ent, HashSet`1 set) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 304
   at Robust.Server.GameObjects.ServerEntityManager.AddContainedRecursive(IEntity ent, HashSet`1 set) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 317
   at Robust.Server.GameObjects.ServerEntityManager.IncludeRelatives(IEnumerable`1 children, HashSet`1 set) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 289
   at Robust.Server.GameObjects.ServerEntityManager.UpdatePlayerSeenEntityStates(GameTick fromTick, IPlayerSession player, Single range) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManage
r.cs:line 482
   at Robust.Server.GameStates.ServerGameStateManager.<>c__DisplayClass17_0.<SendGameStateUpdate>g__GenerateMail|0(IPlayerSession session) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameStates\ServerGameStateMa
nager.cs:line 143
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, In
t32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Robust.Server.GameStates.ServerGameStateManager.SendGameStateUpdate() in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\GameStates\ServerGameStateManager.cs:line 175
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 534
   at Robust.Server.BaseServer.<MainLoop>b__41_0(Object sender, FrameEventArgs args) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 403
   at Robust.Shared.Timing.GameLoop.Run() in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 195
   at Robust.Server.BaseServer.MainLoop() in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 408
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 89
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 49
   at Robust.Server.ContentStart.Start(String[] args) in E:\Code\ss14\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in E:\Code\ss14\space-station-14\Content.Server\Program.cs:line 9
```

**Comment by Zumorica** [comment]
Can't replicate on latest master

**Comment by Zumorica** [comment]
Nevermind, reproduced.

**Comment by F77F** [comment]
why is this exclusive to floortiles 🤔

**Comment by SweptWasTaken** [comment]
> 
> 
> why is this exclusive to floortiles 🤔

Because floor tiles are the only stack item you can place

**Comment by F77F** [comment]
> > why is this exclusive to floortiles 🤔
> 
> Because floor tiles are the only stack item you can place

are coils of cable different? they are a tile technically right.

**Comment by DrSmugleaf** [comment]
> are coils of cable different? they are a tile technically right.

Placed cable coils are an entity, tiles however are not since they are special cased.

**Comment by F77F** [comment]
```cs
void IAfterInteract.AfterInteract(AfterInteractEventArgs eventArgs)
{

            Owner.Delete();
}
```

simply changing the method body to this in FloorTileItemComponent.cs still causes the server to crash.

**Comment by Nickname863** [comment]
I think i found the reason why Food doesn't crash the Server but Building does.
It has nothing to do with an item having a Stacksize as far as i can see.
I compared the the "FloorTileItemComponent" with the "FoodComponent".
If a user eats this code will be called if it is from the Inventory:
![image](https://user-images.githubusercontent.com/33596703/89345872-7391b480-d6a8-11ea-8e34-d01e4ce87d05.png)
The Content of the Hand is always replaced. If the food of the User is doesn't have any remains, then nothing is placed in the Hand.
In case of the Tile placement there is nothing placed in the Hand, the Item is simply deleted: 
![image](https://user-images.githubusercontent.com/33596703/89346111-cff4d400-d6a8-11ea-9019-4e2a9bd2016c.png)
So the true error is that Robust.Shared.GameObjects.EntityManager.RemoveFromEntityTrees is not removing Entitys from Containers. If that is intentional, another way to fix this would be to just place nothing into the hand of the Mob/User. This of course would have the downside of having to remember to do this for every Consumable Item, or the Server crashes.

So what should be done to fix this Bug?
