### ISSUE TITLE
Chambered guns cause debug asserts

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#15092]
Due to the predicted container stuff it causes exceptions on latest engine.

**Comment by deltanedas** [comment]
```
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 36
   at Robust.Shared.Containers.ContainerSlot.InternalInsert(EntityUid toInsert, IEntityManager entMan) in RobustToolbox/Robust.Shared/Containers/ContainerSlot.cs:line 88
   at Robust.Shared.Containers.BaseContainer.Insert(EntityUid toinsert, IEntityManager entMan, TransformComponent transform, TransformComponent ownerTransform, MetaDataComponent meta, PhysicsComponent physics, Boolean force) in RobustToolbox/Robust.Shared/Containers/BaseContainer.cs:line 144
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.TryInsertChamber(EntityUid uid, EntityUid ammo) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 71
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnChamberMagazineTakeAmmo(EntityUid uid, ChamberMagazineAmmoProviderComponent component, TakeAmmoEvent args) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 103
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 255
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 393
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args, Boolean dispatchByReference) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 554
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 222
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 182
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 128
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.AttemptShoot(EntityUid user, EntityUid gunUid, GunComponent gun) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs:line 294
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnShootRequest(RequestShootEvent msg, EntitySessionEventArgs args) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs:line 129
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 169
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 309
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T toRaise) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 263
   at Robust.Client.GameObjects.ClientEntityManager.RaisePredictiveEvent[T](T msg) in RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 107
   at Content.Client.Weapons.Ranged.Systems.GunSystem.Update(Single frameTime) in Content.Client/Weapons/Ranged/Systems/GunSystem.cs:line 165
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 303
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 136
   at Robust.Client.GameObjects.ClientEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 138
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 371
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in RobustToolbox/Robust.Client/GameController/GameController.cs:line 538
   at Robust.Client.GameController.<StartupContinue>b__51_0(Object sender, FrameEventArgs args) in RobustToolbox/Robust.Client/GameController/GameController.cs:line 203
   at Robust.Shared.Timing.GameLoop.Run() in RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 218
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 133
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 118
   at Robust.Client.GameController.<>c__DisplayClass92_0.<Run>b__0() in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 85
```
