### ISSUE TITLE
SQLite is Broken

### ISSUE THREAD

**Issue by Biglulux** [space-wizards/space-station-14#15141]
PR #15076 broke SQLite databases for servers, making all servers using SQLite instead of PostgreSQL unable to start. This is an urgent issue for anyone hosting a community server using SQLite, as the server is down until this is fixed.

Exception from watchdog when trying to start a server using SQLite:

[DEBG] db.manager: Using SQLite DB "D:\SS14Server\Watchdog\instances\real_station\data\preferences.db"
[DEBG] res.mod: RESOLVING DEFAULT: SQLitePCLRaw.core, Version=2.1.4.1835, Culture=neutral, PublicKeyToken=1488e028ca7ab535
[DEBG] res: ResolvingAssembly SQLitePCLRaw.core, Version=2.1.4.1835, Culture=neutral, PublicKeyToken=1488e028ca7ab535
[FATL] unhandled: System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.core, Version=2.1.4.1835, Culture=neutral, PublicKeyToken=1488e028ca7ab535'. The system cannot find the file specified.
File name: 'SQLitePCLRaw.core, Version=2.1.4.1835, Culture=neutral, PublicKeyToken=1488e028ca7ab535'
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Content.Server.Database.ServerDbManager.CreateSqliteOptions() in /home/runner/work/space-station-14/space-station-14/Content.Server/Database/ServerDbManager.cs:line 701
   at Content.Server.Database.ServerDbManager.Init() in /home/runner/work/space-station-14/space-station-14/Content.Server/Database/ServerDbManager.cs:line 276
   at Content.Server.Entry.EntryPoint.Init() in /home/runner/work/space-station-14/space-station-14/Content.Server/Entry/EntryPoint.cs:line 103
   at Robust.Shared.ContentPack.BaseModLoader.BroadcastRunLevel(ModRunLevel level) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/ContentPack/BaseModLoader.cs:line 79
   at Robust.Server.BaseServer.Start(ServerOptions options, Func`1 logHandlerFactory) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 342
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 68
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.Program.Main(String[] args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 25
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.core, Version=2.1.4.1835, Culture=neutral, PublicKeyToken=1488e028ca7ab535'. The system cannot find the file specified.
File name: 'SQLitePCLRaw.core, Version=2.1.4.1835, Culture=neutral, PublicKeyToken=1488e028ca7ab535'
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Content.Server.Database.ServerDbManager.CreateSqliteOptions() in /home/runner/work/space-station-14/space-station-14/Content.Server/Database/ServerDbManager.cs:line 701
   at Content.Server.Database.ServerDbManager.Init() in /home/runner/work/space-station-14/space-station-14/Content.Server/Database/ServerDbManager.cs:line 276
   at Content.Server.Entry.EntryPoint.Init() in /home/runner/work/space-station-14/space-station-14/Content.Server/Entry/EntryPoint.cs:line 103
   at Robust.Shared.ContentPack.BaseModLoader.BroadcastRunLevel(ModRunLevel level) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/ContentPack/BaseModLoader.cs:line 79
   at Robust.Server.BaseServer.Start(ServerOptions options, Func1 logHandlerFactory) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 342
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 68
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.Program.Main(String[] args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 25
[20:45:44 INF SS14.Watchdog.Components.ServerManagement.ServerInstance] real_station shut down with exit code -532462766[20:45:44 WRN SS14.Watchdog.Components.ServerManagement.ServerInstance] real_station shut down before sending ping on attempt 3
[20:45:44 WRN SS14.Watchdog.Components.ServerManagement.ServerInstance] real_station is failing to start, giving up until update.

**Comment by moonheart08** [comment]
If you're running an SS14 server it's highly recommended to know how to revert changes i.e. roll back to earlier builds.

**Comment by Biglulux** [comment]
> If you're running an SS14 server it's highly recommended to know how to revert changes i.e. roll back to earlier builds.

The documentation at https://docs.spacestation14.io/en/getting-started/hosting is pretty garbage, so shrug. There should probably be more comprehensive unit testing so broken PRs aren't merged.

**Comment by Menshin** [comment]
Fixed in Robust 0.96.3, can be closed.

**Comment by PJB3005** [comment]
Yep, #15177
