### ISSUE TITLE
The same fail of actions on forks, but not on the upstream

### ISSUE THREAD

**Issue by KIBORG04** [space-wizards/space-station-14#15142]
## Description

The same test fails on all forks, giving the same error, however that test is passed on upstream. 

Fork without changes
[Morb0/space-station-14/actions/runs/4595976307/jobs/8116873225](https://github.com/Morb0/space-station-14/actions/runs/4595976307/jobs/8116873225)

Other forks
[StationWare/stationware/actions/runs/4528709249/jobs/7975739169](https://github.com/StationWare/stationware/actions/runs/4528709249/jobs/7975739169)
[Nyanotrasen/Nyanotrasen/actions/runs/4602294532/jobs/8131097816](https://github.com/Nyanotrasen/Nyanotrasen/actions/runs/4602294532/jobs/8131097816)
[space-syndicate/space-station-14/actions/runs/4566594002/jobs/8059314606](https://github.com/space-syndicate/space-station-14/actions/runs/4566594002/jobs/8059314606)
https://github.com/ThetaStation/ThetaStation/actions/runs/4589276331/jobs/8104053065

**Reproduction**

Restart actions??? Locally everything is fine

**Screenshots**

**Additional context**

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed Test [1 s]
  Error Message:
   System.InvalidOperationException : Called Delete on an entity already being deleted. Entity: kidneys (163585, OrganAnimalKidneys)
  Stack Trace:
     at Robust.Shared.GameObjects.EntityManager.DeleteEntity(EntityUid e) in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 309
   at Robust.Shared.GameObjects.EntityManager.FlushEntities() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 500
   at Robust.Shared.GameObjects.EntityManager.Cleanup() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line [12](https://github.com/Morb0/space-station-14/actions/runs/4595976307/jobs/8116873225#step:10:13)1
   at Robust.Server.BaseServer.Cleanup() in D:\a\space-station-[14](https://github.com/Morb0/space-station-14/actions/runs/4595976307/jobs/8116873225#step:10:15)\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 634
   at Robust.Server.BaseServer.FinishMainLoop() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 529
   at Robust.UnitTesting.RobustIntegrationTest.ServerIntegrationInstance._serverMain() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 584
```

**Comment by KIBORG04** [comment]
Somewhere after 15466 the error does not occur
