### ISSUE TITLE
windows error when running "dotnet run --project Content.Client"

### ISSUE THREAD

**Issue by jkensik** [space-wizards/space-station-14#1555]
I only got this error on my windows machine, it works fine on ubuntu. 

The error was

Unhandled exception. Robust.Shared.IoC.Exceptions.ImplementationConstructorException: Robust.Client.Graphics.FontManager threw an exception inside its constructor.
 ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
   at SharpFont.Library..ctor()
   at Robust.Client.Graphics.FontManager..ctor() in C:\Users\John\Documents\csharp\space-station-14\RobustToolbox\Robust.Client\Graphics\FontManager.cs:line 32
   --- End of inner exception stack trace ---
   at Robust.Shared.IoC.DependencyCollection.BuildGraph() in C:\Users\John\Documents\csharp\space-station-14\RobustToolbox\Robust.Shared\IoC\DependencyCollection.cs:line 165
   at Robust.Shared.IoC.IoCManager.BuildGraph() in C:\Users\John\Documents\csharp\space-station-14\RobustToolbox\Robust.Shared\IoC\IoCManager.cs:line 154
   at Robust.Client.GameController.InitIoC(DisplayMode mode) in C:\Users\John\Documents\csharp\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.IoC.cs:line 74
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in C:\Users\John\Documents\csharp\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 45
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in C:\Users\John\Documents\csharp\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
   at Robust.Client.ContentStart.Start(String[] args) in C:\Users\John\Documents\csharp\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in C:\Users\John\Documents\csharp\space-station-14\Content.Client\Program.cs:line 9

If anyone has any ideas about what it could be let me know.

**Comment by SweptWasTaken** [comment]
Replicated and can't get this issue. Assuming it's fixed.
