### ISSUE TITLE
Follower crashes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#15889]
Happens on client:

```
[ERRO] root: Predicting the queued deletion of a networked entity: Chad Mack (172082, MobObserver). Trace:    at System.Environment.get_StackTrace()
   at Robust.Client.GameObjects.ClientEntityManager.QueueDeleteEntity(EntityUid uid) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 76
   at Content.Shared.Follower.FollowerSystem.StopFollowingEntity(EntityUid uid, EntityUid target, FollowedComponent followed) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Follower/FollowerSystem.cs:line 113
   at Content.Shared.Follower.FollowerSystem.StopAllFollowers(EntityUid uid, FollowedComponent followed) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Follower/FollowerSystem.cs:line 138
   at Content.Shared.Follower.FollowerSystem.OnFollowedTerminating(EntityUid uid, FollowedComponent component, EntityTerminatingEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Follower/FollowerSystem.cs:line 57
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args, Boolean dispatchByReference) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 554
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntityManager.RecursiveFlagEntityTermination(EntityUid uid, MetaDataComponent metadata, EntityQuery`1 metaQuery, EntityQuery`1 xformQuery) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 351
   at Robust.Shared.GameObjects.EntityManager.DeleteEntity(EntityUid e) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 333
   at Robust.Shared.GameObjects.EntityManager.FlushEntities() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 495
   at Robust.Client.GameObjects.ClientEntityManager.FlushEntities() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 41
   at Robust.Shared.GameObjects.EntityManager.Shutdown() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 110
   at Robust.Client.BaseClient.GameStoppedReset() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/BaseClient.cs:line 258
   at Robust.Client.BaseClient.OnNetDisconnect(Object sender, NetDisconnectedArgs args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/BaseClient.cs:line 241
   at Robust.Shared.Network.NetManager.OnDisconnected(INetChannel channel, String reason) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 1105
   at Robust.Shared.Network.NetManager.HandleDisconnect(NetPeerData peer, NetConnection connection, String reason) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 778
   at Robust.Shared.Network.NetManager.HandleStatusChanged(NetPeerData peer, NetIncomingMessage msg) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 723
   at Robust.Shared.Network.NetManager.ProcessPackets() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 497
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 502
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 171
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 133
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 118
   at Robust.Client.GameController.<>c__DisplayClass92_0.<Run>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 85
[DEBG] map: Stopping...
```

**Comment by Menshin** [comment]
Triggered when disconnecting while following an entity.
Got this warning just before the error :

![image](https://user-images.githubusercontent.com/7117411/235309964-9e5a1d5f-22eb-408f-83f8-388c2a73e9f4.png)
