### ISSUE TITLE
Vapor exceptions

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16506]
![image](https://github.com/space-wizards/space-station-14/assets/31366439/418a5869-fdbb-4eb5-a759-b9d6c3f8fa01)

https://github.com/space-wizards/space-station-14/pull/16505 trying to get better logs though doesn't show the exact reaction atm.

**Comment by Matz05** [comment]
Possibly related debug-assert crash from something to do with either inhaling smoke, inhaling smoke and vomiting, or inhaling multiple sources of smoke and/or foam, while playing in the default dev level with exotic chemistry grenades.
`[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 36
   at Content.Shared.Chemistry.Components.Solution.ValidateSolution() in /home/matias/Desktop/SS14 code/space-station-14/Content.Shared/Chemistry/Components/Solution.cs:line 197
   at Content.Shared.Chemistry.Components.Solution.AddSolution(Solution otherSolution, IPrototypeManager protoMan) in /home/matias/Desktop/SS14 code/space-station-14/Content.Shared/Chemistry/Components/Solution.cs:line 623
   at Content.Server.Chemistry.EntitySystems.SolutionContainerSystem.TryAddSolution(EntityUid targetUid, Solution targetSolution, Solution addedSolution) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Chemistry/EntitySystems/SolutionContainerSystem.cs:line 309
   at Content.Server.Body.Systems.BloodstreamSystem.TryAddToChemicals(EntityUid uid, Solution solution, BloodstreamComponent component) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Body/Systems/BloodstreamSystem.cs:line 264
   at Content.Server.Fluids.EntitySystems.SmokeSystem.ReactWithEntity(EntityUid entity, Solution solution, Double solutionFraction) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Fluids/EntitySystems/SmokeSystem.cs:line 283
   at Content.Server.Fluids.EntitySystems.SmokeSystem.SmokeReact(EntityUid uid, Single frameTime, SmokeComponent component, TransformComponent xform) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Fluids/EntitySystems/SmokeSystem.cs:line 244
   at Content.Server.Fluids.EntitySystems.SmokeSystem.Update(Single frameTime) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Fluids/EntitySystems/SmokeSystem.cs:line 187
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 303
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 258
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 149
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 703
   at Robust.Server.BaseServer.<SetupMainLoop>b__64_1(Object sender, FrameEventArgs args) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 524
   at Robust.Shared.Timing.GameLoop.Run() in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 213
   at Robust.Server.BaseServer.MainLoop() in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 551
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 36
   at Content.Shared.Chemistry.Components.Solution.ValidateSolution() in /home/matias/Desktop/SS14 code/space-station-14/Content.Shared/Chemistry/Components/Solution.cs:line 197
   at Content.Shared.Chemistry.Components.Solution.AddSolution(Solution otherSolution, IPrototypeManager protoMan) in /home/matias/Desktop/SS14 code/space-station-14/Content.Shared/Chemistry/Components/Solution.cs:line 623
   at Content.Server.Chemistry.EntitySystems.SolutionContainerSystem.TryAddSolution(EntityUid targetUid, Solution targetSolution, Solution addedSolution) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Chemistry/EntitySystems/SolutionContainerSystem.cs:line 309
   at Content.Server.Body.Systems.BloodstreamSystem.TryAddToChemicals(EntityUid uid, Solution solution, BloodstreamComponent component) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Body/Systems/BloodstreamSystem.cs:line 264
   at Content.Server.Fluids.EntitySystems.SmokeSystem.ReactWithEntity(EntityUid entity, Solution solution, Double solutionFraction) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Fluids/EntitySystems/SmokeSystem.cs:line 283
   at Content.Server.Fluids.EntitySystems.SmokeSystem.SmokeReact(EntityUid uid, Single frameTime, SmokeComponent component, TransformComponent xform) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Fluids/EntitySystems/SmokeSystem.cs:line 244
   at Content.Server.Fluids.EntitySystems.SmokeSystem.Update(Single frameTime) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Fluids/EntitySystems/SmokeSystem.cs:line 187
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 303
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 258
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 149
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 703
   at Robust.Server.BaseServer.<SetupMainLoop>b__64_1(Object sender, FrameEventArgs args) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 524
   at Robust.Shared.Timing.GameLoop.Run() in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 213
   at Robust.Server.BaseServer.MainLoop() in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 551
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in /home/matias/Desktop/SS14 code/space-station-14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/matias/Desktop/SS14 code/space-station-14/Content.Server/Program.cs:line 9
`
