### ISSUE TITLE
Disposal Bin throws exception when disposing while not near the player

### ISSUE THREAD

**Issue by juliangiebel** [space-wizards/space-station-14#1659]
To replicate:
 1. Press engage
 2. Put stuff into the bin
 3. Press engage again
 4. Run away

<details> 
  <summary>This throws a <code>ComponentStateApplyException</code></summary>
<p>Robust.Client.GameObjects.ComponentStateApplyException&#8291;<br>
<blockquote>
 HResult=0x80131500&#8291;<br>
 Nachricht = Failed to apply comp state: entity=grey jumpsuit (3567, UniformColorGrey), comp=Transform&#8291;<br>
 Quelle = Robust.Client&#8291;<br>
 Stapel&uuml;berwachung:&#8291;<br>
 at Robust.Client.GameObjects.ClientEntityManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityState curState, EntityState nextState) in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityManager.cs:line 297&#8291;<br>
 at Robust.Client.GameObjects.ClientEntityManager.ApplyEntityStates(EntityState[] curEntStates, IEnumerable&#96;1 deletions, EntityState[] nextEntStates) in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityManager.cs:line 98&#8291;<br>
 at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 355&#8291;<br>
 at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 187&#8291;<br>
 at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 284&#8291;<br>
 at Robust.Client.GameController.<MainLoop>b__66_0(Object sender, FrameEventArgs args) in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 84&#8291;<br>
 at Robust.Shared.Timing.GameLoop.Run() in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 200&#8291;<br>
 at Robust.Client.GameController.MainLoop(DisplayMode mode) in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113&#8291;<br>
 at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 59&#8291;<br>
 at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35&#8291;<br>
 at Robust.Client.ContentStart.Start(String[] args) in C:\Users\Julian Giebel\source\repos\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10&#8291;<br>
 at Content.Client.Program.Main(String[] args) in C:\Users\Julian Giebel\source\repos\space-station-14\Content.Client\Program.cs:line 9&#8291;<br>
&#8291;<br>
 Diese Ausnahme wurde urspr&uuml;nglich von dieser Aufrufliste ausgel&ouml;st:&#8291;<br>
 [Externer Code]&#8291;<br>
 Robust.Shared.GameObjects.EntityManager.GetEntity(Robust.Shared.GameObjects.EntityUid) in EntityManager.cs&#8291;<br>
 Robust.Shared.GameObjects.Components.Transform.TransformComponent.HandleComponentState(Robust.Shared.GameObjects.ComponentState, Robust.Shared.GameObjects.ComponentState) in TransformComponent.cs&#8291;<br>
 Robust.Client.GameObjects.ClientEntityManager.HandleEntityState(Robust.Shared.Interfaces.GameObjects.IComponentManager, Robust.Shared.Interfaces.GameObjects.IEntity, Robust.Shared.GameObjects.EntityState, Robust.Shared.GameObjects.EntityState) in ClientEntityManager.cs&#8291;<br>
&#8291;<br>
Innere Ausnahme 1:&#8291;<br>
KeyNotFoundException: The given key '3594' was not present in the dictionary.</p>
</blockquote>
</details>

**Comment by SweptWasTaken** [comment]
Couldn't replicate, closing.

**Comment by metalgearsloth** [comment]
It would probably still be happening because of PVS NaNs but it will be fixed whenever refactor merged.

**Comment by SweptWasTaken** [comment]
Still an issue. Will close when refactor merged.

![unknown](https://user-images.githubusercontent.com/49448379/109092793-1fffba80-770f-11eb-9bde-fd242f7283d8.png)

**Comment by metalgearsloth** [comment]
This still happens:

```
Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=Assistant PDA (5497, AssistantPDA), comp=ContainerContainer
 ---> System.Collections.Generic.KeyNotFoundException: The given key '5498' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 152
   at Robust.Shared.Containers.ContainerManagerComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Containers\ContainerManagerComponent.cs:line 125
   at Robust.Client.GameObjects.ClientEntityManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityState curState, EntityState nextState) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityManager.cs:line 269
```

I was standing on an airblocked tile and when I died it happened.
