### ISSUE TITLE
Lots of exceptions related to keys not being found

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#1691]
![image](https://user-images.githubusercontent.com/5714543/90322695-f7576680-df1c-11ea-904e-880689663144.png)
![image](https://user-images.githubusercontent.com/5714543/90322705-09390980-df1d-11ea-89c3-c3178c308533.png)
![image](https://user-images.githubusercontent.com/5714543/90322706-0c33fa00-df1d-11ea-97af-544fa4cd4e83.png)

**Comment by DrSmugleaf** [comment]
```cs
> [ERRO] runtime: Caught exception in "Component state apply"
> Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=magazine (.30 rifle) (7568, MagazineLRifle), comp=Transform
>  ---> System.Collections.Generic.KeyNotFoundException: The given key '7615' was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 122
>    at Robust.Shared.GameObjects.Components.Transform.TransformComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs:line 721
>    at Robust.Client.GameObjects.ClientEntityManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityState curState, EntityState nextState) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 288
>    --- End of inner exception stack trace ---
```

**Comment by SweptWasTaken** [comment]
Not present anymore. Closing.
