### ISSUE TITLE
[ERRO] net: 78.46.69.138:1212: exception in message handler for MsgPreferencesAndSettings: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#1738]
```
[WARN] net: 78.46.69.138:1212: Failed to deserialize MsgState packet: Index was outside the bounds of the array.
[ERRO] net: 78.46.69.138:1212: exception in message handler for MsgPreferencesAndSettings:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Content.Client.UserInterface.LobbyCharacterPreviewPanel.UpdateUI() in /var/lib/jenkins/workspace/SS14 Content/Content.Client/UserInterface/LobbyCharacterPreviewPanel.cs:line 118
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 830
```

Not sure if these two messages are related, I'm pretty sure they are tho

**Comment by exp111** [comment]
I don't think so. I got the second one often (without the first one). It happens when you get into the lobby

**Comment by Visne** [comment]
You're right, I also got the first one often
I'll make a new issue if it doesn't exist yet

**Comment by PJB3005** [comment]
This is due to a mismatched client/server version.

**Comment by exp111** [comment]
The MsgPreference too? The first one happens because of the mismatch. But the second one was also after updating
