### ISSUE TITLE
Audio related exceptions

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1745]
```
[ERRO] entsys: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AudioSource'.
   at Robust.Client.Graphics.Clyde.Clyde.AudioSource._checkDisposed() in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 546
   at Robust.Client.Graphics.Clyde.Clyde.AudioSource.get_IsPlaying() in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 389
   at Robust.Client.GameObjects.EntitySystems.AudioSystem.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/GameObjects/EntitySystems/AudioSystem.cs:line 99
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 245
[ERRO] entsys: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AudioSource'.
   at Robust.Client.Graphics.Clyde.Clyde.AudioSource._checkDisposed() in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 546
   at Robust.Client.Graphics.Clyde.Clyde.AudioSource.get_IsPlaying() in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 389
   at Robust.Client.GameObjects.EntitySystems.AudioSystem.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/GameObjects/EntitySystems/AudioSystem.cs:line 99
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 245
[ERRO] entsys: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AudioSource'.
   at Robust.Client.Graphics.Clyde.Clyde.AudioSource._checkDisposed() in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 546
   at Robust.Client.Graphics.Clyde.Clyde.AudioSource.get_IsPlaying() in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs:line 389
   at Robust.Client.GameObjects.EntitySystems.AudioSystem.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/GameObjects/EntitySystems/AudioSystem.cs:line 99
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 245
```

**Comment by Zumorica** [comment]
I'm pretty sure PJB fixed this recently.
