### ISSUE TITLE
Server crashes in some cases at roundstart

### ISSUE THREAD

**Issue by Valtosin** [space-wizards/space-station-14#17542]
caught in grafana before server crashes
```cs
Caught exception in GameTicker
System.ArgumentException: An item with the same key has already been added. Key: 20586
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Content.Server.Administration.Logs.AdminLogManager.CacheNewRound() in /home/runner/work/ss14-new/ss14-new/Content.Server/Administration/Logs/AdminLogManager.Cache.cs:line 44
   at Content.Server.Administration.Logs.AdminLogManager.RoundStarting(Int32 id) in /home/runner/work/ss14-new/ss14-new/Content.Server/Administration/Logs/AdminLogManager.cs:line 223
   at Content.Server.Administration.Logs.AdminLogSystem.<Initialize>b__1_0(RoundStartingEvent ev) in /home/runner/work/ss14-new/ss14-new/Content.Server/Administration/Logs/AdminLogSystem.cs:line 18
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in /home/runner/work/ss14-new/ss14-new/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 169
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/ss14-new/ss14-new/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 321
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T toRaise) in /home/runner/work/ss14-new/ss14-new/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 263
   at Content.Server.GameTicking.GameTicker.StartRound(Boolean force) in /home/runner/work/ss14-new/ss14-new/Content.Server/GameTicking/GameTicker.RoundFlow.cs:line 202
 Catcher=GameTicker Sawmill=runtime
 ```
### context
7 servers working simultaneously with one db

#### more context
![chrome_2023-06-22_05-09-43](https://github.com/space-wizards/space-station-14/assets/10297716/843327d7-7239-4e7e-8e97-2a1aadadfb35)

**Comment by Valtosin** [comment]
so, it seems it's the case when map can't load, but it keep trying to add id to the dict, when it's already in it. I'll check what is wrong with maps anyway

**Comment by hobolyra** [comment]
Same issue. Load a map for mapping, but if I try to save the same map, I get "An item with the same key has already been added" error as well. Map works fine otherwise, without any changes map never threw this error beforehand. Now it won't save at all.

**Comment by metalgearsloth** [comment]
> Same issue. Load a map for mapping, but if I try to save the same map, I get "An item with the same key has already been added" error as well. Map works fine otherwise, without any changes map never threw this error beforehand. Now it won't save at all.
> 
> Error only happened after rebuilding dev environment, and a few other maps now also can't be edited that once worked.

Your issue sounds completely different and needs more info.
