### ISSUE TITLE
macos m1 cant hear midi instruments

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#18187]
## Description

```
[ERRO] midi: Failed to initialize fluidsynth due to exception, disabling MIDI support:
System.DllNotFoundException: Unable to load shared library 'fluidsynth' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/fluidsynth.dylib, 0x0001): tried: '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/fluidsynth.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/fluidsynth.dylib' (no such file), '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/fluidsynth.dylib' (no such file)
dlopen(/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/fluidsynth.dylib, 0x0001): tried: '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/fluidsynth.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/fluidsynth.dylib' (no such file), '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/fluidsynth.dylib' (no such file)
dlopen(fluidsynth.dylib, 0x0001): tried: 'fluidsynth.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSfluidsynth.dylib' (no such file), '/usr/lib/fluidsynth.dylib' (no such file, not in dyld cache), 'fluidsynth.dylib' (no such file), '/usr/local/lib/fluidsynth.dylib' (no such file), '/usr/lib/fluidsynth.dylib' (no such file, not in dyld cache)
dlopen(/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/libfluidsynth.dylib, 0x0001): tried: '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/libfluidsynth.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/libfluidsynth.dylib' (no such file), '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/libfluidsynth.dylib' (no such file)
dlopen(/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/libfluidsynth.dylib, 0x0001): tried: '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/libfluidsynth.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/libfluidsynth.dylib' (no such file), '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/libfluidsynth.dylib' (no such file)
dlopen(libfluidsynth.dylib, 0x0001): tried: 'libfluidsynth.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibfluidsynth.dylib' (no such file), '/usr/lib/libfluidsynth.dylib' (no such file, not in dyld cache), 'libfluidsynth.dylib' (no such file), '/usr/local/lib/libfluidsynth.dylib' (no such file), '/usr/lib/libfluidsynth.dylib' (no such file, not in dyld cache)
dlopen(/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/fluidsynth, 0x0001): tried: '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/fluidsynth' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/fluidsynth' (no such file), '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/fluidsynth' (no such file)
dlopen(/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/fluidsynth, 0x0001): tried: '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/fluidsynth' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/fluidsynth' (no such file), '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/fluidsynth' (no such file)
dlopen(fluidsynth, 0x0001): tried: 'fluidsynth' (no such file), '/System/Volumes/Preboot/Cryptexes/OSfluidsynth' (no such file), '/usr/lib/fluidsynth' (no such file, not in dyld cache), 'fluidsynth' (no such file), '/usr/local/lib/fluidsynth' (no such file), '/usr/lib/fluidsynth' (no such file, not in dyld cache)
dlopen(/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/libfluidsynth, 0x0001): tried: '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/libfluidsynth' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/libfluidsynth' (no such file), '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/bin/loader/Space Station 14.app/Contents/Resources/bin/libfluidsynth' (no such file)
dlopen(/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/libfluidsynth, 0x0001): tried: '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/libfluidsynth' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/libfluidsynth' (no such file), '/Users/vasilis/Library/Application Support/Steam/steamapps/common/Space Station 14 Playtest/Space Station 14 Launcher.app/Contents/Resources/dotnet/shared/Microsoft.NETCore.App/7.0.3/libfluidsynth' (no such file)
dlopen(libfluidsynth, 0x0001): tried: 'libfluidsynth' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibfluidsynth' (no such file), '/usr/lib/libfluidsynth' (no such file, not in dyld cache), 'libfluidsynth' (no such file), '/usr/local/lib/libfluidsynth' (no such file), '/usr/lib/libfluidsynth' (no such file, not in dyld cache)

   at NFluidsynth.Native.LibFluidsynth.fluid_set_log_function(Int32 severity, LoggerDelegate func, IntPtr data)
   at NFluidsynth.Logger.SetLoggerMethod(LoggerDelegate method)
   at Robust.Client.Audio.Midi.MidiManager.InitializeFluidsynth() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Audio/Midi/MidiManager.cs:line 186
```

**Reproduction**

1. Play music
2. get error
3. no music

**Screenshots**

**Additional context**

**Comment by moonheart08** [comment]
You need to install fluidsynth for playback to work.

**Comment by VasilisThePikachu** [comment]
I thought that was for linux not macos?

**Comment by moonheart08** [comment]
> I thought that was for linux not macos?

It applies to all non-windows platforms.

**Comment by VasilisThePikachu** [comment]
well i used `brew install Fluidsynth` and i still cant hear it, i now noticed the popup on instruments too
