### ISSUE TITLE
NPC/Combat is passing invalid entity uids

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#18459]
I.e., its passing `EntityUid.Invalid` to `TryGetNearest()`?

```
Can't resolve "Robust.Shared.GameObjects.TransformComponent" on entity 0!
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.TryGetNearest(EntityUid uidA, EntityUid uidB, Vector2& pointA, Vector2& pointB, Single& distance, TransformComponent xformA, TransformComponent xformB, FixturesComponent managerA, FixturesComponent managerB, PhysicsComponent bodyA, PhysicsComponent bodyB) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Queries.cs:line 526
   at Content.Server.NPC.Systems.NPCCombatSystem.OnMeleeSteering(EntityUid uid, NPCMeleeCombatComponent component, NPCSteeringEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Server/NPC/Systems/NPCCombatSystem.Melee.cs:line 37
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Content.Server.NPC.Systems.NPCSteeringSystem.Steer(EntityUid uid, NPCSteeringComponent steering, InputMoverComponent mover, TransformComponent xform, Single frameTime, TimeSpan curTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/NPC/Systems/NPCSteeringSystem.cs:line 345
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at Content.Server.NPC.Systems.NPCSteeringSystem.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/NPC/Systems/NPCSteeringSystem.cs:line 251
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 303
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 153
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 686
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 228
   at Robust.Server.BaseServer.MainLoop() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 557
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.Program.Main(String[] args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 25
```

**Comment by osjarw** [comment]
I believe this was fixed by #30005.
