### ISSUE TITLE
Subdermal implant exception

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#18463]
From grafana. Some subdermal implant code just looks dubious.
- Why is ImplantedEntity not null when a user is picking up an item?
- Why is it not checking the id of the conter is is being inserted into?

```
Caught exception in DispatchEntityNetworkMessage(SystemMessage)
System.ArgumentException: Entity 1713055 is not valid. (Parameter 'uid')
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid, T component, Boolean overwrite) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 257
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 198
   at Content.Shared.Implants.SharedSubdermalImplantSystem.OnInsert(EntityUid uid, SubdermalImplantComponent component, EntGotInsertedIntoContainerMessage args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Implants/SharedSubdermalImplantSystem.cs:line 57
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 179
   at Robust.Shared.Containers.BaseContainer.Insert(EntityUid toinsert, IEntityManager entMan, TransformComponent transform, TransformComponent ownerTransform, MetaDataComponent meta, PhysicsComponent physics, Boolean force) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Containers/BaseContainer.cs:line 81
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.DoPickup(EntityUid uid, Hand hand, EntityUid entity, HandsComponent hands) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 215
   at Content.Shared.Item.SharedItemSystem.OnHandInteract(EntityUid uid, ItemComponent component, InteractHandEvent args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Item/SharedItemSystem.cs:line 75
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 50
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 179
   at Content.Shared.Interaction.SharedInteractionSystem.InteractHand(EntityUid user, EntityUid target) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 383
   at Content.Shared.Interaction.SharedInteractionSystem.UserInteraction(EntityUid user, EntityCoordinates coordinates, Nullable`1 target, Boolean altInteract, Boolean checkCanInteract, Boolean checkAccess, Boolean checkCanUse) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 372
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(ICommonSession session, InputCmdMessage message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 121
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/InputSystem.cs:line 66
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 47
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 318
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 257
 Catcher=DispatchEntityNetworkMessage(SystemMessage) Sawmill=runtime
```

**Comment by ElectroJr** [comment]
Ah there two other errors that might be related:

```
Caught exception in DispatchEntityNetworkMessage(SystemMessage)
System.Collections.Generic.KeyNotFoundException: Entity 1713055 does not have a component of type Robust.Shared.GameObjects.MetaDataComponent
   at Content.Shared.Implants.SharedSubdermalImplantSystem.OnRemove(EntityUid uid, SubdermalImplantComponent component, EntGotRemovedFromContainerMessage args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Implants/SharedSubdermalImplantSystem.cs:line 71
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 179
   at Robust.Shared.Containers.BaseContainer.Remove(EntityUid toRemove, IEntityManager entMan, TransformComponent xform, MetaDataComponent meta, Boolean reparent, Boolean force, Nullable`1 destination, Nullable`1 localRotation) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Containers/BaseContainer.cs:line 327
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.DropPressed(ICommonSession session, EntityCoordinates coords, EntityUid uid) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Interactions.cs:line 95
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(ICommonSession session, InputCmdMessage message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 121
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/InputSystem.cs:line 66
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 47
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 318
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 257
 Catcher=DispatchEntityNetworkMessage(SystemMessage) Sawmill=runtime
```

and

```
Caught exception in entsys
System.Collections.Generic.KeyNotFoundException: Entity 1713055 does not have a component of type Robust.Shared.GameObjects.MetaDataComponent
   at Content.Shared.Implants.SharedSubdermalImplantSystem.OnRemove(EntityUid uid, SubdermalImplantComponent component, EntGotRemovedFromContainerMessage args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Implants/SharedSubdermalImplantSystem.cs:line 71
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 179
   at Robust.Shared.Containers.BaseContainer.Remove(EntityUid toRemove, IEntityManager entMan, TransformComponent xform, MetaDataComponent meta, Boolean reparent, Boolean force, Nullable`1 destination, Nullable`1 localRotation) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Containers/BaseContainer.cs:line 327
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.DoDrop(EntityUid uid, Hand hand, Boolean doDropInteraction, HandsComponent handsComp) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Drop.cs:line 175
   at Content.Server.Standing.StandingStateSystem.FallOver(EntityUid uid, StandingStateComponent component, DropHandItemsEvent args) in /home/runner/work/space-station-14/space-station-14/Content.Server/Standing/StandingStateSystem.cs:line 19
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 179
   at Content.Shared.Standing.StandingStateSystem.Down(EntityUid uid, Boolean playSound, Boolean dropHeldItems, StandingStateComponent standingState, AppearanceComponent appearance, HandsComponent hands) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Standing/StandingStateSystem.cs:line 55
   at Content.Shared.Stunnable.SharedStunSystem.OnKnockInit(EntityUid uid, KnockedDownComponent component, ComponentInit args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Stunnable/SharedStunSystem.cs:line 148
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args, Boolean dispatchByReference) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, CompIdx type, TEvent args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 155
   at Robust.Shared.GameObjects.Component.LifeInitialize(IEntityManager entManager, CompIdx type) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Component.cs:line 77
   at Robust.Shared.GameObjects.EntityManager.AddComponentInternal[T](EntityUid uid, T component, Boolean overwrite, Boolean skipInit) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 275
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid, T component, Boolean overwrite) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 257
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 198
   at Content.Shared.StatusEffect.StatusEffectsSystem.TryAddStatusEffect[T](EntityUid uid, String key, TimeSpan time, Boolean refresh, StatusEffectsComponent status) in /home/runner/work/space-station-14/space-station-14/Content.Shared/StatusEffect/StatusEffectsSystem.cs:line 120
   at Content.Shared.Stunnable.SharedStunSystem.TryKnockdown(EntityUid uid, TimeSpan time, Boolean refresh, StatusEffectsComponent status) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Stunnable/SharedStunSystem.cs:line 210
   at Content.Shared.Slippery.SlipperySystem.TrySlip(EntityUid uid, SlipperyComponent component, EntityUid other) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Slippery/SlipperySystem.cs:line 79
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 197
   at Content.Shared.StepTrigger.Systems.StepTriggerSystem.Update(EntityUid uid, StepTriggerComponent component, TransformComponent transform, EntityQuery`1 query) in /home/runner/work/space-station-14/space-station-14/Content.Shared/StepTrigger/Systems/StepTriggerSystem.cs:line 51
   at Content.Shared.StepTrigger.Systems.StepTriggerSystem.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Shared/StepTrigger/Systems/StepTriggerSystem.cs:line 37
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 318
 Catcher=entsys Sawmill=runtime
```
