### ISSUE TITLE
Cargo gift rule exception.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#18464]
The component's data-field needs a custom type serializer and the broken prototype needs to be fixed.

```
Caught exception in entsys
Robust.Shared.Prototypes.UnknownPrototypeException: Unknown prototype: CrateRestraints
   at Robust.Shared.Prototypes.PrototypeManager.Index[T](String id) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Prototypes/PrototypeManager.cs:line 188
   at Content.Server.StationEvents.Events.CargoGiftsRule.ActiveTick(EntityUid uid, CargoGiftsRuleComponent component, GameRuleComponent gameRule, Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/StationEvents/Events/CargoGiftsRule.cs:line 80
   at Content.Server.GameTicking.Rules.GameRuleSystem`1.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/GameTicking/Rules/GameRuleSystem.cs:line 81
   at Content.Server.StationEvents.Events.StationEventSystem`1.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/StationEvents/Events/StationEventSystem.cs:line 110
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 318
 Catcher=entsys Sawmill=runtime
```

**Comment by ElectroJr** [comment]
Duplicate of #17469, and already fixed
