### ISSUE TITLE
lookup debug assert

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18641]
## Description

0. using debug
1. start server
2. start client, join
3. restart server
4. try to join (i think)
5. debug assert on client

3-5 might be just waiting idk

```
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 36
   at Robust.Shared.GameObjects.EntityLookupSystem.UpdatePhysicsBroadphase(EntityUid uid, TransformComponent xform, PhysicsComponent body) in RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 288
   at Robust.Shared.GameObjects.EntityLookupSystem.OnBodyStartup(EntityUid uid, PhysicsComponent component, ComponentStartup args) in RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 116
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 255
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 393
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args, Boolean dispatchByReference) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 595
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 137
   at Robust.Shared.GameObjects.Component.LifeStartup(IEntityManager entManager) in RobustToolbox/Robust.Shared/GameObjects/Component.cs:line 90
   at Robust.Shared.GameObjects.EntityManager.StartComponents(EntityUid uid) in RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 174
   at Robust.Shared.GameObjects.EntityManager.StartEntity(EntityUid entity) in RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 799
   at Robust.Client.GameObjects.ClientEntityManager.Robust.Client.GameObjects.IClientEntityManagerInternal.StartEntity(EntityUid entity) in RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 58
   at Robust.Client.GameStates.ClientGameStateManager.InitializeAndStart(Dictionary`2 toCreate) in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 1060
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 806
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 644
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 320
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in RobustToolbox/Robust.Client/GameController/GameController.cs:line 605
   at Robust.Client.GameController.<StartupContinue>b__57_0(Object sender, FrameEventArgs args) in RobustToolbox/Robust.Client/GameController/GameController.cs:line 221
   at Robust.Shared.Timing.GameLoop.Run() in RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 233
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 134
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 119
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 86
```

@metalgearsloth i think your thing introduced this

**Comment by metalgearsloth** [comment]
A lot more than that seems to break on reconnecting the client.

**Comment by metalgearsloth** [comment]
Using https://github.com/space-wizards/space-station-14/pull/18416 + new engine PR should fix it.

**Comment by ElectroJr** [comment]
I can't seem to it using the given steps.

**Comment by deltanedas** [comment]
idk but itll probably be fixed
