### ISSUE TITLE
joining server debug assert

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#18740]
## Description
1. start server and client
2. join server
3. server die

```
[FATL] unhandled: System.AggregateException: One or more errors occurred. (Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.)
Unhandled exception. System.AggregateException: One or more errors occurred. (Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.)
 ---> Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 36
   at Content.Server.NPC.Pathfinding.PathfindingSystem.BuildBreadcrumbs(GridPathfindingChunk chunk, MapGridComponent grid, EntityQuery`1 accessQuery, EntityQuery`1 destructibleQuery, EntityQuery`1 doorQuery, EntityQuery`1 climbableQuery, EntityQuery`1 fixturesQuery, EntityQuery`1 physicsQuery, EntityQuery`1 xformQuery) in Content.Server/NPC/Pathfinding/PathfindingSystem.Grid.cs:line 561
   at Content.Server.NPC.Pathfinding.PathfindingSystem.<>c__DisplayClass71_2.<UpdateGrid>b__0(Int32 i) in Content.Server/NPC/Pathfinding/PathfindingSystem.Grid.cs:line 162
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at Content.Server.NPC.Pathfinding.PathfindingSystem.UpdateGrid() in Content.Server/NPC/Pathfinding/PathfindingSystem.Grid.cs:line 152
   at Content.Server.NPC.Pathfinding.PathfindingSystem.Update(Single frameTime) in Content.Server/NPC/Pathfinding/PathfindingSystem.cs:line 88
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 303
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 272
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 153
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in RobustToolbox/Robust.Server/BaseServer.cs:line 718
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in RobustToolbox/Robust.Server/BaseServer.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 228
   at Robust.Server.BaseServer.MainLoop() in RobustToolbox/Robust.Server/BaseServer.cs:line 562
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in RobustToolbox/Robust.Server/Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in Content.Server/Program.cs:line 9
```

might be fixed by current lookup prs idk

**Comment by metalgearsloth** [comment]
no it was me being dumb fixed in cc5d83f
