### ISSUE TITLE
If rack gun on the floor client crashes

### ISSUE THREAD

**Issue by proektgames** [space-wizards/space-station-14#19118]
## Description
If rack gun on the floor client crashes

**Reproduction**
shoot some times, unload magazine, load in magazine some cases from the floor, load magazine, rack gun

**Screenshots**
-

**Additional context**
[ERRO] root: Predicting the deletion of a networked entity: патрон (.30 винтовочный) (5738, CartridgeLightRifle). Trace:    at System.Environment.get_StackTrace()
   at Robust.Client.GameStates.ClientDirtySystem.OnTerminate(EntityTerminatingEvent& ev) in C:\Users\Master\Desktop\ss14\space-station-14-corvax\RobustToolbox\Robust.Client\GameStates\ClientDirtySystem.cs:line 47
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass6_0`1.<SubscribeEvent>b__0(Unit& ev) in C:\Users\Master\Desktop\ss14\space-station-14-corvax\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:lin
e 191
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in C:\Users\Master\Desktop\ss14\space-station-14-corvax\RobustToolbox\Robust.Shared\GameObje
cts\EntityEventBus.Broadcast.cs:line 332
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in C:\Users\Master\Desktop\ss14\space-station-14-corvax\RobustToolbox\Robust.Shared\Ga
meObjects\EntityEventBus.Directed.cs:line 226
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in C:\Users\Master\Desktop\ss14\space-station-14-corvax\RobustToolbox\Robust.Shared\GameObjects\EntityEventBu
s.Directed.cs:line 200

**Comment by lzk228** [comment]
try to test it on wizards build, because i saw liltenhead video on yt, and he racks gun on floor without any problems
then it can be corvax build issue

**Comment by ficcialfaint** [comment]
this is not our codebase + according the errors, the fix requires to be in RT
