### ISSUE TITLE
Right clicking and hovering over a Fulton bacon entry causes a debug assert

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#19705]
## Description

Server
```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Unknown component: SharedEntityStorageComponent
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, AssertInterpolatedStringHandler& message) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 73
   at Content.Shared.Foldable.FoldableSystem.CanToggleFold(EntityUid uid, FoldableComponent fold) in C:\Users\Vasilis\Desktop\space-station-14\Content.Shared\Foldable\FoldableSystem.cs:line 112
   at Content.Shared.Foldable.FoldableSystem.AddFoldVerb(EntityUid uid, FoldableComponent component, GetVerbsEvent`1 args) in C:\Users\Vasilis\Desktop\space-station-14\Content.Shared\Foldable\FoldableSystem.cs:line 140
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Gam
eObjects\EntityEventBus.Directed.cs:line 255
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.
Directed.cs:line 393
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args, Boolean dispatchByReference) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.
Directed.cs:line 554
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entit
yEventBus.Directed.cs:line 222
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:li
ne 182
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 150       
   at Content.Shared.Verbs.SharedVerbSystem.GetLocalVerbs(EntityUid target, EntityUid user, List`1 types, Boolean force) in C:\Users\Vasilis\Desktop\space-station-14\Content.Shared\Verbs\SharedVerbSystem.cs:line 131
   at Content.Server.Verbs.VerbSystem.HandleVerbRequest(RequestServerVerbsEvent args, EntitySessionEventArgs eventArgs) in C:\Users\Vasilis\Desktop\space-station-14\Content.Server\Verbs\VerbSystem.cs:line 60
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 169
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEvent
Bus.Broadcast.cs:line 332
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.
Broadcast.cs:line 317
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 263
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__11_0(Object _, Object systemMsg) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 52
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 252
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs
:line 154
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 717
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 534
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 561
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\Users\Vasilis\Desktop\space-station-14\Content.Server\Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Unknown component: SharedEntityStorageComponent
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, AssertInterpolatedStringHandler& message) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 73
   at Content.Shared.Foldable.FoldableSystem.CanToggleFold(EntityUid uid, FoldableComponent fold) in C:\Users\Vasilis\Desktop\space-station-14\Content.Shared\Foldable\FoldableSystem.cs:line 112
   at Content.Shared.Foldable.FoldableSystem.AddFoldVerb(EntityUid uid, FoldableComponent component, GetVerbsEvent`1 args) in C:\Users\Vasilis\Desktop\space-station-14\Content.Shared\Foldable\FoldableSystem.cs:line 140
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Gam
eObjects\EntityEventBus.Directed.cs:line 255
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.
Directed.cs:line 393
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args, Boolean dispatchByReference) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.
Directed.cs:line 554
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entit
yEventBus.Directed.cs:line 222
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:li
ne 182
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 150       
   at Content.Shared.Verbs.SharedVerbSystem.GetLocalVerbs(EntityUid target, EntityUid user, List`1 types, Boolean force) in C:\Users\Vasilis\Desktop\space-station-14\Content.Shared\Verbs\SharedVerbSystem.cs:line 131
   at Content.Server.Verbs.VerbSystem.HandleVerbRequest(RequestServerVerbsEvent args, EntitySessionEventArgs eventArgs) in C:\Users\Vasilis\Desktop\space-station-14\Content.Server\Verbs\VerbSystem.cs:line 60
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 169
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEvent
Bus.Broadcast.cs:line 332
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.
Broadcast.cs:line 317
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 263
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__11_0(Object _, Object systemMsg) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 52
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 252
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs
:line 154
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 717
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 534
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 561
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\Users\Vasilis\Desktop\space-station-14\Content.Server\Program.cs:line 9
   ```
Client
```
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Unknown component: SharedEntityStorageComponent
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, AssertInterpolatedStringHandler& message) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 73
   at Content.Shared.Foldable.FoldableSystem.CanToggleFold(EntityUid uid, FoldableComponent fold) in C:\Users\Vasilis\Desktop\space-station-14\Content.Shared\Foldable\FoldableSystem.cs:line 112
   at Content.Shared.Foldable.FoldableSystem.AddFoldVerb(EntityUid uid, FoldableComponent component, GetVerbsEvent`1 args) in C:\Users\Vasilis\Desktop\space-station-14\Content.Shared\Foldable\FoldableSystem.cs:line 140
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Gam
eObjects\EntityEventBus.Directed.cs:line 255
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.
Directed.cs:line 393
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args, Boolean dispatchByReference) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.
Directed.cs:line 554
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entit
yEventBus.Directed.cs:line 222
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:li
ne 182
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 150       
   at Content.Shared.Verbs.SharedVerbSystem.GetLocalVerbs(EntityUid target, EntityUid user, List`1 types, Boolean force) in C:\Users\Vasilis\Desktop\space-station-14\Content.Shared\Verbs\SharedVerbSystem.cs:line 131
   at Content.Client.Verbs.VerbSystem.GetVerbs(EntityUid target, EntityUid user, List`1 verbTypes, Boolean force) in C:\Users\Vasilis\Desktop\space-station-14\Content.Client\Verbs\VerbSystem.cs:line 192
   at Content.Client.Verbs.UI.VerbMenuUIController.OpenVerbMenu(EntityUid target, Boolean force, ContextMenuPopup popup) in C:\Users\Vasilis\Desktop\space-station-14\Content.Client\Verbs\UI\VerbMenuUIController.cs:line 77
   at Content.Client.ContextMenu.UI.EntityMenuUIController.<>c__DisplayClass34_0.<AddEntityToMenu>b__0() in C:\Users\Vasilis\Desktop\space-station-14\Content.Client\ContextMenu\UI\EntityMenuUIController.cs:line 270
   at Robust.Client.UserInterface.Controls.Popup.Open(Nullable`1 box, Nullable`1 altPos) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Client\UserInterface\Controls\Popup.cs:line 41
   at Content.Client.ContextMenu.UI.ContextMenuUIController.OpenSubMenu(ContextMenuElement element) in C:\Users\Vasilis\Desktop\space-station-14\Content.Client\ContextMenu\UI\ContextMenuUIController.cs:line 176
   at Content.Client.ContextMenu.UI.ContextMenuUIController.<>c__DisplayClass16_0.<OnMouseEntered>b__0() in C:\Users\Vasilis\Desktop\space-station-14\Content.Client\ContextMenu\UI\ContextMenuUIController.cs:line 113
   at Robust.Shared.Timing.Timer.Update(Single frameTime, IRuntimeLog runtimeLog) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Timing\Timer.cs:line 57
   at Robust.Shared.Timing.TimerManager.UpdateTimers(FrameEventArgs frameEventArgs) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Timing\TimerManager.cs:line 33
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 591
   at Robust.Client.GameController.<StartupContinue>b__57_0(Object sender, FrameEventArgs args) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 220
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 134
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 119
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in C:\Users\Vasilis\Desktop\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 86
```
**Reproduction**

1. Get fulton beacon
2. right click and hover over the entry
3. death
**Screenshots**

**Additional context**

Somethings fucked in FoldableSystem but I cant find out what

**Comment by VasilisThePikachu** [comment]
Guessing this is closed by #19717

**Comment by deltanedas** [comment]
fulton bacon

**Comment by VasilisThePikachu** [comment]
> fulton bacon

ಠ⁠_⁠ಠ
