### ISSUE TITLE
Replay recordings try to move the zip file while still writing?

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#19888]
Replay recordings seem to sometimes try to move a zip file while some process is still writing to them? This specifically happens when moving recordings from some temporary location.

```
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Robust.Shared.ContentPack.WritableDirProvider.Rename(ResPath oldPath, ResPath newPath) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\ContentPack\WritableDirProvider.cs:line 129
   at Content.Server.GameTicking.GameTicker.ReplaysOnRecordingFinished(ReplayRecordingFinished data) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\Content.Server\GameTicking\GameTicker.Replays.cs:line 82
   at Robust.Shared.Replays.SharedReplayRecordingManager.WriteFinalMetadata(RecordingState recState) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Replays\SharedReplayRecordingManager.cs:line 386
   at Robust.Shared.Replays.SharedReplayRecordingManager.WriteBatch(Boolean continueRecording) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Replays\SharedReplayRecordingManager.cs:line 300
   at Robust.Shared.Replays.SharedReplayRecordingManager.StopRecording() in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Replays\SharedReplayRecordingManager.cs:line 111
```

Reproduction steps:
- Start server & client, join game
- `/sudo cvar replay.auto_record true`
- `/sudo cvar replay.auto_record_temp_dir /a/`
- `/restartroundnow` 2+ times in quick succession.

**Comment by VerinSenpai** [comment]
I'm not able to reproduce this following the stated steps. Is this still being experienced?
