### ISSUE TITLE
fire shader black screen

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#19935]
## Description
when stepping on lava instantly black screen

**Reproduction**
1. go in lava room
2. lava
3. black screen

**Stacktrace**
```
[ERRO] ui: Caught exception while trying to draw a UI element: MainWindowRoot (WindowRoot)
[ERRO] runtime: Caught exception in "UserInterfaceManager"
System.InvalidOperationException: This shader instance is immutable and cannot be modified. Duplicate it instead.
   at Robust.Client.Graphics.ShaderInstance.EnsureMutable() in RobustToolbox/Robust.Client/Graphics/Shaders/ShaderInstance.cs:line 196
   at Robust.Client.Graphics.ShaderInstance.SetParameter(String name, Texture value) in RobustToolbox/Robust.Client/Graphics/Shaders/ShaderInstance.cs:line 167
   at Robust.Client.Graphics.Clyde.Clyde.DrawEntities(Viewport viewport, Box2Rotated worldBounds, Box2 worldAABB, IEye eye) in RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.HLR.cs:line 313
   at Robust.Client.Graphics.Clyde.Clyde.<>c__DisplayClass211_0.<RenderViewport>b__0() in RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.HLR.cs:line 506
   at Robust.Client.Graphics.Clyde.Clyde.RenderInRenderTarget(RenderTargetBase rt, Action a, Nullable`1 clearColor) in RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.HLR.cs:line 442
   at Robust.Client.Graphics.Clyde.Clyde.RenderViewport(Viewport viewport) in RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.HLR.cs:line 465
   at Robust.Client.Graphics.Clyde.Clyde.Viewport.Robust.Client.Graphics.IClydeViewport.Render() in RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Viewport.cs:line 122
   at Content.Client.Viewport.ScalingViewport.Draw(DrawingHandleScreen handle) in Content.Client/Viewport/ScalingViewport.cs:line 140
   at Robust.Client.UserInterface.Control.DrawInternal(IRenderHandle renderHandle) in RobustToolbox/Robust.Client/UserInterface/Control.cs:line 545
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Int32& total, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 384
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Int32& total, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 391
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Int32& total, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 391
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Int32& total, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 391
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Int32& total, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 391
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Int32& total, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 391
   at Robust.Client.UserInterface.UserInterfaceManager.<>c__DisplayClass162_0.<Render>g__DoRender|0(WindowRoot root) in RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Layout.cs:line 135
```

**Comment by kontakt** [comment]
No longer occurs.
