### ISSUE TITLE
game broke

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#20083]
## Description
lizard #33193 just before it was ended
people cant move ahelp is broken
rejoining breaks client

**Reproduction**
???? maybe fishops

**Screenshots**
logs when trying to rejoin
![00:30:39](https://github.com/space-wizards/space-station-14/assets/39013340/0e103ca0-5cc4-4532-9f66-d26ac0b8afce)

**Comment by deltanedas** [comment]
havent seen it happen again...

**Comment by Equivocateur** [comment]
Happened again on leviathan #33253.

**Comment by deltanedas** [comment]
:trollface:

**Comment by metalgearsloth** [comment]
when

**Comment by Equivocateur** [comment]
At the end of the leviathan round #33253 - we just vote restarted it to fix.
Ghosting seems to allow movement again until you decide to warp anywhere.

**Comment by Emisse** [comment]
get logs please

**Comment by Equivocateur** [comment]
> get logs please

No associated logs or error messages get created afaik.

**Comment by Emisse** [comment]
enable logging in launcher

**Comment by EmoGarbage404** [comment]
as it stands this issue is next to useless considering it consists of "game died" with no useful logs or information beyond that.

**Comment by deltanedas** [comment]
i provided "some" logs but doesnt actually say what caused it. purely guessing that its a deadlock

**Comment by Equivocateur** [comment]
Happened at the end at Lizard #33303 at the end of the round

Tail of stdout is
```
[ERRO] runtime: Caught exception in "ResetPredictedEntities"
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.<>c.<QueryMapBroadphase>b__19_0(ValueTuple`2& tuple, FixtureProxy& value) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 141
   at Robust.Shared.Physics.BroadPhase.DynamicTreeBroadPhase.AabbQueryStateCallback[TState](ValueTuple`6& tuple, Proxy proxy) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/BroadPhase/DynamicTreeBroadPhase.cs:line 136
   at Robust.Shared.Physics.B2DynamicTree`1.Query[TState](TState& state, QueryCallback`1 callback, Box2& aabb) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 894
   at Robust.Shared.Physics.BroadPhase.DynamicTreeBroadPhase.QueryAabb[TState](TState& state, QueryCallbackDelegate`1 callback, Box2 aabb, Boolean approx) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/BroadPhase/DynamicTreeBroadPhase.cs:line 64
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.FindGridContacts(PhysicsMapComponent component, MapId mapId, HashSet`1 movedGrids, Dictionary`2 gridMoveBuffer) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 92
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.FindNewContacts(PhysicsMapComponent component, MapId mapId)
   at Robust.Client.Physics.PhysicsSystem.ResetContacts() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Physics/PhysicsSystem.Predict.cs:line 110
   at Robust.Client.GameStates.ClientGameStateManager.ResetPredictedEntities() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 470
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 229
[ERRO] net.predict: Failed to apply comp state: entity=98385, comp=Robust.Shared.GameObjects.TransformComponent
[ERRO] runtime: Caught exception in "ClientGameStateManager.HandleEntityState"
System.Exception: Infinite loop in B2DynamicTree.Balance(). Trace:    at System.Environment.get_StackTrace()
   at Robust.Shared.Physics.B2DynamicTree`1.Balance(Proxy index) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 586
   at Robust.Shared.Physics.B2DynamicTree`1.InsertLeaf(Proxy leaf) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 543
   at Robust.Shared.Physics.B2DynamicTree`1.MoveProxy(Proxy proxy, Box2& aabb, Vector2 displacement) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 357
   at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdatePhysicsTree(EntityUid uid, EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, TransformComponent xform, PhysicsComponent body, FixturesComponent manager, EntityQuery`1 xformQuery) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 385
   at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, EntityUid uid, TransformComponent xform, Boolean recursive) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 670
   at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, EntityUid uid, TransformComponent xform, Boolean recursive) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 715
   at Robust.Shared.GameObjects.EntityLookupSystem.OnMove(MoveEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 466
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 332
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.SharedTransformSystem.SetCoordinates(EntityUid uid, TransformComponent xform, EntityCoordinates value, Nullable`1 rotation, Boolean unanchor, TransformComponent newParent, TransformComponent oldParent) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 587
   at Robust.Shared.GameObjects.SharedTransformSystem.OnHandleState(EntityUid uid, TransformComponent xform, ComponentHandleState& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 717
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 160
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(EntityUid uid, NetEntity netEntity, IEventBus bus, EntityState curState, EntityState nextState, GameTick lastApplied, GameTick toTick, Boolean enteringPvs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 1245
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 796
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 644
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 322
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 604
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 134
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 119
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 86
   at System.Threading.Thread.StartCallback()
   at Robust.Shared.Physics.B2DynamicTree`1.Balance(Proxy index)
   at Robust.Shared.Physics.B2DynamicTree`1.InsertLeaf(Proxy leaf) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 440
   at Robust.Shared.Physics.B2DynamicTree`1.MoveProxy(Proxy proxy, Box2& aabb, Vector2 displacement) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 303
   at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdatePhysicsTree(EntityUid uid, EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, TransformComponent xform, PhysicsComponent body, FixturesComponent manager, EntityQuery`1 xformQuery) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 373
   at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, EntityUid uid, TransformComponent xform, Boolean recursive) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 670
   at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, EntityUid uid, TransformComponent xform, Boolean recursive) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 670
   at Robust.Shared.GameObjects.EntityLookupSystem.OnMove(MoveEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 466
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 326
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.SharedTransformSystem.SetCoordinates(EntityUid uid, TransformComponent xform, EntityCoordinates value, Nullable`1 rotation, Boolean unanchor, TransformComponent newParent, TransformComponent oldParent) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 547
   at Robust.Shared.GameObjects.SharedTransformSystem.OnHandleState(EntityUid uid, TransformComponent xform, ComponentHandleState& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 697
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 160
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(EntityUid uid, NetEntity netEntity, IEventBus bus, EntityState curState, EntityState nextState, GameTick lastApplied, GameTick toTick, Boolean enteringPvs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 1258
[ERRO] net.predict: Failed to apply comp state: entity=98385, comp=Robust.Shared.GameObjects.TransformComponent
```

Error message repeats ad infinitum

**Comment by metalgearsloth** [comment]
> Happened on Lizard #33303 at the end of the round
> 
> Tail of stdout is
> 
> ```
> [ERRO] runtime: Caught exception in "ResetPredictedEntities"
> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
>    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
>    at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.<>c.<QueryMapBroadphase>b__19_0(ValueTuple`2& tuple, FixtureProxy& value) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 141
>    at Robust.Shared.Physics.BroadPhase.DynamicTreeBroadPhase.AabbQueryStateCallback[TState](ValueTuple`6& tuple, Proxy proxy) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/BroadPhase/DynamicTreeBroadPhase.cs:line 136
>    at Robust.Shared.Physics.B2DynamicTree`1.Query[TState](TState& state, QueryCallback`1 callback, Box2& aabb) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 894
>    at Robust.Shared.Physics.BroadPhase.DynamicTreeBroadPhase.QueryAabb[TState](TState& state, QueryCallbackDelegate`1 callback, Box2 aabb, Boolean approx) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/BroadPhase/DynamicTreeBroadPhase.cs:line 64
>    at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.FindGridContacts(PhysicsMapComponent component, MapId mapId, HashSet`1 movedGrids, Dictionary`2 gridMoveBuffer) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 92
>    at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.FindNewContacts(PhysicsMapComponent component, MapId mapId)
>    at Robust.Client.Physics.PhysicsSystem.ResetContacts() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Physics/PhysicsSystem.Predict.cs:line 110
>    at Robust.Client.GameStates.ClientGameStateManager.ResetPredictedEntities() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 470
>    at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 229
> [ERRO] net.predict: Failed to apply comp state: entity=98385, comp=Robust.Shared.GameObjects.TransformComponent
> [ERRO] runtime: Caught exception in "ClientGameStateManager.HandleEntityState"
> System.Exception: Infinite loop in B2DynamicTree.Balance(). Trace:    at System.Environment.get_StackTrace()
>    at Robust.Shared.Physics.B2DynamicTree`1.Balance(Proxy index) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 586
>    at Robust.Shared.Physics.B2DynamicTree`1.InsertLeaf(Proxy leaf) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 543
>    at Robust.Shared.Physics.B2DynamicTree`1.MoveProxy(Proxy proxy, Box2& aabb, Vector2 displacement) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 357
>    at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdatePhysicsTree(EntityUid uid, EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, TransformComponent xform, PhysicsComponent body, FixturesComponent manager, EntityQuery`1 xformQuery) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 385
>    at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, EntityUid uid, TransformComponent xform, Boolean recursive) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 670
>    at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, EntityUid uid, TransformComponent xform, Boolean recursive) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 715
>    at Robust.Shared.GameObjects.EntityLookupSystem.OnMove(MoveEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 466
>    at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 332
>    at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
>    at Robust.Shared.GameObjects.SharedTransformSystem.SetCoordinates(EntityUid uid, TransformComponent xform, EntityCoordinates value, Nullable`1 rotation, Boolean unanchor, TransformComponent newParent, TransformComponent oldParent) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 587
>    at Robust.Shared.GameObjects.SharedTransformSystem.OnHandleState(EntityUid uid, TransformComponent xform, ComponentHandleState& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 717
>    at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 160
>    at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(EntityUid uid, NetEntity netEntity, IEventBus bus, EntityState curState, EntityState nextState, GameTick lastApplied, GameTick toTick, Boolean enteringPvs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 1245
>    at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 796
>    at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 644
>    at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 322
>    at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 604
>    at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 240
>    at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 134
>    at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 119
>    at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 86
>    at System.Threading.Thread.StartCallback()
>    at Robust.Shared.Physics.B2DynamicTree`1.Balance(Proxy index)
>    at Robust.Shared.Physics.B2DynamicTree`1.InsertLeaf(Proxy leaf) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 440
>    at Robust.Shared.Physics.B2DynamicTree`1.MoveProxy(Proxy proxy, Box2& aabb, Vector2 displacement) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/B2DynamicTree.cs:line 303
>    at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdatePhysicsTree(EntityUid uid, EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, TransformComponent xform, PhysicsComponent body, FixturesComponent manager, EntityQuery`1 xformQuery) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 373
>    at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, EntityUid uid, TransformComponent xform, Boolean recursive) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 670
>    at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, EntityUid uid, TransformComponent xform, Boolean recursive) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 670
>    at Robust.Shared.GameObjects.EntityLookupSystem.OnMove(MoveEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 466
>    at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 326
>    at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
>    at Robust.Shared.GameObjects.SharedTransformSystem.SetCoordinates(EntityUid uid, TransformComponent xform, EntityCoordinates value, Nullable`1 rotation, Boolean unanchor, TransformComponent newParent, TransformComponent oldParent) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 547
>    at Robust.Shared.GameObjects.SharedTransformSystem.OnHandleState(EntityUid uid, TransformComponent xform, ComponentHandleState& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 697
>    at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 160
>    at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(EntityUid uid, NetEntity netEntity, IEventBus bus, EntityState curState, EntityState nextState, GameTick lastApplied, GameTick toTick, Boolean enteringPvs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 1258
> [ERRO] net.predict: Failed to apply comp state: entity=98385, comp=Robust.Shared.GameObjects.TransformComponent
> ```
> 
> Error message repeats ad infinitum

send the full thing in DMs rather than a crop.

**Comment by EmoGarbage404** [comment]
game is most likely no longer broke
