### ISSUE TITLE
Cooking raw meat crashes server

### ISSUE THREAD

**Issue by TheArturZh** [space-wizards/space-station-14#20248]
## Description

```
[FATL] unhandled: System.NullReferenceException: Object reference not set to an instance of an object.
    at Content.Server.Construction.ConstructionSystem.ChangeEntity(EntityUid uid, Nullable`1 userUid, String newEntity, ConstructionComponent construction, MetaDataComponent metaData, TransformComponent transform, ContainerManagerComponent containerManager) in E:\SS14Dev\space-station-14-official\Content.Server\Construction\ConstructionSystem.Graph.cs:line 386                                                                                                                          
    at Content.Server.Construction.ConstructionSystem.ChangeNode(EntityUid uid, Nullable`1 userUid, String id, Boolean performActions, ConstructionComponent construction) in E:\SS14Dev\space-station-14-official\Content.Server\Construction\ConstructionSystem.Graph.cs:line 259
    at Content.Server.Construction.ConstructionSystem.HandleEdge(EntityUid uid, Object ev, ConstructionGraphEdge edge, Boolean validation, ConstructionComponent construction) in E:\SS14Dev\space-station-14-official\Content.Server\Construction\ConstructionSystem.Interactions.cs:line 180
    at Content.Server.Construction.ConstructionSystem.HandleNode(EntityUid uid, Object ev, ConstructionGraphNode node, Boolean validation, ConstructionComponent construction) in E:\SS14Dev\space-station-14-official\Content.Server\Construction\ConstructionSystem.Interactions.cs:line 101
    at Content.Server.Construction.ConstructionSystem.HandleEvent(EntityUid uid, Object ev, Boolean validation, ConstructionComponent construction) in E:\SS14Dev\space-station-14-official\Content.Server\Construction\ConstructionSystem.Interactions.cs:line 77                                                                                                          
    at Content.Server.Construction.ConstructionSystem.UpdateInteractions() in E:\SS14Dev\space-station-14-official\Content.Server\Construction\ConstructionSystem.Interactions.cs:line 503
    at Content.Server.Construction.ConstructionSystem.Update(Single frameTime) in E:\SS14Dev\space-station-14-official\Content.Server\Construction\ConstructionSystem.cs:line 97
```
**Reproduction**

1. Find any raw meat
2. Throw in plasma fire
3. null forgiving operator moment :trollface:

**Comment by deltanedas** [comment]
reproduced
