### ISSUE TITLE
Gas leaking on closed windoors facing space 

### ISSUE THREAD

**Issue by TGODiamond** [space-wizards/space-station-14#21732]
## Description
When opening and closing a windoor out to space, gas begins to leak out even though the windoor is airtight. This bug stops entirely when placing a tile in front of the windoor out in space, even if the tile gets removed afterwards. This has something to do with directional airtightness. Something not getting initialized properly. Stumbled upon this bug when I was working on PR #21123.

**Reproduction**
* Build a windoor facing out in space (place it as the default direction (south))
* Open and close the windoor
* Gas is leaking out slowly, though no tiles get popped out of place while this happens

**Screenshots, videos, and errors**

https://github.com/space-wizards/space-station-14/assets/79604238/2b91556d-ae35-4fb4-a69d-4a7d69466675

https://github.com/space-wizards/space-station-14/assets/79604238/99e142f7-9f9f-487c-af30-4303f6fcedca

Errors on server:
```
[ERRO] root: Encountered null adjacent tile in AdjustEqMovement. Dir: South, Tile: TileRef: 11,-32 (Tile 115, 0, 0), non-null adj count: 1, Trace:    at System.Environment.get_StackTrace()
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.AdjustEqMovement(TileAtmosphere tile, AtmosDirection direction, Single amount) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Monstermos.cs:line 645
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.EqualizePressureInZone(Entity`2 ent, TileAtmosphere tile, Int32 cycleNum, GasTileOverlayComponent visuals) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Monstermos.cs:line 323
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.ProcessTileEqualize(Entity`1 ent, GasTileOverlayComponent visuals) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs:line 166
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.UpdateProcessing(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs:line 442
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.cs:line 71
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 306
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 236
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 160
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 719
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 566
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.Program.Main(String[] args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 25
[ERRO] runtime: Caught exception in "entsys"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.EqualizePressureInZone(Entity`2 ent, TileAtmosphere tile, Int32 cycleNum, GasTileOverlayComponent visuals) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Monstermos.cs:line 32
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.ProcessTileEqualize(Entity`1 ent, GasTileOverlayComponent visuals) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs:line 156
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.UpdateProcessing(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs:line 390
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.cs:line 92
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 321
```

Failed assert in debug configuration:
```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.EqualizePressureInZone(Entity`2 ent, TileAtmosphere tile, Int32 cycleNum, GasTileOverlayComponent visuals) in /home/magnus/Documents/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Monstermos.cs:line 289
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.ProcessTileEqualize(Entity`1 ent, GasTileOverlayComponent visuals) in /home/magnus/Documents/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs:line 166
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.UpdateProcessing(Single frameTime) in /home/magnus/Documents/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs:line 442
   at Content.Server.Atmos.EntitySystems.AtmosphereSystem.Update(Single frameTime) in /home/magnus/Documents/space-station-14/Content.Server/Atmos/EntitySystems/AtmosphereSystem.cs:line 71
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 306
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 236
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 160
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 722
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 539
   at Robust.Shared.Timing.GameLoop.Run() in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 566
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in /home/magnus/Documents/space-station-14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/magnus/Documents/space-station-14/Content.Server/Program.cs:line 9

```

**Comment by TGODiamond** [comment]
I think it has something to do with initialization of the door, since placing it in other directions than the default (south), this bug doesn't happen then.

**Comment by ElectroJr** [comment]
I'm fairly sure I know what the cause is, but my bugfix PR has turned into a somewhat larger refactor and will take a bit more time to finish.
