### ISSUE TITLE
grav anom pulse debug asserts

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#21755]
## Description
1. put grav anom in the middle of dev
2. pulse
3. client dies

```
[ERRO] runtime: Caught exception in "ResetPredictedEntities"
Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.AddToMoveBuffer(MapId mapId, FixtureProxy proxy, Box2 aabb) in RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 465
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.TouchProxies(MapId mapId, BroadphaseComponent broadphase, Fixture fixture) in RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 456
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.RegenerateContacts(EntityUid uid, PhysicsComponent body, FixturesComponent fixtures, TransformComponent xform) in RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 446
   at Content.Shared.Throwing.ThrownItemSystem.StopThrow(EntityUid uid, ThrownItemComponent thrownItemComponent) in Content.Shared/Throwing/ThrownItemSystem.cs:line 104
   at Content.Shared.Throwing.ThrownItemSystem.OnSleep(EntityUid uid, ThrownItemComponent thrownItem, PhysicsSleepEvent& event) in Content.Shared/Throwing/ThrownItemSystem.cs:line 89
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass48_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 289
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 399
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 550
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 224
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 202
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 160
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetAwake(Entity`1 ent, Boolean value, Boolean updateSleepTime) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 401
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetAwake(EntityUid uid, PhysicsComponent body, Boolean value, Boolean updateSleepTime) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 378
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetCanCollide(EntityUid uid, Boolean value, Boolean dirty, Boolean force, FixturesComponent manager, PhysicsComponent body) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 509
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.OnPhysicsHandleState(EntityUid uid, PhysicsComponent component, ComponentHandleState& args) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 92
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass48_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 289
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 399
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 165
   at Robust.Client.GameStates.ClientGameStateManager.ResetPredictedEntities() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 598
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 334
[ERRO] runtime: Caught exception in "ResetPredictedEntities"
Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.AddToMoveBuffer(MapId mapId, FixtureProxy proxy, Box2 aabb) in RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 465
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.TouchProxies(MapId mapId, BroadphaseComponent broadphase, Fixture fixture) in RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 456
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.RegenerateContacts(EntityUid uid, PhysicsComponent body, FixturesComponent fixtures, TransformComponent xform) in RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 446
   at Content.Shared.Throwing.ThrownItemSystem.StopThrow(EntityUid uid, ThrownItemComponent thrownItemComponent) in Content.Shared/Throwing/ThrownItemSystem.cs:line 104
   at Content.Shared.Throwing.ThrownItemSystem.OnSleep(EntityUid uid, ThrownItemComponent thrownItem, PhysicsSleepEvent& event) in Content.Shared/Throwing/ThrownItemSystem.cs:line 89
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass48_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 289
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 399
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 550
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 224
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 202
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 160
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetAwake(Entity`1 ent, Boolean value, Boolean updateSleepTime) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 401
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetAwake(EntityUid uid, PhysicsComponent body, Boolean value, Boolean updateSleepTime) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 378
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetCanCollide(EntityUid uid, Boolean value, Boolean dirty, Boolean force, FixturesComponent manager, PhysicsComponent body) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 509
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.OnPhysicsHandleState(EntityUid uid, PhysicsComponent component, ComponentHandleState& args) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 92
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass48_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 289
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 399
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 165
   at Robust.Client.GameStates.ClientGameStateManager.ResetPredictedEntities() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 598
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 334
[ERRO] runtime: Caught exception in "ResetPredictedEntities"
Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.AddToMoveBuffer(MapId mapId, FixtureProxy proxy, Box2 aabb) in RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 465
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.TouchProxies(MapId mapId, BroadphaseComponent broadphase, Fixture fixture) in RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 456
   at Robust.Shared.Physics.Systems.SharedBroadphaseSystem.RegenerateContacts(EntityUid uid, PhysicsComponent body, FixturesComponent fixtures, TransformComponent xform) in RobustToolbox/Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs:line 446
   at Content.Shared.Throwing.ThrownItemSystem.StopThrow(EntityUid uid, ThrownItemComponent thrownItemComponent) in Content.Shared/Throwing/ThrownItemSystem.cs:line 104
   at Content.Shared.Throwing.ThrownItemSystem.OnSleep(EntityUid uid, ThrownItemComponent thrownItem, PhysicsSleepEvent& event) in Content.Shared/Throwing/ThrownItemSystem.cs:line 89
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass48_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 289
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 399
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 550
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 224
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 202
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 160
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetAwake(Entity`1 ent, Boolean value, Boolean updateSleepTime) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 401
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetAwake(EntityUid uid, PhysicsComponent body, Boolean value, Boolean updateSleepTime) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 378
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetCanCollide(EntityUid uid, Boolean value, Boolean dirty, Boolean force, FixturesComponent manager, PhysicsComponent body) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 509
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.OnPhysicsHandleState(EntityUid uid, PhysicsComponent component, ComponentHandleState& args) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs:line 92
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass48_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 289
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 399
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 165
   at Robust.Client.GameStates.ClientGameStateManager.ResetPredictedEntities() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 598
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 334
[ERRO] state: Failed to apply comp state: entity=t-ray scanner (1075, trayScanner), comp=Robust.Shared.GameObjects.TransformComponent
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateSundriesTree(EntityUid broadUid, BroadphaseComponent broadphase, EntityUid uid, TransformComponent xform, Boolean staticBody, Nullable`1 aabb) in RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 436
   at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, TransformComponent broadphaseXform, PhysicsMapComponent physicsMap, EntityUid uid, TransformComponent xform, Boolean recursive) in RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 688
   at Robust.Shared.GameObjects.EntityLookupSystem.AddOrUpdateEntityTree(EntityUid broadUid, BroadphaseComponent broadphase, EntityUid uid, TransformComponent xform, Boolean recursive) in RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 653
   at Robust.Shared.GameObjects.EntityLookupSystem.UpdateEntityTree(EntityUid uid, TransformComponent xform) in RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 637
   at Robust.Shared.GameObjects.EntityLookupSystem.OnMove(MoveEvent& args) in RobustToolbox/Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs:line 468
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass6_0`1.<SubscribeEvent>b__0(Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 195
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 332
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 228
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 202
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 160
   at Robust.Shared.GameObjects.SharedTransformSystem.SetCoordinates(Entity`2 entity, EntityCoordinates value, Nullable`1 rotation, Boolean unanchor, TransformComponent newParent, TransformComponent oldParent) in RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 605
   at Robust.Shared.GameObjects.SharedTransformSystem.SetCoordinates(EntityUid uid, TransformComponent xform, EntityCoordinates value, Nullable`1 rotation, Boolean unanchor, TransformComponent newParent, TransformComponent oldParent) in RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 617
   at Robust.Shared.GameObjects.SharedTransformSystem.OnHandleState(EntityUid uid, TransformComponent xform, ComponentHandleState& args) in RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 745
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass48_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 289
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 399
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 165
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(EntityUid uid, NetEntity netEntity, MetaDataComponent meta, IEventBus bus, EntityState curState, EntityState nextState, GameTick lastApplied, GameTick toTick, Boolean enteringPvs) in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 1322
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 867
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 719
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 381
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in RobustToolbox/Robust.Client/GameController/GameController.cs:line 532
   at Robust.Client.GameController.<StartupContinue>b__57_0(Object sender, FrameEventArgs args) in RobustToolbox/Robust.Client/GameController/GameController.cs:line 220
   at Robust.Shared.Timing.GameLoop.Run() in RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 134
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 119
   at Robust.Client.GameController.<>c__DisplayClass98_0.<Run>b__0() in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 86
```

**Comment by ketufaispikinut** [comment]
Can't reproduce
