### ISSUE TITLE
Runtime in Computervisualizer while its being deleted by a singulo

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#2184]
will be a todo as soon as #2169 is merged

```
Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in D:\Workspaces\Github\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 48
   at Robust.Shared.GameObjects.Entity.GetComponent[T]() in D:\Workspaces\Github\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 269
   at Content.Client.GameObjects.Components.ComputerVisualizer.OnChangeData(AppearanceComponent component) in D:\Workspaces\Github\space-station-14\Content.Client\GameObjects\Components\ComputerVisualizer.cs:line 61
```

**Comment by DrSmugleaf** [comment]
Related to https://github.com/space-wizards/RobustToolbox/issues/1237

**Comment by AJCM-git** [comment]
Cant repro anymore
