### ISSUE TITLE
s-casing exception

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2204]
[ERRO] runtime: Caught exception in "GameLoop Update"
System.Collections.Generic.KeyNotFoundException: The given key 's-casing' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Content.Client.ClickMapManager.IsOccluding(RSI rsi, StateId state, Direction dir, Int32 frame, Vector2i pos) in /var/lib/jenkins/workspace/SS14 Content/Content.Client/ClickMapManager.cs:line 73
   at Content.Client.GameObjects.Components.ClickableComponent.CheckClick(Vector2 worldPos, Int32& drawDepth, UInt32& renderOrder) in /var/lib/jenkins/workspace/SS14 Content/Content.Client/GameObjects/Components/ClickableComponent.cs:line 110
   at Content.Client.State.GameScreenBase.GetEntitiesUnderPosition(MapCoordinates coordinates) in /var/lib/jenkins/workspace/SS14 Content/Content.Client/State/GameScreenBase.cs:line 128
   at Content.Client.State.GameScreenBase.FrameUpdate(FrameEventArgs e) in /var/lib/jenkins/workspace/SS14 Content/Content.Client/State/GameScreenBase.cs:line 63
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController.cs:line 296
   at Robust.Shared.Timing.GameLoop.Run() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 242

**Comment by PJB3005** [comment]
The exception was fixed in b168a7926ff14e6acd9d806185b378aac7b808d6, the bug causing the broken sprite in 1fa960d5d6af827237e31a634df37f62f171f86b
