### ISSUE TITLE
Trying to pick up dragged item causes unhandled exception

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#22507]
## Description
Trying to pick up an item that your controlled mob is dragging causes an unhandled exception and in debug it crashes the client
Only happens if you try to pick up an item YOU are dragging. Can pick up item dragged by others

**Reproduction**

Load devmap
Start dragging a crowbar
Change to free hand
Try to pick up crowbar - error/crash.

**Screenshots**
```
[DEBG] system.joint: Added Distance Joint with ID pull-joint-635 from Dynamic to KinematicController 
[DEBG] system.joint: Initializing joint pull-joint-635
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Expected: not 54
   at Robust.Shared.Utility.DebugTools.AssertNotEqual(Object objA, Object objB) in /home/user/s14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 72
   at Robust.Shared.Physics.Systems.SharedJointSystem.SetRelay(EntityUid uid, Nullable`1 relay, JointComponent component) in /home/user/s14/RobustToolbox/Robust.Shared/Physics/Systems/SharedJointSystem.Relay.cs:line 125
   at Robust.Shared.Physics.Systems.SharedJointSystem.RefreshRelay(EntityUid uid, JointComponent component) in /home/user/s14/RobustToolbox/Robust.Shared/Physics/Systems/SharedJointSystem.Relay.cs:line 75
   at Robust.Shared.Containers.BaseContainer.RecursivelyUpdateJoints(EntityUid uid, TransformComponent xform, SharedJointSystem jointSys, EntityQuery`1 jointQuery, EntityQuery`1 transformQuery) in /home/user/s14/RobustToolbox/Robust.Shared/Containers/BaseContainer.cs:line 249
   at Robust.Shared.Containers.BaseContainer.Insert(EntityUid toinsert, IEntityManager entMan, TransformComponent transform, TransformComponent ownerTransform, MetaDataComponent meta, PhysicsComponent physics, Boolean force) in /home/user/s14/RobustToolbox/Robust.Shared/Containers/BaseContainer.cs:line 193
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.DoPickup(EntityUid uid, Hand hand, EntityUid entity, HandsComponent hands) in /home/user/s14/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 220
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, Hand hand, Boolean checkActionBlocker, Boolean animate, HandsComponent handsComp, ItemComponent item) in /home/user/s14/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 121
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, String handName, Boolean checkActionBlocker, Boolean animateUser, Boolean animate, HandsComponent handsComp, ItemComponent item) in /home/user/s14/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 60
   at Content.Shared.Item.SharedItemSystem.OnHandInteract(EntityUid uid, ItemComponent component, InteractHandEvent args) in /home/user/s14/Content.Shared/Item/SharedItemSystem.cs:line 79
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass46_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/user/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 256
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/user/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 399
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass66_1.<EntCollectOrdered>b__0(Unit& ev) in /home/user/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 567
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in /home/user/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 49
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast) in /home/user/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 40
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in /home/user/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 220
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 184
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/s14/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 149
   at Content.Shared.Interaction.SharedInteractionSystem.InteractHand(EntityUid user, EntityUid target) in /home/user/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 425
   at Content.Shared.Interaction.SharedInteractionSystem.UserInteraction(EntityUid user, EntityCoordinates coordinates, Nullable`1 target, Boolean altInteract, Boolean checkCanInteract, Boolean checkAccess, Boolean checkCanUse) in /home/user/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 376
   at Content.Shared.Interaction.SharedInteractionSystem.HandleUseInteraction(ICommonSession session, EntityCoordinates coords, EntityUid uid) in /home/user/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 250
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass5_0.<.ctor>b__0(PointerInputCmdArgs& args) in /home/user/s14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 97
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in /home/user/s14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 121
   at Robust.Client.GameObjects.InputSystem.HandleInputCommand(ICommonSession session, BoundKeyFunction function, IFullInputCmdMessage message, Boolean replay) in /home/user/s14/RobustToolbox/Robust.Client/GameObjects/EntitySystems/InputSystem.cs:line 78
   at Content.Client.Gameplay.GameplayStateBase.OnKeyBindStateChanged(ViewportBoundKeyEventArgs args) in /home/user/s14/Content.Client/Gameplay/GameplayStateBase.cs:line 207
   at Content.Client.Gameplay.GameplayState.OnKeyBindStateChanged(ViewportBoundKeyEventArgs args) in /home/user/s14/Content.Client/Gameplay/GameplayState.cs:line 117
   at Robust.Client.Input.InputManager.ViewportKeyEvent(Control viewport, BoundKeyEventArgs eventArgs) in /home/user/s14/RobustToolbox/Robust.Client/Input/InputManager.cs:line 445
   at Content.Client.Viewport.ScalingViewport.KeyBindDown(GUIBoundKeyEventArgs args) in /home/user/s14/Content.Client/Viewport/ScalingViewport.cs:line 122
   at Robust.Client.UserInterface.UserInterfaceManager.<>c.<KeyBindDown>b__125_0(Control c, GUIBoundKeyEventArgs ev) in /home/user/s14/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 107
   at Robust.Client.UserInterface.UserInterfaceManager._doGuiInput(Control control, GUIBoundKeyEventArgs guiEvent, Action`2 action, Boolean ignoreStop) in /home/user/s14/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 282
   at Robust.Client.UserInterface.UserInterfaceManager.KeyBindDown(BoundKeyEventArgs args) in /home/user/s14/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 107
   at Robust.Client.UserInterface.UserInterfaceManager.OnUIKeyBindStateChanged(BoundKeyEventArgs args) in /home/user/s14/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 436
   at Robust.Client.Input.InputManager.SetBindState(KeyBinding binding, BoundKeyState state, Boolean uiOnly) in /home/user/s14/RobustToolbox/Robust.Client/Input/InputManager.cs:line 404
   at Robust.Client.Input.InputManager.DownBind(KeyBinding binding, Boolean uiOnly, Boolean isRepeat) in /home/user/s14/RobustToolbox/Robust.Client/Input/InputManager.cs:line 355
   at Robust.Client.Input.InputManager.KeyDown(KeyEventArgs args) in /home/user/s14/RobustToolbox/Robust.Client/Input/InputManager.cs:line 276
   at Robust.Client.GameController.KeyDown(KeyEventArgs keyEvent) in /home/user/s14/RobustToolbox/Robust.Client/GameController/GameController.Input.cs:line 12
   at Robust.Client.Graphics.Clyde.Clyde.DispatchSingleEvent(DEventBase ev) in /home/user/s14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 47
   at Robust.Client.Graphics.Clyde.Clyde.DispatchEvents() in /home/user/s14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 31
   at Robust.Client.Graphics.Clyde.Clyde.ProcessInput(FrameEventArgs frameEventArgs) in /home/user/s14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Windowing.cs:line 392
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in /home/user/s14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 489
   at Robust.Client.GameController.<StartupContinue>b__58_2(Object sender, FrameEventArgs args) in /home/user/s14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 240
   at Robust.Shared.Timing.GameLoop.Run() in /home/user/s14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 187
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/user/s14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 158
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/user/s14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 143
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in /home/user/s14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 108

Process finished with exit code 134.
```

**Comment by Errant-4** [comment]
Issue has been fixed at some point
