### ISSUE TITLE
ReflectSystem null exceptions

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#22603]
From grafana:

```
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value() in /_/src/runtime/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Nullable.cs:line 45
   at Content.Shared.Weapons.Reflect.SharedReflectSystem.TryReflectProjectile(EntityUid user, EntityUid reflector, EntityUid projectile, ProjectileComponent projectileComp, ReflectComponent reflect) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Reflect/SharedReflectSystem.cs:line 124
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass48_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 289
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 550
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 202
   at Content.Server.Projectiles.ProjectileSystem.OnStartCollide(EntityUid uid, ProjectileComponent component, StartCollideEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Server/Projectiles/ProjectileSystem.cs:line 39
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 550
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 202
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.CollideContacts() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Contacts.cs:line 557
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.cs:line 310
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 306
 Catcher=entsys Sawmill=runtime
```

**Comment by kontakt** [comment]
Closing as stale.
