### ISSUE TITLE
NPC/Medibot exceptions

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#22604]
From grafan:
```
System.Collections.Generic.KeyNotFoundException: The given key 'Dead' was not present in the dictionary.
   at Content.Server.NPC.HTN.PrimitiveTasks.Operators.Specific.MedibotInjectOperator.Update(NPCBlackboard blackboard, Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/NPC/HTN/PrimitiveTasks/Operators/Specific/MedibotInjectOperator.cs:line 50
   at Content.Server.NPC.HTN.HTNSystem.Update(HTNComponent component, Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/NPC/HTN/HTNSystem.cs:line 335
   at Content.Server.NPC.HTN.HTNSystem.UpdateNPC(Int32& count, Int32 maxUpdates, Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/NPC/HTN/HTNSystem.cs:line 247
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 306
 Catcher=entsys Sawmill=runtime
```

**Comment by deltanedas** [comment]
bruh that should never happen
