### ISSUE TITLE
BatteryRampPegSolver throws exception DebugAssertException

### ISSUE THREAD

**Issue by IlyaBokovenko** [space-wizards/space-station-14#22612]
`2023-12-16T12:37:56.8557266+01:00 [FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\Projects\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 37
   at Content.Server.Power.Pow3r.BatteryRampPegSolver.UpdateNetwork(Network network, PowerState state, Single frameTime) in C:\Projects\space-station-14\Content.Server\Power\Pow3r\BatteryRampPegSolver.cs:line 278
   at Content.Server.Power.Pow3r.BatteryRampPegSolver.UpdateNetworkJob.Execute(Int32 index) in C:\Projects\space-station-14\Content.Server\Power\Pow3r\BatteryRampPegSolver.cs:line 371
   at Robust.Shared.Threading.ParallelManager.InternalParallelJob.Execute() in C:\Projects\space-station-14\RobustToolbox\Robust.Shared\Threading\ParallelManager.cs:line 231
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()`

While debugging I have noticed that battery.SupplyRampTarget have some reasonable amount (assigned from unmet) but battery.LoadingNetworkDemand is 0
The only place where battery.LoadingNetworkDemand get zero is ClearBatteries which is called at the end of Tick
So this is probably multihreading issue in `parallel.ProcessNow(_networkJob, group.Count);`

**Comment by wafehling** [comment]
Hate this thing. Makes debugging a huge pain.

**Comment by Tayrtahn** [comment]
Shortcut for investigating: https://github.com/space-wizards/space-station-14/blob/master/Content.Server%2FPower%2FPow3r%2FBatteryRampPegSolver.cs#L278

**Comment by slarticodefast** [comment]
This keeps happening to me after 2-3 minutes on the dev map. This makes debugging really hard.

**Comment by diamondhorne** [comment]
same

**Comment by Just-a-Unity-Dev** [comment]
Still having this on Across The Veil, which last pulled upstream from commit ce0a51fc29675b3b0afb90296b6a8ce90c3f9cd3.

**Comment by ShadowCommander** [comment]
Still happening randomly.

![rider64_UJS6mx7G1s](https://github.com/space-wizards/space-station-14/assets/10494922/b1c07f74-b8f5-458a-b2b4-78b3951d8b3c)

**Comment by slarticodefast** [comment]
Didn't happen in a long time, so I'm assuming this is resolved.
