### ISSUE TITLE
Server crash when constructing crude spears

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/space-station-14#228]
Steps to reproduce:
1. Place a crude spear construction ghost
2. Click it with a steel stack and the server should crash

Exception info:
```
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at Robust.Server.GameObjects.SpriteComponent.AddLayerWithSprite(SpriteSpecifier specifier) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Server\GameObjects\Components\Renderable\SpriteComponent.cs:line 144
   at Content.Server.GameObjects.Components.Construction.ConstructionComponent.Init(ConstructionPrototype prototype) in C:\Users\moneyl\source\repos\space-station-14\Content.Server\GameObjects\Components\Construction\ConstructionComponent.cs:line 91
   at Content.Server.GameObjects.Components.Construction.ConstructorComponent.TryStartStructureConstruction(GridCoordinates loc, String prototypeName, Angle angle, Int32 ack) in C:\Users\moneyl\source\repos\space-station-14\Content.Server\GameObjects\Components\Construction\ConstructorComponent.cs:line 93
   at Content.Server.GameObjects.Components.Construction.ConstructorComponent.HandleMessage(ComponentMessage message, INetChannel netChannel, IComponent component) in C:\Users\moneyl\source\repos\space-station-14\Content.Server\GameObjects\Components\Construction\ConstructorComponent.cs:line 37
   at Robust.Shared.GameObjects.Entity.HandleNetworkMessage(IncomingEntityMessage message) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 204
   at Robust.Shared.GameObjects.EntityManager.HandleEntityNetworkMessage(MsgEntity msg) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 459
   at Robust.Shared.Network.NetManager.<>c__DisplayClass56_0`1.<RegisterNetMessage>b__0(NetMessage msg) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 573
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 558
   at Robust.Shared.Network.NetManager.ProcessPackets() in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 262
   at Robust.Server.BaseServer.Update(Single frameTime) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 346
   at Robust.Server.BaseServer.<MainLoop>b__32_0(Object sender, FrameEventArgs args) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 262
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 168
   at Robust.Server.BaseServer.MainLoop() in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 265
   at Robust.Server.EntryPoint.Main(String[] args) in C:\Users\moneyl\source\repos\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 85
```

**Comment by raymoo** [comment]
I tried constructing one on the public server and the server didn't crash, but my client stopped updating the visual positions of objects. I could hear my footsteps still. (Linux client)
