### ISSUE TITLE
Doesnt run on Linux

### ISSUE THREAD

**Issue by user424242420** [space-wizards/space-station-14#23624]
## Description

I git clone your repo and it build Client, but it doesnt run

**Reproduction**

1) Download repo to linux machine
2) Run python3 run_this.py
3) Build with dotnet build
4) Run with dotnet run --project Content.Client

**Screenshots**

```
[ERRO] discord: Failed connection to /run/user/1000/discord-ipc-0. The operation has timed out.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Robust.Client.UserInterface.CustomControls.DebugConsole.<_loadHistoryFromDisk>b__47_0() in /tmp/space-station-14/RobustToolbox/Robust.Client/UserInterface/CustomControls/DebugConsole.xaml.cs:line 229
   at Robust.Client.UserInterface.CustomControls.DebugConsole._loadHistoryFromDisk() in /tmp/space-station-14/RobustToolbox/Robust.Client/UserInterface/CustomControls/DebugConsole.xaml.cs:line 195
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Robust.Shared.Asynchronous.RobustSynchronizationContext.ProcessPendingTasks() in /tmp/space-station-14/RobustToolbox/Robust.Shared/Asynchronous/RobustSynchronizationContext.cs:line 60
   at Robust.Shared.Asynchronous.TaskManager.ProcessPendingTasks() in /tmp/space-station-14/RobustToolbox/Robust.Shared/Asynchronous/TaskManager.cs:line 28
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in /tmp/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 499
   at Robust.Client.GameController.<StartupContinue>b__58_2(Object sender, FrameEventArgs args) in /tmp/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 240
   at Robust.Shared.Timing.GameLoop.Run() in /tmp/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 187
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /tmp/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 164
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /tmp/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 149
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in /tmp/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 108
^C^Z
```

**Additional context**

IDK

**Comment by lzk228** [comment]
First you should try to ask help in discord

**Comment by deltanedas** [comment]
does run on linux https://voidlinux.org enter the void

**Comment by PJB3005** [comment]
I see the bug here. As a workaround in the mean time, you can delete your `~/.local/share/Space Station 14/data/debug_console_history.json` file and that should fix it.

**Comment by user424242420** [comment]
> I see the bug here. As a workaround in the mean time, you can delete your `~/.local/share/Space Station 14/data/debug_console_history.json` file and that should fix it.

Working, thank you
