### ISSUE TITLE
bolting guns can cause a deletion prediction error

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#23878]
## Description

In some cases bolting a gun can cause a deletion prediction error for a cartridge the client expects to be in the magazine.

**Reproduction**

Take an mk58 > repeatedly shoot it, emptying the mag > reload the magazine > insert and rebolt gun > repeat until issue arises.

Im not 100% sure, it may need the magazine to not be completely filled, and it may be related to filling the magazine from an ammo box.  

```
[ERRO] system.client_dirty: Predicting the deletion of a networked entity: cartridge (.35 auto practice) (9400/n795595, CartridgePistolPractice). Trace:    at System.Environment.get_StackTrace()
   at Robust.Client.GameStates.ClientDirtySystem.OnTerminate(EntityTerminatingEvent& ev) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientDirtySystem.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 195
   at Robust.Shared.GameObjects.EntityManager.RecursiveFlagEntityTermination(EntityUid uid, MetaDataComponent metadata, TransformComponent xform) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 520
   at Robust.Shared.GameObjects.EntityManager.DeleteEntity(Nullable`1 uid) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 463
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.CycleCartridge(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Nullable`1 user, AppearanceComponent appearance) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 235
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.SetBoltClosed(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Boolean value, Nullable`1 user, AppearanceComponent appearance, ItemSlotsComponent slots) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 155
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.ToggleBolt(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Nullable`1 user) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 254
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.UseChambered(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Nullable`1 user) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 98
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnChamberUse(EntityUid uid, ChamberMagazineAmmoProviderComponent component, UseInHandEvent args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 70
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 177
   at Robust.Shared.Input.Binding.InputCmdHandler.StateInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 68
   at Robust.Client.GameObjects.InputSystem.HandleInputCommand(ICommonSession session, BoundKeyFunction function, IFullInputCmdMessage message, Boolean replay) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/EntitySystems/InputSystem.cs:line 78
   at Content.Client.Gameplay.GameplayStateBase.OnKeyBindStateChanged(ViewportBoundKeyEventArgs args) in /home/runner/work/space-station-14/space-station-14/Content.Client/Gameplay/GameplayStateBase.cs:line 207
   at Robust.Client.Input.InputManager.ViewportKeyEvent(Control viewport, BoundKeyEventArgs eventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Input/InputManager.cs:line 424
   at Robust.Client.UserInterface.UserInterfaceManager.KeyBindDown(BoundKeyEventArgs args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 75
   at Robust.Client.Input.InputManager.SetBindState(KeyBinding binding, BoundKeyState state, Boolean uiOnly) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Input/InputManager.cs:line 404
   at Robust.Client.Input.InputManager.KeyDown(KeyEventArgs args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Input/InputManager.cs:line 276
   at Robust.Client.Graphics.Clyde.Clyde.DispatchSingleEvent(DEventBase ev) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 47
   at Robust.Client.Graphics.Clyde.Clyde.DispatchEvents() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 31
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 489
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 164
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 149
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 108
   at System.Threading.Thread.StartCallback()
[ERRO] runtime: Caught exception in "GameLoop Tick"
System.ArgumentException: Entity 0 is not valid. (Parameter 'uid')
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid, T component, Boolean overwrite, MetaDataComponent metadata) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 251
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 188
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.EnsureShootable(EntityUid uid) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs:line 429
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnBallisticTakeAmmo(EntityUid uid, BallisticAmmoProviderComponent component, TakeAmmoEvent args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs:line 242
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 177
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.CycleCartridge(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Nullable`1 user, AppearanceComponent appearance) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 219
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.ToggleBolt(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Nullable`1 user) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 254
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.UseChambered(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Nullable`1 user) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 98
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnChamberUse(EntityUid uid, ChamberMagazineAmmoProviderComponent component, UseInHandEvent args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 70
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 177
   at Robust.Shared.Input.Binding.InputCmdHandler.StateInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 68
   at Robust.Client.GameObjects.InputSystem.PredictInputCommand(IFullInputCmdMessage inputCmd) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/EntitySystems/InputSystem.cs:line 110
   at Robust.Client.GameStates.ClientGameStateManager.PredictTicks(GameTick predictionTarget) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 499
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 452
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
```
The 2nd error repeats many times.

After a bit, I also then get this error with a random entity
```
[ERRO] runtime: Caught exception in "GameLoop Tick"
System.ArgumentException: Entity 0 is not valid. (Parameter 'uid')
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid, T component, Boolean overwrite, MetaDataComponent metadata) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 251
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 188
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.EnsureShootable(EntityUid uid) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs:line 429
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnBallisticTakeAmmo(EntityUid uid, BallisticAmmoProviderComponent component, TakeAmmoEvent args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs:line 242
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 177
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.CycleCartridge(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Nullable`1 user, AppearanceComponent appearance) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 219
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnChamberUse(EntityUid uid, ChamberMagazineAmmoProviderComponent component, UseInHandEvent args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 70
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 177
   at Robust.Shared.Input.Binding.InputCmdHandler.StateInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 68
   at Robust.Client.GameObjects.InputSystem.PredictInputCommand(IFullInputCmdMessage inputCmd) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/EntitySystems/InputSystem.cs:line 110
   at Robust.Client.GameStates.ClientGameStateManager.PredictTicks(GameTick predictionTarget) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 499
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 452
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
[INFO] state: Requesting full server state
[ERRO] runtime: Caught exception in "GameLoop Tick"
Robust.Client.GameStates.MissingMetadataException: Server state is missing the metadata component for a new entity: 795595.
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 767
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 722
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 386
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
[INFO] state: Received Full GameState: to=289694, sz=571600
[INFO] state: Resetting all entity states to tick 289694.
[INFO] state: Requesting full server state
[ERRO] runtime: Caught exception in "GameLoop Tick"
Robust.Client.GameStates.MissingMetadataException: Server state is missing the metadata component for a new entity: 497301.
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 767
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 722
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 386
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
[INFO] state: Received Full GameState: to=289706, sz=571736
[INFO] state: Resetting all entity states to tick 289706.
[INFO] state: Requesting full server state
[ERRO] runtime: Caught exception in "GameLoop Tick"
Robust.Client.GameStates.MissingMetadataException: Server state is missing the metadata component for a new entity: 497303.
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 767
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 722
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 386
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
[INFO] state: Received Full GameState: to=289715, sz=571688
[INFO] state: Resetting all entity states to tick 289715.
[INFO] state: Requesting full server state
[ERRO] runtime: Caught exception in "GameLoop Tick"
Robust.Client.GameStates.MissingMetadataException: Server state is missing the metadata component for a new entity: 497303.
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 767
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 722
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 386
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
[INFO] state: Received Full GameState: to=289724, sz=571718
[INFO] state: Resetting all entity states to tick 289724.
[INFO] state: Requesting full server state
[ERRO] runtime: Caught exception in "GameLoop Tick"
Robust.Client.GameStates.MissingMetadataException: Server state is missing the metadata component for a new entity: 497303.
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 767
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 722
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 386
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
   
   ...
```

I think entity 497303 was a random screwdriver on centcom.

The station / centcom then appears like random sections of it are missing everything but the tiles.

**Screenshots**

**Additional context**

I can provide more logs if you need.

**Comment by IProduceWidgets** [comment]
#23772 Potentially related

**Comment by dragonryan06** [comment]
I got a different error but mine sounds closely related, I was also messing with racking/bolting a gun when issue #24010 occurred

**Comment by Errant-4** [comment]
Is this related to  #19165 which causes debug asserts every time an entity-cartridge* is cycled into the gun?
*A cartridge that has been removed from it's magazine/box where it was just counted as an integer, and has became an actual entity
