### ISSUE TITLE
Cooking Fertilized Chicken Egg debugasserts on DestroyContacts

### ISSUE THREAD

**Issue by Varen** [space-wizards/space-station-14#24041]
## Description
Cooking fertilized egg, when the chicken spawns, will somehow trigger destroycontacts debugassert.

**Reproduction**

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/3650235/30e22c86-4c87-46fb-a0af-4a463c62ce13)
![image](https://github.com/space-wizards/space-station-14/assets/3650235/29ce5409-4d4c-45a1-bfb6-30e237f4b5e4)

**Additional context**

```[DEBG] system.n_p_c: Waking chicken (2360/n2360, MobChicken)
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 37
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.DestroyContacts(PhysicsComponent body) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\Physics\Systems\SharedPhysicsSystem.Components.cs:line 199
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.OnCollisionChange(CollisionChangeEvent& ev) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\Physics\Systems\SharedPhysicsSystem.cs:line 120
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass6_0`1.<SubscribeEvent>b__0(Unit& ev) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 195
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T& toRaise) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 283
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[T](T& message) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 95
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SetCanCollide(EntityUid uid, Boolean value, Boolean dirty, Boolean force, FixturesComponent manager, PhysicsComponent body) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\Physics\Systems\SharedPhysicsSystem.Components.cs:line 530
   at Robust.Shared.GameObjects.CollisionWakeSystem.UpdateCanCollide(EntityUid uid, CollisionWakeComponent component, PhysicsComponent body, TransformComponent xform, Boolean checkTerminating, Boolean dirty) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\Systems\CollisionWakeSystem.cs:line 122
   at Robust.Shared.GameObjects.CollisionWakeSystem.SetEnabled(EntityUid uid, Boolean enabled, CollisionWakeComponent component) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\Systems\CollisionWakeSystem.cs:line 39
   at Content.Shared.Placeable.ItemPlacerSystem.OnEndCollide(EntityUid uid, ItemPlacerComponent comp, EndCollideEvent& args) in G:\SS14\VRepo\Content.Shared\Placeable\ItemPlacerSystem.cs:line 51
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass50_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 282
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass62_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 432
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 584
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 217
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 195
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 160
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.DestroyContact(Contact contact) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\Physics\Systems\SharedPhysicsSystem.Contacts.cs:line 332
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.DestroyContacts(PhysicsComponent body) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\Physics\Systems\SharedPhysicsSystem.Components.cs:line 196
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.OnContactEntityQueueDel(EntityUid obj) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\Physics\Systems\SharedPhysicsSystem.Contacts.cs:line 195
   at Robust.Shared.GameObjects.EntityManager.QueueDeleteEntity(Nullable`1 uid) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 627
   at Robust.Shared.Spawners.SharedTimedDespawnSystem.Update(Single frameTime) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\Spawners\SharedTimedDespawnSystem.cs:line 40
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 306
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in G:\SS14\VRepo\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 246
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in G:\SS14\VRepo\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 154
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in G:\SS14\VRepo\RobustToolbox\Robust.Server\BaseServer.cs:line 729
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in G:\SS14\VRepo\RobustToolbox\Robust.Server\BaseServer.cs:line 542
   at Robust.Shared.Timing.GameLoop.Run() in G:\SS14\VRepo\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in G:\SS14\VRepo\RobustToolbox\Robust.Server\BaseServer.cs:line 569
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in G:\SS14\VRepo\RobustToolbox\Robust.Server\Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in G:\SS14\VRepo\RobustToolbox\Robust.Server\Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in G:\SS14\VRepo\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in G:\SS14\VRepo\Content.Server\Program.cs:line 9
```

**Comment by themias** [comment]
This only seems to happen when you place the egg directly on the grill. If you put the egg next to the grill, it will still warm up the egg enough to spawn the chicken, with no debug assert.
