### ISSUE TITLE
Attempting to load monadstation crashes the game!

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#2422]
The current revision of PR #2416 crashes the game on load. Not at home so I can't get the error log, will do so later. Anyone can easily reproduce it.

**Comment by moonheart08** [comment]
Crash log:
```
[FATL] unhandled: System.ArgumentException: An item with the same key has already been added. Key: Content.Server.GameObjects.Components.NodeContainer.Nodes.AdjacentNode
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.BaseNetConnectorNodeGroup`2.OnAddNode(Node node) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/NodeGroups/BaseNetConnectorNodeGroup.cs:line 18
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.BaseNodeGroup.AddNode(Node node) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/NodeGroups/INodeGroup.cs:line 50
   at Content.Server.GameObjects.Components.NodeContainer.Nodes.Node.SetNodeGroup(INodeGroup newGroup) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/Nodes/Node.cs:line 148
   at Content.Server.GameObjects.Components.NodeContainer.Nodes.Node.set_NodeGroup(INodeGroup value) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/Nodes/Node.cs:line 28
   at Content.Server.GameObjects.Components.NodeContainer.Nodes.Node.TryAssignGroupIfNeeded() in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/Nodes/Node.cs:line 89
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.BaseNodeGroup.RemakeGroup() in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/NodeGroups/INodeGroup.cs:line 87
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.NodeGroupManager.Update(Single frameTime) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/NodeGroups/INodeGroupManager.cs:line 32
   at Content.Server.GameObjects.EntitySystems.NodeGroupSystem.Update(Single frameTime) in /home/moony/projects/space-station-14/Content.Server/GameObjects/EntitySystems/NodeGroupSystem.cs:line 14
   at Robust.Shared.GameObjects.EntitySystemManager.Update(Single frameTime) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 250
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 95
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 962
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 567
   at Robust.Server.BaseServer.<MainLoop>b__43_1(Object sender, FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 415
   at Robust.Shared.Timing.GameLoop.Run() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 195
   at Robust.Server.BaseServer.MainLoop() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 421
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 89
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 49
   at Robust.Server.ContentStart.Start(String[] args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/moony/projects/space-station-14/Content.Server/Program.cs:line 9
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: Content.Server.GameObjects.Components.NodeContainer.Nodes.AdjacentNode
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.BaseNetConnectorNodeGroup`2.OnAddNode(Node node) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/NodeGroups/BaseNetConnectorNodeGroup.cs:line 18
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.BaseNodeGroup.AddNode(Node node) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/NodeGroups/INodeGroup.cs:line 50
   at Content.Server.GameObjects.Components.NodeContainer.Nodes.Node.SetNodeGroup(INodeGroup newGroup) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/Nodes/Node.cs:line 148
   at Content.Server.GameObjects.Components.NodeContainer.Nodes.Node.set_NodeGroup(INodeGroup value) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/Nodes/Node.cs:line 28
   at Content.Server.GameObjects.Components.NodeContainer.Nodes.Node.TryAssignGroupIfNeeded() in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/Nodes/Node.cs:line 89
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.BaseNodeGroup.RemakeGroup() in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/NodeGroups/INodeGroup.cs:line 87
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.NodeGroupManager.Update(Single frameTime) in /home/moony/projects/space-station-14/Content.Server/GameObjects/Components/NodeContainer/NodeGroups/INodeGroupManager.cs:line 32
   at Content.Server.GameObjects.EntitySystems.NodeGroupSystem.Update(Single frameTime) in /home/moony/projects/space-station-14/Content.Server/GameObjects/EntitySystems/NodeGroupSystem.cs:line 14
   at Robust.Shared.GameObjects.EntitySystemManager.Update(Single frameTime) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 250
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 95
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 962
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 567
   at Robust.Server.BaseServer.<MainLoop>b__43_1(Object sender, FrameEventArgs args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 415
   at Robust.Shared.Timing.GameLoop.Run() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 195
   at Robust.Server.BaseServer.MainLoop() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 421
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 89
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 49
   at Robust.Server.ContentStart.Start(String[] args) in /home/moony/projects/space-station-14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/moony/projects/space-station-14/Content.Server/Program.cs:line 9
```

**Comment by collinlunn** [comment]
I loaded up the map by removing the power connection from wires to prevent the crash. But when I tp to the specific wire that is causing the crash, something in the occuder system crashes.

**Comment by SweptWasTaken** [comment]
Monadstation PR is closed. Closing.
