### ISSUE TITLE
[ERRO] runtime: Caught exception in "entsys"

### ISSUE THREAD

**Issue by KloopRE** [space-wizards/space-station-14#24262]
The error seems to have been related to the fact that the key largestSource did not exist in the component.LifetimeDamage dictionary, and attempting to retrieve the value using this key (component.LifetimeDamage[largestSource]) resulted in a KeyNotFoundException.

I tried to fix this error, but is kludge

Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]: [ERRO] runtime: Caught exception in "entsys"
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]: System.Collections.Generic.KeyNotFoundException: The given key 'KillNpcSource { NpcEnt = 11642016 }' was not present in the dictionary.
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Server.KillTracking.KillTrackingSystem.OnMobStateChanged(EntityUid uid, KillTrackerComponent component, MobStateChangedEvent args) in /opt/servers/DeadSPace-Server/Content.Server/KillTracking/KillTrackingSystem.cs:line 75
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass48_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /opt/servers/DeadSPace-Server/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 249
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /opt/servers/DeadSPace-Server/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 584
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /opt/servers/DeadSPace-Server/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 177
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Shared.Mobs.Systems.MobStateSystem.UpdateMobState(EntityUid entity, MobStateComponent component, Nullable`1 origin) in /opt/servers/DeadSPace-Server/Content.Shared/Mobs/Systems/MobStateSystem.StateMachine.cs:line 30
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Shared.Mobs.Systems.MobThresholdSystem.CheckThresholds(EntityUid target, MobStateComponent mobStateComponent, MobThresholdsComponent thresholdsComponent, DamageableComponent damageableComponent, Nullable`1 origin) in /opt/servers/DeadSPace-Server/Content.Shared/Mobs/Systems/MobThresholdSystem.cs:line 342
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Shared.Mobs.Systems.MobThresholdSystem.OnDamaged(EntityUid target, MobThresholdsComponent thresholds, DamageChangedEvent args) in /opt/servers/DeadSPace-Server/Content.Shared/Mobs/Systems/MobThresholdSystem.cs:line 417
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in /opt/servers/DeadSPace-Server/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 47
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast) in /opt/servers/DeadSPace-Server/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 40
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /opt/servers/DeadSPace-Server/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 177
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Shared.Damage.DamageableSystem.DamageChanged(EntityUid uid, DamageableComponent component, DamageSpecifier damageDelta, Boolean interruptsDoAfters, Nullable`1 origin) in /opt/servers/DeadSPace-Server/Content.Shared/Damage/Systems/DamageableSystem.cs:line 113
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Shared.Damage.DamageableSystem.TryChangeDamage(Nullable`1 uid, DamageSpecifier damage, Boolean ignoreResistances, Boolean interruptsDoAfters, DamageableComponent damageable, Nullable`1 origin) in /opt/servers/DeadSPace-Server/Content.Shared/Damage/Systems/DamageableSystem.cs:line 191
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Shared.Weapons.Melee.SharedMeleeWeaponSystem.DoLightAttack(EntityUid user, LightAttackEvent ev, EntityUid meleeUid, MeleeWeaponComponent component, ICommonSession session) in /opt/servers/DeadSPace-Server/Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs:line 506
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Shared.Weapons.Melee.SharedMeleeWeaponSystem.AttemptAttack(EntityUid user, EntityUid weaponUid, MeleeWeaponComponent weapon, AttackEvent attack, ICommonSession session) in /opt/servers/DeadSPace-Server/Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs:line 414
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Shared.Weapons.Melee.SharedMeleeWeaponSystem.AttemptLightAttack(EntityUid user, EntityUid weaponUid, MeleeWeaponComponent weapon, EntityUid target) in /opt/servers/DeadSPace-Server/Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs:line 326
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Server.NPC.Systems.NPCCombatSystem.Attack(EntityUid uid, NPCMeleeCombatComponent component, TimeSpan curTime, EntityQuery`1 physicsQuery, EntityQuery`1 xformQuery) in /opt/servers/DeadSPace-Server/Content.Server/NPC/Systems/NPCCombatSystem.Melee.cs:line 117
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Server.NPC.Systems.NPCCombatSystem.UpdateMelee(Single frameTime) in /opt/servers/DeadSPace-Server/Content.Server/NPC/Systems/NPCCombatSystem.Melee.cs:line 57
Jan 18 17:52:54 Ubuntu-2204-jammy-amd64-base Content.Server[2059118]:    at Content.Server.NPC.Systems.NPCCombatSystem.Update(Single frameTime) in /opt/servers/DeadSPace-Server/Content.Server/NPC/Systems/NPCCombatSystem.cs:line 43

**Comment by KloopRE** [comment]
I think an asynchronous operation occurred that removed a key from the dictionary after it was added.

![image](https://github.com/space-wizards/space-station-14/assets/100780612/410c6262-2907-427d-bc80-57ad5b226902)

**Comment by KloopRE** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/100780612/51ad8cde-406d-4e13-8703-15570ffe4ad6)
this line:
if (component.LifetimeDamage[largestSource] >= component.LifetimeDamage[killSource] / 2)
I used the TryGetValue method to check for the presence of a key. I also logged warnings to the console if the key was not found.
![image](https://github.com/space-wizards/space-station-14/assets/100780612/d1fad5e0-ec28-4399-9802-30d4939a68e9)

Here is the result: the fatal error is gone. But this should not have happened!
![image](https://github.com/space-wizards/space-station-14/assets/100780612/d8c441cd-b690-4e60-a0b8-a5329b11c035)

I also added these lines.

![image](https://github.com/space-wizards/space-station-14/assets/100780612/01f8ce7a-75cb-4d78-b2ae-5c4667f38158)

![image](https://github.com/space-wizards/space-station-14/assets/100780612/c024a6e5-3b69-40ee-8535-7b01f150c3d2)
but is kludge

**Comment by Pok27** [comment]
Fixed in #28553
