### ISSUE TITLE
Surveillance сamera is able to introduce duplicate chunks in PvsSession.Chunks, which crashes debug build

### ISSUE THREAD

**Issue by TheArturZh** [space-wizards/space-station-14#24624]
## Description

Comment in Robust.Server/GameStates/PvsSystem.Chunks.cs at line 99 says that `// The list of visible chunks should be unique.` , but camera is able to introduce duplicate chunks in PvsSession.Chunks, which trips the debug assert.

```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 37
   at Robust.Server.GameStates.PvsSystem.GetVisibleChunks() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\GameStates\PvsSystem.Chunks.cs:line 100
   at Robust.Server.GameStates.PvsSystem.BeforeSendState() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\GameStates\PvsSystem.cs:line 424
   at Robust.Server.GameStates.PvsSystem.SendGameStates(ICommonSession[] players) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\GameStates\PvsSystem.cs:line 174
   at Robust.Server.GameStates.ServerGameStateManager.SendGameStateUpdate() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\GameStates\ServerGameStateManager.cs:line 68
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\BaseServer.cs:line 738
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\BaseServer.cs:line 542
   at Robust.Shared.Timing.GameLoop.Run() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\BaseServer.cs:line 569
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\Program.cs:line 76
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\Program.cs:line 44
   at Robust.Server.ContentStart.Start(String[] args) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in E:\SS14Dev\space-station-14-official\Content.Server\Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 37
   at Robust.Server.GameStates.PvsSystem.GetVisibleChunks() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\GameStates\PvsSystem.Chunks.cs:line 100
   at Robust.Server.GameStates.PvsSystem.BeforeSendState() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\GameStates\PvsSystem.cs:line 424
   at Robust.Server.GameStates.PvsSystem.SendGameStates(ICommonSession[] players) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\GameStates\PvsSystem.cs:line 174
   at Robust.Server.GameStates.ServerGameStateManager.SendGameStateUpdate() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\GameStates\ServerGameStateManager.cs:line 68
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\BaseServer.cs:line 738
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\BaseServer.cs:line 542
   at Robust.Shared.Timing.GameLoop.Run() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\BaseServer.cs:line 569
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\Program.cs:line 76
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\Program.cs:line 44
   at Robust.Server.ContentStart.Start(String[] args) in E:\SS14Dev\space-station-14-official\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in E:\SS14Dev\space-station-14-official\Content.Server\Program.cs:line 9
```

**Reproduction**

1. Build debug
2. Boot up the game and go to nearest camera monitor
3. Open camera that shows your character
4. Server crashes

**Comment by TheArturZh** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/pull/5094
