### ISSUE TITLE
Attempting to send a message with a tag in it ending in a } throws Pidgin.ParseException

### ISSUE THREAD

**Issue by FairlySadPanda** [space-wizards/space-station-14#24671]
## Description
Found this whilst doing a chat refactor. Huzzah for typos.

**Reproduction**
Steps to reproduce:
1. Open the dev client
2. Type "hello world [amogus}" in chat
3. Open the console

Expected:
1. You send a message saying "hello world"
2. There's no error in the console

Actual:
1. You send no message
2. There's a Pigin.ParseException error.

**Additional context**
```unhandled: Pidgin.ParseException: Parse error.
    unexpected }
    expected "/", or "]"
    at line 1, col 35
   at Pidgin.ParserExtensions.GetValueOrThrow[TToken,T](Result`2 result)
   at Pidgin.ParserExtensions.ParseOrThrow[T](Parser`2 parser, String input, IConfiguration`1 configuration)
   at Robust.Shared.Utility.FormattedMessage.Parse(String input) in C:\Users\karak\RiderProjects\honk-station-14\RobustToolbox\Robust.Shared\Utility\FormattedMessage.MarkupParser.cs:line 46
   at Robust.Shared.Utility.FormattedMessage.AddMarkup(String markup) in C:\Users\karak\RiderProjects\honk-station-14\RobustToolbox\Robust.Shared\Utility\FormattedMessage.MarkupParser.cs:line 27
   at Robust.Shared.Utility.FormattedMessage.FromMarkup(String markup) in C:\Users\karak\RiderProjects\honk-station-14\RobustToolbox\Robust.Shared\Utility\FormattedMessage.cs:line 58
   at Robust.Shared.Utility.FormattedMessage.RemoveMarkup(String text) in C:\Users\karak\RiderProjects\honk-station-14\RobustToolbox\Robust.Shared\Utility\FormattedMessage.cs:line 89
```

**Comment by FairlySadPanda** [comment]
(Probably an engine issue actually but it bubbles up as a chat bug)
