### ISSUE TITLE
If there aren't enough players available, DoThiefStart can cause a the round-start to fail

### ISSUE THREAD

**Issue by DebugOk** [space-wizards/space-station-14#24784]
## Description
Pretty simple, I assume its this line right here
https://github.com/space-wizards/space-station-14/blob/6e68a6ca10d84c90370c94af9e7ca14a6c8fb7b9/Content.Server/GameTicking/Rules/ThiefRuleSystem.cs#L92

If there arent enough players in the pool, you might be requesting too much from PickAntag and causing a crash. I haven't dug into it too much, but just from a glance thats what I assume is going on

**Reproduction**
Start a thief round with less available willing players then the game expects.

**Additional context**
```
3 thieves required, 0 currently chosen, 1 potentials
 Sawmill=system.thief_rule
```

```
Caught exception in GameTicker
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Robust.Shared.Random.RandomExtensions.PickAndTake[T](IRobustRandom random, IList`1 list) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/Random/RandomExtensions.cs:line 56
   at Content.Server.Antag.AntagSelectionSystem.PickAntag(Int32 antagCount, List`1 prefList) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 213
   at Content.Server.GameTicking.Rules.ThiefRuleSystem.DoThiefStart(ThiefRuleComponent component) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/Rules/ThiefRuleSystem.cs:line 92
   at Content.Server.GameTicking.Rules.ThiefRuleSystem.OnPlayersSpawned(RulePlayerJobsAssignedEvent ev) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/Rules/ThiefRuleSystem.cs:line 68
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T toRaise) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 275
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[T](T message) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 90
   at Content.Server.GameTicking.GameTicker.SpawnPlayers(List`1 readyPlayers, Dictionary`2 profiles, Boolean force) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/GameTicker.Spawning.cs:line 119
   at Content.Server.GameTicking.GameTicker.StartRound(Boolean force) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/GameTicker.RoundFlow.cs:line 242
 Catcher=GameTicker Sawmill=runtime
```

**Comment by bhenrich** [comment]
so now the question is if there are less thieves available than 3, do we cancel adding thieves to the round, or do we pick all available thieves?

**Comment by bhenrich** [comment]
@DebugOk how often did you see this happen in rounds?

**Comment by DebugOk** [comment]
> @DebugOk how often did you see this happen in rounds?

I've only seen it happen once, and that wasn't even on Wizden
