### ISSUE TITLE
Power crash

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2493]
@collinlunn When trying to load monadstation:

```
System.ArgumentException: An item with the same key has already been added. Key: Content.Server.GameObjects.Components.NodeContainer.Nodes.AdjacentNode
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.BaseNetConnectorNodeGroup`2.OnAddNode(Node node) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\NodeContainer\NodeGroups\BaseNetConnectorNodeGroup.cs:line 18
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.BaseNodeGroup.AddNode(Node node) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\NodeContainer\NodeGroups\INodeGroup.cs:line 50
   at Content.Server.GameObjects.Components.NodeContainer.Nodes.Node.SetNodeGroup(INodeGroup newGroup) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\NodeContainer\Nodes\Node.cs:line 148
   at Content.Server.GameObjects.Components.NodeContainer.Nodes.Node.set_NodeGroup(INodeGroup value) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\NodeContainer\Nodes\Node.cs:line 28
   at Content.Server.GameObjects.Components.NodeContainer.Nodes.Node.TryAssignGroupIfNeeded() in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\NodeContainer\Nodes\Node.cs:line 89
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.BaseNodeGroup.RemakeGroup() in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\NodeContainer\NodeGroups\INodeGroup.cs:line 87
   at Content.Server.GameObjects.Components.NodeContainer.NodeGroups.NodeGroupManager.Update(Single frameTime) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\NodeContainer\NodeGroups\INodeGroupManager.cs:line 32
   at Content.Server.GameObjects.EntitySystems.NodeGroupSystem.Update(Single frameTime) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\EntitySystems\NodeGroupSystem.cs:line 14
   at Robust.Shared.GameObjects.EntitySystemManager.Update(Single frameTime) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 250
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 95
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 962
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 567
   at Robust.Server.BaseServer.<MainLoop>b__43_1(Object sender, FrameEventArgs args) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 415
   at Robust.Shared.Timing.GameLoop.Run() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 195
   at Robust.Server.BaseServer.MainLoop() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 421
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 89
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 49
   at Robust.Server.Program.Main(String[] args) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 28
```

**Comment by SweptWasTaken** [comment]
Not an issue since it's only for Monad and I think it was fixed by the mentioned PR anyway. Closing.
