### ISSUE TITLE
Exception on connecting (exception in message handler for MsgVoteData)

### ISSUE THREAD

**Issue by Partmedia** [space-wizards/space-station-14#25002]
## Description
A player sent me a log. PII removed:

```
[DEBG] net: Attempting to connect to lizard.spacestation14.io port 1212
<snip>
[DEBG] net: Handshake completed, connection established.
[INFO] net: Received message name string table.
[INFO] net: Client completed serializer handshake.
[INFO] cfg: Sending client info...
[DEBG] client: Synchronized time base: 1: 00:00:00
[INFO] client: Tickrate changed to: 30 on tick 0
<snip>
[DEBG] admin: Have 21 commands available
[INFO] admin: Updated admin status: Not admin
[WARN] state: Exceeded maximum state buffer size!
Tick: 0/0/0
Size: 513
Applicable states: 0
Was waiting for full: True (0, 12/31/9999 11:59:59 PM)
Had full state: False
[INFO] state: Requesting full server state
[WARN] state: Exceeded maximum state buffer size!
Tick: 0/0/0
Size: 513
Applicable states: 0
Was waiting for full: True (0, 2/6/2024 8:49:19 AM)
Had full state: False
[INFO] state: Requesting full server state
[ERRO] net: <snip>: exception in message handler for MsgVoteData:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Robust.Shared.GameObjects.EntitySystemManager.GetEntitySystem[T]() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 69
   at Content.Client.Voting.VoteManager.ReceiveVoteData(MsgVoteData message) in /home/runner/work/space-station-14/space-station-14/Content.Client/Voting/VoteManager.cs:line 129
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 927
```

This last exception repeats many many times.

**Comment by Halalrc** [comment]
the same problem... What actions?
