### ISSUE TITLE
Content.Client crashes when typing CRE in Spawn entities search box

### ISSUE THREAD

**Issue by Ygg01** [space-wizards/space-station-14#2511]
**Steps to reproduce:**
1. Launch Server and Client (in playground mode).
2. Open the Spawn Entities menu.
3. Enter text "CRE" (case not important) into the Spawn Entities search bar.

**Expect**
Expected to search the entities.

**Actual**
Client crashes with following log

```
[FATL] unhandled: System.Collections.Generic.KeyNotFoundException: The given key 'Open' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Client.GameObjects.AppearanceComponent.GetData[T](Enum key) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Appearance\AppearanceComponent.cs:line
 49
   at Content.Client.GameObjects.Components.Storage.CrematoriumVisualizer.OnChangeData(AppearanceComponent component) in D:\projects\space-station-14\Content.Client\GameObjects\Components\Morgue
\CrematoriumVisualizer.cs:line 47
   at Robust.Client.GameObjects.SpriteComponent.GetPrototypeTextures(EntityPrototype prototype, IResourceCache resourceCache)+MoveNext() in D:\projects\space-station-14\RobustToolbox\Robust.Clie
nt\GameObjects\Components\Renderable\SpriteComponent.cs:line 1840
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.InsertEntityButton(EntityPrototype prototype, Boolean insertFirst, Int32 index) in D:\projects\space-station-14\RobustToolbox\R
obust.Client\UserInterface\CustomControls\EntitySpawnWindow.cs:line 315
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.UpdateVisiblePrototypes() in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\CustomControls\EntitySpawnW
indow.cs:line 286
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.FrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\CustomControls\Entit
ySpawnWindow.cs:line 386
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\Control.cs:line 703
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\Control.cs:line 706
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\Control.cs:line 706
   at Robust.Client.UserInterface.UserInterfaceManager.FrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 183
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 294
   at Robust.Client.GameController.<MainLoop>b__65_3(Object sender, FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:l
ine 108
   at Robust.Shared.Timing.GameLoop.Run() in D:\projects\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 242
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:
line 59
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
   at Robust.Client.ContentStart.Start(String[] args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in D:\projects\space-station-14\Content.Client\Program.cs:line 9
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'Open' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Client.GameObjects.AppearanceComponent.GetData[T](Enum key) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Appearance\AppearanceComponent.cs:line
 49
   at Content.Client.GameObjects.Components.Storage.CrematoriumVisualizer.OnChangeData(AppearanceComponent component) in D:\projects\space-station-14\Content.Client\GameObjects\Components\Morgue
\CrematoriumVisualizer.cs:line 47
   at Robust.Client.GameObjects.SpriteComponent.GetPrototypeTextures(EntityPrototype prototype, IResourceCache resourceCache)+MoveNext() in D:\projects\space-station-14\RobustToolbox\Robust.Clie
nt\GameObjects\Components\Renderable\SpriteComponent.cs:line 1840
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.InsertEntityButton(EntityPrototype prototype, Boolean insertFirst, Int32 index) in D:\projects\space-station-14\RobustToolbox\R
obust.Client\UserInterface\CustomControls\EntitySpawnWindow.cs:line 315
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.UpdateVisiblePrototypes() in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\CustomControls\EntitySpawnW
indow.cs:line 286
   at Robust.Client.UserInterface.CustomControls.EntitySpawnWindow.FrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\CustomControls\Entit
ySpawnWindow.cs:line 386
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\Control.cs:line 703
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\Control.cs:line 706
   at Robust.Client.UserInterface.Control.DoFrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\Control.cs:line 706
   at Robust.Client.UserInterface.UserInterfaceManager.FrameUpdate(FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 183
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 294
   at Robust.Client.GameController.<MainLoop>b__65_3(Object sender, FrameEventArgs args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:l
ine 108
   at Robust.Shared.Timing.GameLoop.Run() in D:\projects\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 242
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 113
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:
line 59
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in D:\projects\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 35
   at Robust.Client.ContentStart.Start(String[] args) in D:\projects\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in D:\projects\space-station-14\Content.Client\Program.cs:line 9
```

https://media.giphy.com/media/n64kLkXgHfCgDmKQbU/giphy.gif

**Comment by Ygg01** [comment]
🎉
