### ISSUE TITLE
something causing power ramping debug assert

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#26512]
## Description
title

## Reproduction
1. forcemap Saltern
2. restartroundnow
3. wait random amount of time then debug assert

## Message
```
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Content.Server.Power.Pow3r.BatteryRampPegSolver.UpdateNetwork(Network network, PowerState state, Single frameTime) in Content.Server/Power/Pow3r/BatteryRampPegSolver.cs:line 278
   at Content.Server.Power.Pow3r.BatteryRampPegSolver.UpdateNetworkJob.Execute(Int32 index) in Content.Server/Power/Pow3r/BatteryRampPegSolver.cs:line 371
   at Robust.Shared.Threading.ParallelManager.InternalParallelJob.Execute() in RobustToolbox/Robust.Shared/Threading/ParallelManager.cs:line 239
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by slarticodefast** [comment]
I just got the same error while testing a totally unrelated botany change on the dev map. This seems to be an older problem.
#22612

**Comment by deltanedas** [comment]
yeah dupe of #22612
