### ISSUE TITLE
golobby command crashing client

### ISSUE THREAD

**Issue by wrexbe** [space-wizards/space-station-14#26552]
1. Start server + client
2. Be on the map
3. Use golobby on client
4. Error happens
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Robust.Shared.GameObjects.AllEntityQueryEnumerator`2.MoveNext(EntityUid& uid, TComp1& comp1, TComp2& comp2) in C:\Users\Wrexbe2\repos\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.Components.cs:line 2006
   at Robust.Client.GameStates.ClientGameStateManager.PartialStateReset(GameState state, Boolean resetAllEntities, Boolean deleteClientEntities, Boolean deleteClientChildren) in C:\Users\Wrexbe2\repos\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 972
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in C:\Users\Wrexbe2\repos\space-station-14\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 351
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in C:\Users\Wrexbe2\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 535
   at Robust.Client.GameController.<StartupContinue>b__58_0(Object sender, FrameEventArgs args) in C:\Users\Wrexbe2\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 224
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\Wrexbe2\repos\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in C:\Users\Wrexbe2\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in C:\Users\Wrexbe2\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in C:\Users\Wrexbe2\repos\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 106
```
5. Client dies

**Comment by nikthechampiongr** [comment]
This appears to be caused by #25452.

**Comment by deltanedas** [comment]
also happens when doing forcemap; restartroundnow

**Comment by wrexbe** [comment]
I figured it out, trying to figure out how to prevent it from dieing now.
