### ISSUE TITLE
Client crash when restarting a round with the lobby enabled

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#2674]
- Get into the game
- cvar game.lobbyenabled true on the server console
- restartround on the server console
- Crash

```
[FATL] unhandled: Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=disposal pipe segment (5685, DisposalPipe), comp=Transform
 ---> Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 32
   at Robust.Shared.Map.MapGrid.SnapGridCellFor(EntityCoordinates coords, SnapGridOffset offset) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Map\MapGrid.cs:line 365
   at Robust.Shared.GameObjects.Components.Transform.SnapGridComponent.UpdatePosition() in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Transform\SnapGridComponent.cs:line 188
   at Robust.Shared.GameObjects.Systems.SnapGridSystem.OnMoveEvent(MoveEvent event) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SnapGridSystem.cs:line 18
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent[T](EventSource source, T eventArgs) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 312
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T toRaise) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 212
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Transform\TransformComponent.cs
:line 725
   at Robust.Client.GameObjects.ClientEntityManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityState curState, EntityState nextState) in E:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityManager.cs:line
287
```

**Comment by PJB3005** [comment]
See https://github.com/space-wizards/RobustToolbox/issues/1424
