### ISSUE TITLE
clicking rcd while mapping crashes client

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#27048]
## Description
title

**Comment by eoineoineoin** [comment]
Callstack:
```
Unhandled exception. Robust.Shared.Prototypes.UnknownPrototypeException: Unknown EntityPrototype prototype:
   at Robust.Shared.Prototypes.PrototypeManager.Index[T](String id) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Shared/Prototypes/PrototypeManager.cs:line 257
   at Robust.Client.Placement.PlacementManager.PreparePlacement(String templateName) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/Placement/PlacementManager.cs:line 692
   at Robust.Client.Placement.PlacementManager.BeginHijackedPlacing(PlacementInformation info, PlacementHijack hijack) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/Placement/PlacementManager.cs:line 496
   at Robust.Client.Placement.PlacementManager.BeginPlacing(PlacementInformation info, PlacementHijack hijack) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/Placement/PlacementManager.cs:line 467
   at Content.Client.RCD.RCDConstructionGhostSystem.Update(Single frameTime) in /home/eoin/code/space-station-14/Content.Client/RCD/RCDConstructionGhostSystem.cs:line 76
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 306
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 273
   at Robust.Client.GameObjects.ClientEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 194
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 459
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 552
   at Robust.Client.GameController.<StartupContinue>b__63_0(Object sender, FrameEventArgs args) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 243
   at Robust.Shared.Timing.GameLoop.Run() in /home/eoin/code/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass105_0.<Run>b__0() in /home/eoin/code/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106``
