### ISSUE TITLE
Alerts exception when uncuffing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#2744]
@chairbender 

Steps:
1. Cuff yourself via another client
2. Click on alert and get an exception on the server.

Stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Content.Server.GameObjects.Components.Mobs.ServerAlertsComponent.HandleNetworkMessage(ComponentMessage message, INetChannel netChannel, ICommonSession session) in D:\ProgrammingProjects\space-station-14\Content.Server\GameObjects\Components\Mobs\ServerAlertsComponent.cs:line 76
   at Robust.Shared.GameObjects.EntityManager.DispatchComponentMessage(NetworkComponentMessage netMsg) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 393
   at Robust.Shared.GameObjects.EntityManager.<Initialize>b__24_0(Object sender, NetworkComponentMessage compMsg) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 67
   at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 155
   at Robust.Server.GameObjects.ServerEntityNetworkManager.Update() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 57
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 90
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 963
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 554
   at Robust.Server.BaseServer.<MainLoop>b__44_1(Object sender, FrameEventArgs args) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 404
   at Robust.Shared.Timing.GameLoop.Run() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 195
   at Robust.Server.BaseServer.MainLoop() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 410
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 87
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 49
   at Robust.Server.Program.Main(String[] args) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 28
```

I forgot to get what was null but should be easy enough to debug...

**Comment by chairbender** [comment]
looking into it
