### ISSUE TITLE
exception in "DispatchEntityNetworkMessage(SystemMessage)"

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#28047]
reproduction:
1. Make urist with mind a zombie
2. Remove mind from first urist
3. Control second urist
4. Make second urist a zombie

https://github.com/space-wizards/space-station-14/assets/124214523/93ac0704-b1d7-4fcd-b6f4-e68cda4d4326

```[ERRO] runtime: Caught exception in "DispatchEntityNetworkMessage(SystemMessage)"
System.ArgumentException: We already have this role: Content.Server.Roles.ZombieRoleComponent
   at Content.Shared.Roles.SharedRoleSystem.MindAddRole[T](EntityUid mindId, T component, MindComponent mind, Boolean silent) in /home/lzk/Documents/GitHub/space-station-15/Content.Shared/Roles/SharedRoleSystem.cs:line 142
   at Content.Server.Zombies.ZombieSystem.ZombifyEntity(EntityUid target, MobStateComponent mobState) in /home/lzk/Documents/GitHub/space-station-15/Content.Server/Zombies/ZombieSystem.Transform.cs:line 239
   at Content.Server.Administration.Systems.AdminVerbSystem.<>c__DisplayClass7_0.<AddAntagVerbs>b__1() in /home/lzk/Documents/GitHub/space-station-15/Content.Server/Administration/Systems/AdminVerbSystem.Antags.cs:line 73
   at Content.Shared.Verbs.SharedVerbSystem.ExecuteVerb(Verb verb, EntityUid user, EntityUid target, Boolean forced) in /home/lzk/Documents/GitHub/space-station-15/Content.Shared/Verbs/SharedVerbSystem.cs:line 189
   at Content.Server.Verbs.VerbSystem.ExecuteVerb(Verb verb, EntityUid user, EntityUid target, Boolean forced) in /home/lzk/Documents/GitHub/space-station-15/Content.Server/Verbs/VerbSystem.cs:line 86
   at Content.Shared.Verbs.SharedVerbSystem.HandleExecuteVerb(ExecuteVerbEvent args, EntitySessionEventArgs eventArgs) in /home/lzk/Documents/GitHub/space-station-15/Content.Shared/Verbs/SharedVerbSystem.cs:line 46
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 46
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 253
```

**Comment by mqole** [comment]
probably fixed by https://github.com/space-wizards/space-station-14/pull/31318
