### ISSUE TITLE
Some loadouts are broken

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#28137]
just error in client popups, but all prototypes looks alright

1. click on loadout button
2. error

https://github.com/space-wizards/space-station-14/assets/124214523/b530f891-a4d0-4704-9b10-9721f84cce69
![Screenshot_20240519_110340](https://github.com/space-wizards/space-station-14/assets/124214523/d47b3f14-5fed-45ca-8158-7d254227fbd4)

text of one of them
```[ERRO] clyde.win: Error dispatching window event DEventKeyUp:
System.Collections.Generic.KeyNotFoundException: The given key 'Glasses' was not present in the dictionary.
   at Content.Client.Lobby.UI.Loadouts.LoadoutGroupContainer.RefreshLoadouts(HumanoidCharacterProfile profile, RoleLoadout loadout, ICommonSession session, IDependencyCollection collection) in /home/lzk/Documents/GitHub/space-station-15/Content.Client/Lobby/UI/Loadouts/LoadoutGroupContainer.xaml.cs:line 34
   at Content.Client.Lobby.UI.Loadouts.LoadoutWindow..ctor(HumanoidCharacterProfile profile, RoleLoadout loadout, RoleLoadoutPrototype proto, ICommonSession session, IDependencyCollection collection) in /home/lzk/Documents/GitHub/space-station-15/Content.Client/Lobby/UI/Loadouts/LoadoutWindow.xaml.cs:line 32
   at Content.Client.Lobby.UI.HumanoidProfileEditor.OpenLoadout(JobPrototype jobProto, RoleLoadout roleLoadout, RoleLoadoutPrototype roleLoadoutProto) in /home/lzk/Documents/GitHub/space-station-15/Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs:line 899
   at Content.Client.Lobby.UI.HumanoidProfileEditor.<>c__DisplayClass40_1.<RefreshJobs>b__3(ButtonEventArgs args) in /home/lzk/Documents/GitHub/space-station-15/Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs:line 873
   at Robust.Client.UserInterface.Controls.BaseButton.KeyBindUp(GUIBoundKeyEventArgs args) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/UserInterface/Controls/BaseButton.cs:line 278
   at Robust.Client.UserInterface.UserInterfaceManager.KeyBindUp(BoundKeyEventArgs args) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 129
   at Robust.Client.Input.InputManager.SetBindState(KeyBinding binding, BoundKeyState state, Boolean uiOnly, Boolean isRepeat) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Input/InputManager.cs:line 412
   at Robust.Client.Input.InputManager.KeyUp(KeyEventArgs args) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Input/InputManager.cs:line 326
   at Robust.Client.Graphics.Clyde.Clyde.DispatchSingleEvent(DEventBase ev) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 50
   at Robust.Client.Graphics.Clyde.Clyde.DispatchEvents() in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 31
```

**Comment by PotentiallyTom** [comment]
Happening for me too, The problem items are:
`SecurityBelt`
`Glasses`
`ScientistGloves`
`MedicalMask`

I can access the clown and passenger loadout, despite them having a glasses option. 

The roles not bugged are:
* Captain
* CE
* Det
* All 4 Intern Roles
* All of engineering
* Clown 
* Passenger
I can't access the loadout for any of the other roles.

**Comment by Ian321** [comment]
For me the following roles are bugged with the missing key:

- CE : StationEngineerBackpack
- CMO : MedicalBackpack
- QM : CargoTechnicianBackpack
- RD : ScientistBackpack
- Detective : SecurityBackpack
- Paramedic : MedicalBackpack

I noticed this after I late joined as a detective and spawned without a backpack (and its starting contents).

**Comment by Dutch-VanDerLinde** [comment]
> For me the following roles are bugged with the missing key:
> 
> * CE : StationEngineerBackpack
> * CMO : MedicalBackpack
> * QM : CargoTechnicianBackpack
> * RD : ScientistBackpack
> * Detective : SecurityBackpack
> * Paramedic : MedicalBackpack
> 
> I noticed this after I late joined as a detective and spawned without a backpack (and its starting contents).

redo your loadout to fix it

**Comment by lzk228** [comment]
looks like fixed now
