### ISSUE TITLE
Corn throws an error when growing to stage-6

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#28254]
## Description

```
[ERRO] go.comp.sprite: State 'stage-6' does not exist in set RSI (/Textures/Objects/Specific/Hydroponics/corn.rsi). Trace:
   at System.Environment.get_StackTrace()
   at Robust.Client.GameObjects.SpriteComponent.Layer.SetRsi(RSI rsi) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs:line 1832
   at Robust.Client.GameObjects.SpriteComponent.LayerSetRSI(Int32 layer, ResPath rsiPath) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs:line 1061
   at Content.Client.Botany.PlantHolderVisualizerSystem.OnAppearanceChange(EntityUid uid, PlantHolderVisualsComponent component, AppearanceChangeEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Client/Botany/PlantHolderVisualizerSystem.cs:line 26
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 47
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 40
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 198
   at Robust.Client.GameObjects.AppearanceSystem.FrameUpdate(Single frameTime) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/EntitySystems/AppearanceSystem.cs:line 120
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 333
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 595
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106
   at System.Threading.Thread.StartCallback()
```

**Reproduction**
]

- Put corn seeds in hydroponics tray
- Wait for corn to grow
- Error pops up in console

**Comment by Lamrr** [comment]
Cannot reproduce locally - no error is made while growing corn. Was it a special type of corn?

**Comment by Tayrtahn** [comment]
Huh. The corn seed prototype is set to 3 growth stages, so it definitely shouldn't be getting to 6.

It might have something to do with 6 being the default number of growth stages for a seed prototype?

**Comment by ShadowCommander** [comment]
I'm not able to reproduce it on local either with default corn. This was on Lizard. I was growing some corn and the other two botanists were growing one corn. Mine were regular seeds. I'm not sure what they were doing.

**Comment by beck-thompson** [comment]
I've gotten a very similar error in Delta. I tried to reproduce it as well and got nowhere...
![Screenshot 2024-07-17 095421](https://github.com/user-attachments/assets/cc340e07-728e-4105-9deb-f161dcf340ea)

**Comment by Pok27** [comment]
This was fixed in botany refactor #44576 (or earlier)
