### ISSUE TITLE
Barber scissors Nullable object

### ISSUE THREAD

**Issue by Morb0** [space-wizards/space-station-14#28360]
## Description

Barber scissors can be used on any entity (already invalid behavior), and when misused cause nullable error spam.

**Reproduction**

1. Spawn scissors
2. Use on any entity (even on wall)
3. PROFIT

**Screenshots**

**Additional context**

```
[ERRO] runtime: Caught exception in "entsys"
System.InvalidOperationException: Nullable object must have a value.
   at Content.Shared.MagicMirror.SharedMagicMirrorSystem.OnMirrorRangeCheck(EntityUid uid, MagicMirrorComponent component, BoundUserInterfaceCheckRangeEvent& args) in D:\Development\space-station-14\Content.Shared\MagicMirror\SharedMagicMirrorSystem.cs:line 37
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in D:\Development\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 596
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in D:\Development\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 198
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.CheckRange(Entity`1 UiEnt, Enum key, InterfaceData data, Entity`1 actor) in D:\Development\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedUserInterfaceSystem.cs:line 967
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.Update(Single frameTime) in D:\Development\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedUserInterfaceSystem.cs:line 912
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in D:\Development\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 306
   ```

**Comment by EmoGarbage404** [comment]
Is this on latest version since I thought this got patched a day or two ago

**Comment by Morb0** [comment]
> Is this on latest version since I thought this got patched a day or two ago

Okay, yeah, seems in last upstream was fixed
