### ISSUE TITLE
Exception when using the mapping command 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#2839]
It seems to execute just fine anyways, but its worth reporting
```
[WARN] con: localhost@JoeGenero: ExecuteError - mapping 2 Maps/saltern.yml:
System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
   at System.Linq.CachingComparer`2.Compare(TElement element, Boolean cacheLower)
   at System.Linq.OrderedEnumerable`1.TryGetFirst(Boolean& found)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Content.Server.Commands.GameTicking.MappingCommand.Execute(IConsoleShell shell, IPlayerSession player, String[] args) in /home/maharba/Save/3-Programas/Git/Desarrollo/SS14/space-station-14/Content.Server/Commands/GameTicking/MappingCommand.cs:line 64
   at Robust.Server.Console.ConsoleShell.ExecuteCommand(IPlayerSession session, String command) in /home/maharba/Save/3-Programas/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/Console/ConsoleShell.cs:line 121
```

**Comment by SweptWasTaken** [comment]
Can't replicate anymore.
