### ISSUE TITLE
Breaking destructible entities which drop items crashes the server

### ISSUE THREAD

**Issue by cyclowns** [space-wizards/space-station-14#2850]
```
System.InvalidOperationException
  HResult=0x80131509
  Mensaje = Tried to spawn entity ShardGlassReinforced on invalid coordinates EntId=1443, X=0.00, Y=0.00.
  Origen = Robust.Server
  Seguimiento de la pila:
   at Robust.Server.GameObjects.ServerEntityManager.SpawnEntity(String protoName, EntityCoordinates coordinates) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 120
   at Content.Server.GameObjects.Components.Destructible.Thresholds.Behavior.SpawnEntitiesBehavior.Trigger(IEntity owner, DestructibleSystem system) in C:\Users\DarkM\repos\space-station-14\Content.Server\GameObjects\Components\Destructible\Thresholds\Behavior\SpawnEntitiesBehavior.cs:line 44
   at Content.Server.GameObjects.Components.Destructible.Thresholds.Threshold.Trigger(IEntity owner, DestructibleSystem system) in C:\Users\DarkM\repos\space-station-14\Content.Server\GameObjects\Components\Destructible\Thresholds\Threshold.cs:line 53
   at Content.Server.GameObjects.Components.Destructible.DestructibleComponent.HandleMessage(ComponentMessage message, IComponent component) in C:\Users\DarkM\repos\space-station-14\Content.Server\GameObjects\Components\Destructible\DestructibleComponent.cs:line 83
   at Robust.Shared.GameObjects.Entity.SendMessage(IComponent owner, ComponentMessage message) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 220
   at Robust.Shared.GameObjects.Component.SendMessage(ComponentMessage message) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Component.cs:line 186
   at Content.Shared.GameObjects.Components.Damage.DamageableComponent.OnHealthChanged(DamageChangedEventArgs e) in C:\Users\DarkM\repos\space-station-14\Content.Shared\GameObjects\Components\Damage\DamageableComponent.cs:line 466
   at Content.Shared.GameObjects.Components.Damage.DamageableComponent.OnHealthChanged(List`1 changes) in C:\Users\DarkM\repos\space-station-14\Content.Shared\GameObjects\Components\Damage\DamageableComponent.cs:line 457
   at Content.Shared.GameObjects.Components.Damage.DamageableComponent.ChangeDamage(DamageType type, Int32 amount, Boolean ignoreResistances, IEntity source, DamageChangeParams extraParams) in C:\Users\DarkM\repos\space-station-14\Content.Shared\GameObjects\Components\Damage\DamageableComponent.cs:line 321
   at Content.Server.GameObjects.Components.Projectiles.ThrownItemComponent.Robust.Shared.GameObjects.Components.ICollideBehavior.CollideWith(IEntity entity) in C:\Users\DarkM\repos\space-station-14\Content.Server\GameObjects\Components\Projectiles\ThrownItemComponent.cs:line 49
   at Robust.Shared.GameObjects.Systems.SharedPhysicsSystem.ProcessCollisions(IEnumerable`1 awakeBodies) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line 278
   at Robust.Shared.GameObjects.Systems.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line 154
   at Robust.Server.GameObjects.EntitySystems.PhysicsSystem.Update(Single frameTime) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySystems\PhysicsSystem.cs:line 14
   at Robust.Shared.GameObjects.EntitySystemManager.Update(Single frameTime) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 261
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 95
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 963
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 554
   at Robust.Server.BaseServer.<MainLoop>b__44_1(Object sender, FrameEventArgs args) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 404
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 195
   at Robust.Server.BaseServer.MainLoop() in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 410
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 87
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in C:\Users\DarkM\repos\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```
tested with breaking windows, tables, and wires

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/space-station-14/issues/2827
