### ISSUE TITLE
When firing a revolver that has been reloaded, an error occurs in the Client

### ISSUE THREAD

**Issue by MetalSage** [space-wizards/space-station-14#28587]
## Description

If you unload the revolver, load and fire it, you get a Client Error, which is Fatal in Debug mode

**Reproduction**

- Get any revolver any way you want
- Unload a revolver
- Load a revolver
- Fire the revolver by opening the Client's console.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/74924875/a9fa7b60-c18b-4149-aee4-87d34f2aa1d7)

**Additional context**

Full Error:
```
[ERRO] root: Predicting the queued deletion of a networked entity: cartridge (.45 magnum) (11402/n74278, CartridgeMagnum). Trace:    at System.Environment.get_StackTrace()
   at Robust.Client.GameObjects.ClientEntityManager.QueueDeleteEntity(Nullable`1 uid) in D:\Git\Wizard\RobustToolbox\Robust.Client\GameObjects\ClientEntityManager.cs:line 85
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnRevolverTakeAmmo(EntityUid uid, RevolverAmmoProviderComponent component, TakeAmmoEvent args) in D:\Git\Wizard\Content.Shared\Weapons\Ranged\Systems\SharedGunSystem.Revolver.cs:line 407
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in D:\Git\Wizard\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 596
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in D:\Git\Wizard\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 180
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.AttemptShoot(EntityUid user, EntityUid gunUid, GunComponent gun) in D:\Git\Wizard\Content.Shared\Weapons\Ranged\Systems\SharedGunSystem.cs:line 315
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnShootRequest(RequestShootEvent msg, EntitySessionEventArgs args) in D:\Git\Wizard\Content.Shared\Weapons\Ranged\Systems\SharedGunSystem.cs:line 141
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in D:\Git\Wizard\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in D:\Git\Wizard\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in D:\Git\Wizard\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 267
   at Robust.Client.GameStates.ClientGameStateManager.PredictTicks(GameTick predictionTarget) in D:\Git\Wizard\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 510
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in D:\Git\Wizard\RobustToolbox\Robust.Client\GameStates\ClientGameStateManager.cs:line 454
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in D:\Git\Wizard\RobustToolbox\Robust.Client\GameController\GameController.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in D:\Git\Wizard\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in D:\Git\Wizard\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in D:\Git\Wizard\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in D:\Git\Wizard\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 106
```

**Comment by beck-thompson** [comment]
Replicated
