### ISSUE TITLE
PrayerSystem throws null exceptions

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#28698]
From grafana:
```
Caught exception in DispatchEntityNetworkMessage(SystemMessage)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Content.Server.Prayer.PrayerSystem.Pray(ICommonSession sender, PrayableComponent comp, String message) in /home/runner/work/space-station-14/space-station-14/Content.Server/Prayer/PrayerSystem.cs:line 100
   at Content.Server.Prayer.PrayerSystem.<>c__DisplayClass5_0.<AddPrayVerb>b__1(String message) in /home/runner/work/space-station-14/space-station-14/Content.Server/Prayer/PrayerSystem.cs:line 59
   at Content.Server.Administration.QuickDialogSystem.<>c__DisplayClass12_0`1.<OpenDialog>b__0(QuickDialogResponseEvent ev) in /home/runner/work/space-station-14/space-station-14/Content.Server/Administration/QuickDialogSystem.OpenDialog.cs:line 33
   at Content.Server.Administration.QuickDialogSystem.Handler(QuickDialogResponseEvent msg, EntitySessionEventArgs args) in /home/runner/work/space-station-14/space-station-14/Content.Server/Administration/QuickDialogSystem.cs:line 50
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 46
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 253
 Catcher=DispatchEntityNetworkMessage(SystemMessage) Sawmill=runtime
```

**Comment by Tayrtahn** [comment]
Replicated.

Steps:
- Spawn red phone or other Prayable.
- Use Pray verb to open quick dialog window, and keep it open.
- Die, ghost, or otherwise change the entity you're controlling.
- Send the prayer message.
