### ISSUE TITLE
SpawnAndDeleteAllEntitiesOnDifferentMaps fails randomly

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#28908]
## Description

https://github.com/space-wizards/space-station-14/actions/runs/9487364711/job/26143813102

```
Failed SpawnAndDeleteAllEntitiesOnDifferentMaps [17 s]
  Error Message:
   Robust.Shared.Utility.DebugAssertException : Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.

  1) Test was dirty-disposed.

  Stack Trace:
     at Content.Server.Atmos.Piping.EntitySystems.AtmosDeviceSystem.Update(Single frameTime) in /home/runner/work/space-station-14/space-station-14/Content.Server/Atmos/Piping/EntitySystems/AtmosDeviceSystem.cs:line 124
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 252
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 195
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 702
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.SingleThreadRunUntilEmpty() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1097
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.Run() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1084
   at Robust.UnitTesting.RobustIntegrationTest.ServerIntegrationInstance._serverMain() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 655
```

**Reproduction**

Test history:
```
 - Pair 4 Test #0: Chemistry.ReagentDataTest.ReagentDataIsSerializable
 - Pair 4 Test #1: ClickableTest.Test("ClickTestRotatingCornerVisible",0.25f,0.25f,0.0d,1)
 - Pair 4 Test #2: ClickableTest.Test("ClickTestRotatingCornerVisible",0.35f,0.5f,0.0d,2)
 - Pair 4 Test #3: ClickableTest.Test("ClickTestRotatingCornerVisible",-0.25f,-0.25f,0.0d,1)
 - Pair 4 Test #4: ClickableTest.Test("ClickTestRotatingCornerVisible",0.25f,0.25f,3.141592653589793d,1)
 - Pair 4 Test #5: ClickableTest.Test("ClickTestRotatingCornerVisible",-0.25f,-0.25f,3.141592653589793d,1)
 - Pair 4 Test #6: ClickableTest.Test("ClickTestRotatingCornerVisible",-0.25f,0.25f,1.5707963267948966d,1)
 - Pair 4 Test #7: ClickableTest.Test("ClickTestRotatingCornerVisible",0,0.25f,0.7853981633974483d,1)
 - Pair 4 Test #8: ClickableTest.Test("ClickTestRotatingCornerVisibleNoRot",0.25f,0.25f,0.0d,1)
 - Pair 4 Test #9: ClickableTest.Test("ClickTestRotatingCornerVisibleNoRot",-0.25f,-0.25f,0.0d,1)
 - Pair 4 Test #10: ClickableTest.Test("ClickTestRotatingCornerVisibleNoRot",0.25f,0.25f,3.141592653589793d,1)
 - Pair 4 Test #11: ClickableTest.Test("ClickTestRotatingCornerVisibleNoRot",-0.25f,-0.25f,3.141592653589793d,1)
 - Pair 4 Test #12: ClickableTest.Test("ClickTestRotatingCornerVisibleNoRot",0,0.35f,0.6853981633974483d,1)
 - Pair 4 Test #13: ClickableTest.Test("ClickTestRotatingCornerVisibleNoRot",0.25f,0.25f,0.6853981633974483d,1)
 - Pair 4 Test #14: ClickableTest.Test("ClickTestRotatingCornerInvisible",0.25f,0.25f,0.0d,1)
 - Pair 4 Test #15: ClickableTest.Test("ClickTestRotatingCornerInvisible",0.35f,0.5f,0.0d,2)
 - Pair 4 Test #16: ClickableTest.Test("ClickTestRotatingCornerInvisible",0.25f,0.25f,3.141592653589793d,1)
 - Pair 4 Test #17: Commands.PardonCommand.PardonTest
 - Pair 4 Test #18: ClickableTest.Test("ClickTestRotatingCornerInvisibleNoRot",0.25f,0.25f,3.141592653589793d,1)
 - Pair 4 Test #19: ClickableTest.Test("ClickTestRotatingCornerInvisibleNoRot",0.25f,0.25f,0.6853981633974483d,1)
 - Pair 4 Test #20: Commands.RestartRoundNowTest.RestartRoundAfterStart(False)
 - Pair 4 Test #21: Construction.ConstructionActionValid.ConstructionGraphEdgeValid
 - Pair 4 Test #22: Construction.ConstructionPrototypeTest.DeconstructionIsValid
 - Pair 4 Test #23: Construction.ConstructionPrototypeTest.TestStartNodeValid
 - Pair 4 Test #24: Construction.Interaction.PanelScrewing.WiresPanelScrewing("TelecomServerFilled")
 - Pair 4 Test #25: Construction.Interaction.WindowConstruction.DeconstructWindow
 - Pair 4 Test #26: Construction.Interaction.WindowRepair.RepairReinforcedWindow
 - Pair 4 Test #27: DoAfter.DoAfterCancellationTests.CancelTilePry
 - Pair 4 Test #28: DoAfter.DoAfterCancellationTests.CancelWallDeconstruct
 - Pair 4 Test #29: EncryptionKeys.RemoveEncryptionKeys.HeadsetKeys
 ```

**Comment by Tayrtahn** [comment]
Thanks for finally adding this as an issue. Let's get this sucker fixed.

**Comment by Tayrtahn** [comment]
Gonna log more instances here:

- https://github.com/space-wizards/space-station-14/actions/runs/9550080539/job/26321206611
