### ISSUE TITLE
Server crash when throwing glasses at normal windows precisely

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#2931]
This seems like a pretty big deal
State of client before server crash:
![image](https://user-images.githubusercontent.com/19853115/103739130-67d94f80-4fb2-11eb-9695-a60f3f46ffb4.png)
Doctor's Delight is the glass I threw, you can see it kind of hit the seam between the wall and window. Throwing it at the windows worked normally, and throwing it at the wall itself worked normally, but right there broke it

Other notes:
- Tested with other drinks, behaves the same
- Occurs with both admin-spawned drinks (like above) and drinks obtained from the bar
- Happens when throwing in any direction, not just up/down
- Only appears to happen between the seams between windows and other objects
- **Only works with regular windows and not r-windows????**
- Sometimes doesn't work. The spot that it crashes on is pretty precise

<details><summary>Exception details</summary>
<p>

```
Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 47
   at Robust.Shared.GameObjects.Entity.TryGetComponent[T](T& component) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 296
   at Content.Server.GameObjects.Components.Projectiles.ThrownItemComponent.Robust.Shared.GameObjects.Components.ICollideBehavior.CollideWith(IEntity entity) in K:\github.com\cyclowns\space-station-14\Content.Server\GameObjects\Components\Projectiles\ThrownItemComponent.cs:line 48
   at Robust.Shared.GameObjects.Systems.SharedPhysicsSystem.ProcessCollisions(IEnumerable`1 awakeBodies) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line 278
   at Robust.Shared.GameObjects.Systems.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line 154
   at Robust.Server.GameObjects.EntitySystems.PhysicsSystem.Update(Single frameTime) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySystems\PhysicsSystem.cs:line 14
   at Robust.Shared.GameObjects.EntitySystemManager.Update(Single frameTime) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 261
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 95
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 963
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 554
   at Robust.Server.BaseServer.<MainLoop>b__44_1(Object sender, FrameEventArgs args) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 404
   at Robust.Shared.Timing.GameLoop.Run() in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 195
   at Robust.Server.BaseServer.MainLoop() in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 410
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 87
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 49
   at Robust.Server.ContentStart.Start(String[] args) in K:\github.com\cyclowns\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in K:\github.com\cyclowns\space-station-14\Content.Server\Program.cs:line 9
```

</p>
</details>

**Comment by SweptWasTaken** [comment]
🤔 

Line 48 of ThrownItemComponent.cs
```csharp
            if (entity.TryGetComponent(out IDamageableComponent damage))
            {
                damage.ChangeDamage(DamageType.Blunt, 10, false, Owner);
            }
```

Maybe it's just a physics bug with trying to damage two collidable entities at the same time?

**Comment by PaulRitter** [comment]
ok my theory is: the shard gets stuck inbetween the wall & the window, kinda jiggling at causing damage. imo this should be an `Owner.IsDeleted` check in the collidewith.

**Comment by mirrorcult** [comment]
> 
> 
> ok my theory is: the shard gets stuck inbetween the wall & the window, kinda jiggling at causing damage. imo this should be an `if(Owner.IsDeleted) return;` check in the collidewith.

tested, doesn't fix the issue

**Comment by PaulRitter** [comment]
> 
> 
> > ok my theory is: the shard gets stuck inbetween the wall & the window, kinda jiggling at causing damage. imo this should be an `if(Owner.IsDeleted) return;` check in the collidewith.
> 
> tested, doesn't fix the issue

can you provide me with the branch you tried to fix this on?

**Comment by metalgearsloth** [comment]
ThrowCollideInteraction is deleting it so you should just add the check after as a quick fix.

```
if (entity.TryGetComponent(out PhysicsComponent collid))
{
    if (!collid.Hard) // ignore non hard
        return;

    _shouldStop = true; // hit something hard => stop after this collision

    // Raise an event.
    EntitySystem.Get<InteractionSystem>().ThrowCollideInteraction(User, Owner, entity, Owner.Transform.Coordinates);
}
```

The ideal solution is removing the damage part and handle under an IThrowCollide implementation.

**Comment by metalgearsloth** [comment]
Pretty sure this is fixed
