### ISSUE TITLE
Drains, Toilets, and Sinks prohibit a grid from saving.

### ISSUE THREAD

**Issue by Scruq445** [space-wizards/space-station-14#29755]
I was making a shuttle and tried to save it when it gave me an error for DrainComponent and SolutionRegenerationComponent and found out it was because of the placed drains, toilets, and sinks.

![Screenshot_20240705_184638](https://github.com/space-wizards/space-station-14/assets/109207982/6c486c85-7622-4aee-84af-5e109bfeb6d0)

```[INFO] con: Scruq:savegrid 9998 /SavedShips/ATSTest 
[ERRO] map: Encountered an invalid entityUid '12' while serializing a map.
[ERRO] con: Scruq: ExecuteError - savegrid 9998 /SavedShips/ATSTest :
System.InvalidOperationException: No data definition found for type Robust.Shared.GameObjects.Entity`1[Content.Shared.Chemistry.Components.SolutionComponent] when writing
   at Robust.Shared.Serialization.Manager.SerializationManager.WriteValueInternal[T](T value, DataDefinition`1 definition, Boolean alwaysWrite, ISerializationContext context) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Serialization/Manager/SerializationManager.Writing.cs:line 246
   at lambda_method22695(Closure, Nullable`1, Boolean, ISerializationContext)
   at lambda_method10979(Closure, DrainComponent, ISerializationContext, Boolean)
   at lambda_method22689(Closure, DrainComponent, Boolean, ISerializationContext)
   at Robust.Shared.Serialization.Manager.SerializationManagerWriteExtensions.WriteValueAs[T](ISerializationManager manager, Type type, Object value, Boolean alwaysWrite, ISerializationContext context) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Serialization/Manager/SerializationManagerWriteExtensions.cs:line 26
   at Robust.Server.GameObjects.MapLoaderSystem.WriteEntitySection(MappingDataNode rootNode, Dictionary`2 uidEntityMap, Dictionary`2 entityUidMap) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/MapLoaderSystem.cs:line 1250
   at Robust.Server.GameObjects.MapLoaderSystem.GetSaveData(EntityUid uid) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/MapLoaderSystem.cs:line 968
   at Robust.Server.GameObjects.MapLoaderSystem.Save(EntityUid uid, String ymlPath) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/MapLoaderSystem.cs:line 204
   at Robust.Server.Console.Commands.SaveGridCommand.Execute(IConsoleShell shell, String argStr, String[] args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Console/Commands/MapCommands.cs:line 45
   at Robust.Server.Console.ServerConsoleHost.ExecuteInShell(IConsoleShell shell, String command) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Console/ServerConsoleHost.cs:line 126
```

**Comment by beck-thompson** [comment]
Bro I swear toilets have caused so many bugs its ridiculous

**Comment by Tayrtahn** [comment]
This is due to the cached `Entity<SolutionComponent>` on these components being marked as a DataField. Components (and by extension Entity<TComp>s) cannot and should not be serialized.

The fields are fine to keep for optimization, but they need to have the DataField attribute removed.
