### ISSUE TITLE
Exception in BlockGameArcadeComponent.DeactivePlayer

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#2986]
```
Caught exception while dispatching SystemMessage: System.ArgumentException: Player session does not have this UI open.
   at Robust.Server.GameObjects.BoundUserInterface.AssertContains(IPlayerSession session) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/Components/UserInterface/ServerUserInterfaceComponent.cs:line 348
   at Robust.Server.GameObjects.BoundUserInterface.SendMessage(BoundUserInterfaceMessage message, IPlayerSession session) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/Components/UserInterface/ServerUserInterfaceComponent.cs:line 314
   at Content.Server.Arcade.Components.BlockGameArcadeComponent.DeactivePlayer(IPlayerSession session) in /home/runner/work/space-station-14/space-station-14/Content.Server/Arcade/Components/BlockGameArcadeComponent.cs:line 81
   at Robust.Server.GameObjects.BoundUserInterface.CloseShared(IPlayerSession session) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/Components/UserInterface/ServerUserInterfaceComponent.cs:line 262
   at Robust.Server.GameObjects.ServerUserInterfaceComponent.ReceiveMessage(IPlayerSession session, BoundUIWrapMessage msg) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/Components/UserInterface/ServerUserInterfaceComponent.cs:line 85
   at Robust.Server.GameObjects.UserInterfaceSystem.OnMessageReceived(BoundUIWrapMessage msg, EntitySessionEventArgs args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/UserInterfaceSystem.cs:line 63
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 47
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 376
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 283
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 325
```

**Comment by Morb0** [comment]
Reproduced error by opening the NT block arcade window and trying to open second one without closing the first one.
