### ISSUE TITLE
canceling spawn with right-click causes a client exception

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#30162]
1. choose spawn something
2. right clickk
3. 
```
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Robust.Client.UserInterface.UserInterfaceManager.KeyBindDown(BoundKeyEventArgs args) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 118
   at Robust.Client.UserInterface.UserInterfaceManager.OnUIKeyBindStateChanged(BoundKeyEventArgs args) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 453
   at Robust.Client.Input.InputManager.SetBindState(KeyBinding binding, BoundKeyState state, Boolean uiOnly, Boolean isRepeat) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Input/InputManager.cs:line 412
   at Robust.Client.Input.InputManager.DownBind(KeyBinding binding, Boolean uiOnly, Boolean isRepeat) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Input/InputManager.cs:line 362
   at Robust.Client.Input.InputManager.KeyDown(KeyEventArgs args) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Input/InputManager.cs:line 283
   at Robust.Client.GameController.KeyDown(KeyEventArgs keyEvent) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/GameController/GameController.Input.cs:line 12
   at Robust.Client.Graphics.Clyde.Clyde.DispatchSingleEvent(DEventBase ev) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 47
   at Robust.Client.Graphics.Clyde.Clyde.DispatchEvents() in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 31
   at Robust.Client.Graphics.Clyde.Clyde.ProcessInput(FrameEventArgs frameEventArgs) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Windowing.cs:line 392
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/GameController/GameController.cs:line 489
   at Robust.Client.GameController.<StartupContinue>b__58_2(Object sender, FrameEventArgs args) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/GameController/GameController.cs:line 240
   at Robust.Shared.Timing.GameLoop.Run() in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 187
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in /home/lzk/Documents/GitHub/space-station-15/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106
Aborted (core dumped)
```

**Comment by IProduceWidgets** [comment]
@metalgearsloth There's dozens of us! Dozens!
