### ISSUE TITLE
Microwave construction is broken

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#30231]
## Description
Constructing a microwave will cause the following exception:
```
Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in Content.Server.dll: 'Object reference not set to an instance of an object.'
   at Content.Server.Kitchen.EntitySystems.MicrowaveSystem.OnInsertAttempt(Entity`1 ent, ContainerIsInsertingAttemptEvent& args) in D:\Code\SS14\space-station-14\Content.Server\Kitchen\EntitySystems\MicrowaveSystem.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 634
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 240
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 159
   at Robust.Shared.Containers.SharedContainerSystem.CanInsert(EntityUid toInsert, BaseContainer container, Boolean assumeEmpty, TransformComponent containerXform) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\Containers\SharedContainerSystem.Insert.cs:line 186
   at Robust.Shared.Containers.SharedContainerSystem.Insert(Entity`3 toInsert, BaseContainer container, TransformComponent containerXform, Boolean force) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\Containers\SharedContainerSystem.Insert.cs:line 65
   at Content.Server.Construction.ConstructionSystem.ChangeEntity(EntityUid uid, Nullable`1 userUid, String newEntity, ConstructionComponent construction, MetaDataComponent metaData, TransformComponent transform, ContainerManagerComponent containerManager) in D:\Code\SS14\space-station-14\Content.Server\Construction\ConstructionSystem.Graph.cs:line 392
   at Content.Server.Construction.ConstructionSystem.ChangeNode(EntityUid uid, Nullable`1 userUid, String id, Boolean performActions, ConstructionComponent construction) in D:\Code\SS14\space-station-14\Content.Server\Construction\ConstructionSystem.Graph.cs:line 260
   at Content.Server.Construction.ConstructionSystem.HandleEdge(EntityUid uid, Object ev, ConstructionGraphEdge edge, Boolean validation, ConstructionComponent construction) in D:\Code\SS14\space-station-14\Content.Server\Construction\ConstructionSystem.Interactions.cs:line 180
   at Content.Server.Construction.ConstructionSystem.HandleEvent(EntityUid uid, Object ev, Boolean validation, ConstructionComponent construction) in D:\Code\SS14\space-station-14\Content.Server\Construction\ConstructionSystem.Interactions.cs:line 67
   at Content.Server.Construction.ConstructionSystem.UpdateInteractions() in D:\Code\SS14\space-station-14\Content.Server\Construction\ConstructionSystem.Interactions.cs:line 522
   at Content.Server.Construction.ConstructionSystem.Update(Single frameTime) in D:\Code\SS14\space-station-14\Content.Server\Construction\ConstructionSystem.cs:line 91
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 306
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 256
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 195
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 729
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 542
   at Robust.Shared.Timing.GameLoop.Run() in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 569
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in D:\Code\SS14\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in D:\Code\SS14\space-station-14\Content.Server\Program.cs:line 9
```

**Reproduction**
- Spawn microwave machine bord
- Construct a machine frame
- follow the construction steps
- game will crash upon using the screwdriver

**Additional context**
Likely caused by #29200

I assume it tries to insert the screwdriver immediately after construction, but the MicrowaveComponent is not fully intialized yet and the Storage is still null.

**Comment by slarticodefast** [comment]
Update: It is not the screwdriver that is inserted but the microwave machine board and machine parts that is inserted into the "machineboard" and "machine_parts" containers. I'll make a quick PR to fix it.
