### ISSUE TITLE
fatal error access secure windor

### ISSUE THREAD

**Issue by krevetkqqq** [space-wizards/space-station-14#31307]
## Description

when i use from aghost backpack access configurator on secure windor server crashes

**Reproduction**

- aghost in console
- f5 - secure windoor
- from backpack acces configurator
- from pda card into access configurator
- try change access

**Screenshots**

**Additional context**

console log:
`[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Entity 2564 is not the owner of the component. Component: AccessReaderComponent
   at Robust.Shared.Utility.DebugTools.AssertOwner(Nullable`1 uid, IComponent component) in C:\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 178
   at Robust.Shared.GameObjects.EntityManager.Dirty(EntityUid uid, IComponent component, MetaDataComponent meta) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 380
   at Content.Server.Access.Systems.AccessOverriderSystem.TryWriteToTargetAccessReaderId(EntityUid uid, List`1 newAccessList, EntityUid player, AccessOverriderComponent component) in C:\space-station-14\Content.Server\Access\Systems\AccessOverriderSystem.cs:line 248
   at Content.Server.Access.Systems.AccessOverriderSystem.OnWriteToTargetAccessReaderIdMessage(EntityUid uid, AccessOverriderComponent component, WriteToTargetAccessReaderIdMessage args) in C:\space-station-14\Content.Server\Access\Systems\AccessOverriderSystem.cs:line 96
   at Robust.Shared.GameObjects.BoundUserInterfaceRegisterExt.Subscriber`1.<>c__DisplayClass3_0`1.<Event>b__0(EntityUid uid, TComp component, TEvent args) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\UserInterface\BoundUserInterfaceRegisterExt.cs:line 70
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 634
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 240
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent(EntityUid uid, Object args, Boolean broadcast) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 209
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent(EntityUid uid, Object args, Boolean broadcast) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 164
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.OnMessageReceived(BoundUIWrapMessage msg, EntityUid sender) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedUserInterfaceSystem.cs:line 126
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.<Initialize>b__14_0(BoundUIWrapMessage msg, EntitySessionEventArgs args) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedUserInterfaceSystem.cs:line 59
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in C:\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in C:\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 265
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 191
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 729
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in C:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 542
   at Robust.Shared.Timing.GameLoop.Run() in C:\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in C:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 569
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in C:\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\space-station-14\Content.Server\Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Entity 2564 is not the owner of the component. Component: AccessReaderComponent
   at Robust.Shared.Utility.DebugTools.AssertOwner(Nullable`1 uid, IComponent component) in C:\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 178
   at Robust.Shared.GameObjects.EntityManager.Dirty(EntityUid uid, IComponent component, MetaDataComponent meta) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 380
   at Content.Server.Access.Systems.AccessOverriderSystem.TryWriteToTargetAccessReaderId(EntityUid uid, List`1 newAccessList, EntityUid player, AccessOverriderComponent component) in C:\space-station-14\Content.Server\Access\Systems\AccessOverriderSystem.cs:line 248
   at Content.Server.Access.Systems.AccessOverriderSystem.OnWriteToTargetAccessReaderIdMessage(EntityUid uid, AccessOverriderComponent component, WriteToTargetAccessReaderIdMessage args) in C:\space-station-14\Content.Server\Access\Systems\AccessOverriderSystem.cs:line 96
   at Robust.Shared.GameObjects.BoundUserInterfaceRegisterExt.Subscriber`1.<>c__DisplayClass3_0`1.<Event>b__0(EntityUid uid, TComp component, TEvent args) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\UserInterface\BoundUserInterfaceRegisterExt.cs:line 70
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 634
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 240
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent(EntityUid uid, Object args, Boolean broadcast) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 209
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent(EntityUid uid, Object args, Boolean broadcast) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 164
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.OnMessageReceived(BoundUIWrapMessage msg, EntityUid sender) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedUserInterfaceSystem.cs:line 126
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.<Initialize>b__14_0(BoundUIWrapMessage msg, EntitySessionEventArgs args) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedUserInterfaceSystem.cs:line 59
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in C:\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in C:\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 265
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 191
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 729
   at Robust.Server.BaseServer.<SetupMainLoop>b__66_1(Object sender, FrameEventArgs args) in C:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 542
   at Robust.Shared.Timing.GameLoop.Run() in C:\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in C:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 569
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in C:\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\space-station-14\Content.Server\Program.cs:line 9`

**Comment by ilyasassiks** [comment]
https://www.youtube.com/watch?v=mxcVXzQg6VM

**Comment by Killerqu00** [comment]
Hi! I couldn't replicate that issue, is this still relevant?

**Comment by krevetkqqq** [comment]
> Hi! I couldn't replicate that issue, is this still relevant?

heya. i don't really know, it's old topic. trouble was, that any change of access everywhere is crashing. if that's doesn't work, that is fixed
