### ISSUE TITLE
right clicking while placing decals crashes client

### ISSUE THREAD

**Issue by Moomoobeef** [space-wizards/space-station-14#31904]
## Description
If you right click while placing decals the client will crash. Old behavior was just that it would stop placing decals, and I used this frequently to exit decal mode.

**Reproduction**
1. Open Decals UI
2. start placing decals
3. right click to stop placing decals
4. client crashes
5. cry

**Screenshots**

**Additional context**
I had the palette open and was placing the colored half-tile decals. This happened on both debug (which isn't surprising) and tools configuration.
I am running the game on manjaro linux.

**Comment by bruhmogus** [comment]
isn't right clicking with decals just supposed to remove the decals in that area?

**Comment by Moomoobeef** [comment]
> isn't right clicking with decals just supposed to remove the decals in that area?

Oh yea you're right. I forgot (I haven't done any decalling in a couple months)
Still though, that's a pretty big problem if you cannot remove decals...

**Comment by Emisse** [comment]
I cannot replicate this, can you give more details

**Comment by lzk228** [comment]
well it's actually a dupe of https://github.com/space-wizards/space-station-14/issues/30162
happens on debug build and crash caused by exception

**Comment by deltanedas** [comment]
its a meme debug assert in control handling code i think

**Comment by Moomoobeef** [comment]
> I cannot replicate this, can you give more details

it happens on the debug build, I get the following exception
```
Exception has occurred: CLR/Robust.Shared.Utility.DebugAssertException
An unhandled exception of type 'Robust.Shared.Utility.DebugAssertException' occurred in Robust.Shared.dll
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Robust.Client.UserInterface.UserInterfaceManager.KeyBindDown(BoundKeyEventArgs args) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 118
   at Robust.Client.UserInterface.UserInterfaceManager.OnUIKeyBindStateChanged(BoundKeyEventArgs args) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.Input.cs:line 453
   at Robust.Client.Input.InputManager.SetBindState(KeyBinding binding, BoundKeyState state, Boolean uiOnly, Boolean isRepeat) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/Input/InputManager.cs:line 412
   at Robust.Client.Input.InputManager.DownBind(KeyBinding binding, Boolean uiOnly, Boolean isRepeat) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/Input/InputManager.cs:line 362
   at Robust.Client.Input.InputManager.KeyDown(KeyEventArgs args) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/Input/InputManager.cs:line 283
   at Robust.Client.GameController.KeyDown(KeyEventArgs keyEvent) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Input.cs:line 12
   at Robust.Client.Graphics.Clyde.Clyde.DispatchSingleEvent(DEventBase ev) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 47
   at Robust.Client.Graphics.Clyde.Clyde.DispatchEvents() in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Events.cs:line 31
   at Robust.Client.Graphics.Clyde.Clyde.ProcessInput(FrameEventArgs frameEventArgs) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Windowing.cs:line 391
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 494
   at Robust.Client.GameController.<StartupContinue>b__60_2(Object sender, FrameEventArgs args) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 245
   at Robust.Shared.Timing.GameLoop.Run() in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 187
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass102_0.<Run>b__0() in /home/moomoo/Documents/git/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106
```
I don't know how to get logs in localhost.

**Comment by eoineoineoin** [comment]
Duplicate of #28005, and sounds like this isn't expected to work.
