### ISSUE TITLE
Clyde error when blowing up a reinforced wall with 20 grenades

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#3192]
Haven't been able to reproduce it yet.

![TnC4X6nVHF](https://user-images.githubusercontent.com/10968691/107855352-04003d00-6e22-11eb-92d7-5d526025b479.gif)

```csharp
[FATL] unhandled: System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Robust.Client.Graphics.Clyde.Clyde.CreateAudioSource(AudioStream stream) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Audio\Clyde.Audio.cs:line 196
   at Robust.Client.GameObjects.AudioSystem.Play(AudioStream stream, IEntity entity, Nullable`1 audioParams) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\AudioSystem.cs:line 244
   at Robust.Client.GameObjects.AudioSystem.Play(String filename, IEntity entity, Nullable`1 audioParams) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\AudioSystem.cs:line 229
   at Robust.Client.GameObjects.AudioSystem.PlayAudioEntityHandler(PlayAudioEntityMessage ev) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\AudioSystem.cs:line 81
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(Object ev) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 150
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 284
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 200
   at Robust.Shared.GameObjects.EntityManager.<Initialize>b__24_1(Object sender, Object systemMsg) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 61
   at Robust.Client.GameObjects.ClientEntityNetworkManager.DispatchMsgEntity(MsgEntity message) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityNetworkManager.cs:line 109
   at Robust.Client.GameObjects.ClientEntityNetworkManager.Update() in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityNetworkManager.cs:line 43
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 83
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 276
   at Robust.Client.GameController.<MainLoop>b__67_0(Object sender, FrameEventArgs args) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 83
   at Robust.Shared.Timing.GameLoop.Run() in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 199
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 112
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart, IMainArgs loaderArgs) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 58
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart, IMainArgs loaderArgs) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 33
   at Robust.Client.ContentStart.Start(String[] args) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in C:\Projects\C#\space-station-14\Content.Client\Program.cs:line 9
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Robust.Client.Graphics.Clyde.Clyde.CreateAudioSource(AudioStream stream) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Audio\Clyde.Audio.cs:line 196
   at Robust.Client.GameObjects.AudioSystem.Play(AudioStream stream, IEntity entity, Nullable`1 audioParams) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\AudioSystem.cs:line 244
   at Robust.Client.GameObjects.AudioSystem.Play(String filename, IEntity entity, Nullable`1 audioParams) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\AudioSystem.cs:line 229
   at Robust.Client.GameObjects.AudioSystem.PlayAudioEntityHandler(PlayAudioEntityMessage ev) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\AudioSystem.cs:line 81
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(Object ev) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 150
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 284
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 200
   at Robust.Shared.GameObjects.EntityManager.<Initialize>b__24_1(Object sender, Object systemMsg) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 61
   at Robust.Client.GameObjects.ClientEntityNetworkManager.DispatchMsgEntity(MsgEntity message) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityNetworkManager.cs:line 109
   at Robust.Client.GameObjects.ClientEntityNetworkManager.Update() in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityNetworkManager.cs:line 43
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 83
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 276
   at Robust.Client.GameController.<MainLoop>b__67_0(Object sender, FrameEventArgs args) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 83
   at Robust.Shared.Timing.GameLoop.Run() in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 199
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 112
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart, IMainArgs loaderArgs) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 58
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart, IMainArgs loaderArgs) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 33
   at Robust.Client.ContentStart.Start(String[] args) in C:\Projects\C#\space-station-14\RobustToolbox\Robust.Client\ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in C:\Projects\C#\space-station-14\Content.Client\Program.cs:line 9
```

**Comment by PaulRitter** [comment]
"duplicate" of https://github.com/space-wizards/RobustToolbox/issues/2388
