### ISSUE TITLE
Entity on fire crash newly joined clients.

### ISSUE THREAD

**Issue by gardspirito** [space-wizards/space-station-14#31992]
## Description
If there is an entity (behaviour observed on `paper`) that is currently on fire, any new client that joins the server (and apparently has the `paper` in their PVS) instantly crashes on the initialization stage.

**Reproduction**
1) Take, let's say, ca1bfbf9813b69054dccc3993bcdd4603a557acc.
2) Start the server and start the first client.
3) Spawn a paper, remove `DestructibleComponent` so it can stay on fire forever, light up the fire by using lighter.
4) Start the second client and try to connect to the server.

**Screenshots**
Sorry, I don't know what to include here.

**Additional context**
```
[INFO] player: Attaching local player to Elwood Altmann (4/n2503, MobSlimePerson, localhost@JoeGenero_2).
[ERRO] state: Server entity threw in Init: nent=2487, ent=captain's thoughts (378/n2487, PaperCaptainsThoughts)
[ERRO] runtime: Caught exception in "ClientGameStateManager.InitializeAndStart"
Robust.Shared.GameObjects.EntityCreationException: Exception inside InitializeAndStartEntity
 ---> Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Robust.Shared.GameObjects.EntityManager.InitializeEntity(EntityUid entity, MetaDataComponent meta) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 899
   at Robust.Shared.GameObjects.EntityManager.InitializeAndStartEntity(Entity`1 entity, Boolean doMapInit) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 879
   --- End of inner exception stack trace ---
   at Robust.Shared.GameObjects.EntityManager.InitializeAndStartEntity(Entity`1 entity, Boolean doMapInit) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 888
   at Robust.Shared.GameObjects.EntityManager.InitializeAndStartEntity(EntityUid entity, Nullable`1 mapId) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 869
   at Robust.Shared.GameObjects.EntityManager.SpawnAttachedTo(String protoName, EntityCoordinates coordinates, ComponentRegistry overrides, Angle rotation) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Spawn.cs:line 82
   at Robust.Shared.GameObjects.EntityManager.SpawnEntity(String protoName, EntityCoordinates coordinates, ComponentRegistry overrides) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Spawn.cs:line 16
   at Content.Client.Atmos.EntitySystems.FireVisualizerSystem.UpdateAppearance(EntityUid uid, FireVisualsComponent component, SpriteComponent sprite, AppearanceComponent appearance) in /home/gard/prj/space-station-14/Content.Client/Atmos/EntitySystems/FireVisualizerSystem.cs:line 85
   at Content.Client.Atmos.EntitySystems.FireVisualizerSystem.OnComponentInit(EntityUid uid, FireVisualsComponent component, ComponentInit args) in /home/gard/prj/space-station-14/Content.Client/Atmos/EntitySystems/FireVisualizerSystem.cs:line 51
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 678
   at Robust.Shared.GameObjects.EntityManager.LifeInitialize(EntityUid uid, IComponent component, CompIdx idx) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.LifeCycle.cs:line 40
   at Robust.Shared.GameObjects.EntityManager.InitializeComponents(EntityUid uid, MetaDataComponent metadata) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 130
   at Robust.Shared.GameObjects.EntityManager.InitializeEntity(EntityUid entity, MetaDataComponent meta) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 905
   at Robust.Client.GameStates.ClientGameStateManager.InitializeRecursive(EntityUid entity, MetaDataComponent meta, EntityQuery`1 metas, EntityQuery`1 xforms) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 1259
Unhandled exception. Robust.Shared.GameObjects.EntityCreationException: Exception inside InitializeAndStartEntity
 ---> Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Robust.Shared.GameObjects.EntityManager.InitializeEntity(EntityUid entity, MetaDataComponent meta) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 899
   at Robust.Shared.GameObjects.EntityManager.InitializeAndStartEntity(Entity`1 entity, Boolean doMapInit) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 879
   --- End of inner exception stack trace ---
   at Robust.Shared.GameObjects.EntityManager.InitializeAndStartEntity(Entity`1 entity, Boolean doMapInit) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 888
   at Robust.Shared.GameObjects.EntityManager.InitializeAndStartEntity(EntityUid entity, Nullable`1 mapId) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 869
   at Robust.Shared.GameObjects.EntityManager.SpawnAttachedTo(String protoName, EntityCoordinates coordinates, ComponentRegistry overrides, Angle rotation) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Spawn.cs:line 82
   at Robust.Shared.GameObjects.EntityManager.SpawnEntity(String protoName, EntityCoordinates coordinates, ComponentRegistry overrides) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Spawn.cs:line 16
   at Content.Client.Atmos.EntitySystems.FireVisualizerSystem.UpdateAppearance(EntityUid uid, FireVisualsComponent component, SpriteComponent sprite, AppearanceComponent appearance) in /home/gard/prj/space-station-14/Content.Client/Atmos/EntitySystems/FireVisualizerSystem.cs:line 85
   at Content.Client.Atmos.EntitySystems.FireVisualizerSystem.OnComponentInit(EntityUid uid, FireVisualsComponent component, ComponentInit args) in /home/gard/prj/space-station-14/Content.Client/Atmos/EntitySystems/FireVisualizerSystem.cs:line 51
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.DispatchComponent[TEvent](EntityUid euid, IComponent component, CompIdx baseType, Unit& args) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 678
   at Robust.Shared.GameObjects.EntityManager.LifeInitialize(EntityUid uid, IComponent component, CompIdx idx) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.LifeCycle.cs:line 40
   at Robust.Shared.GameObjects.EntityManager.InitializeComponents(EntityUid uid, MetaDataComponent metadata) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 130
   at Robust.Shared.GameObjects.EntityManager.InitializeEntity(EntityUid entity, MetaDataComponent meta) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 905
   at Robust.Client.GameStates.ClientGameStateManager.InitializeRecursive(EntityUid entity, MetaDataComponent meta, EntityQuery`1 metas, EntityQuery`1 xforms) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 1259
   at Robust.Client.GameStates.ClientGameStateManager.InitializeAndStart(Dictionary`2 toCreate, EntityQuery`1 metas, EntityQuery`1 xforms) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 1204
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(GameState curState, GameState nextState) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 963
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 741
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 388
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 540
   at Robust.Client.GameController.<StartupContinue>b__60_0(Object sender, FrameEventArgs args) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 229
   at Robust.Shared.Timing.GameLoop.Run() in /home/gard/prj/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass102_0.<Run>b__0() in /home/gard/prj/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106
```

**Comment by lzk228** [comment]
we do a little trolling :trollface:

**Comment by beck-thompson** [comment]
<img width="974" height="229" alt="Image" src="https://github.com/user-attachments/assets/f5153e56-0dd2-4ada-981c-8d62ca98ba0a" />

We think its mad because when you enter PVS, the entity hasn't been initlized yet but it tries to spawn the light right away
