### ISSUE TITLE
stationevent commands are broken since refactor

### ISSUE THREAD

**Issue by 0x6273** [space-wizards/space-station-14#32196]
## Description
Since the refactor in 07ec00ed05394f0d6c8929d8d015854b8dbbc3bb, the `stationevent` toolshed commands fail with the error:
```
The type EntityPrototype has no parser available and cannot be parsed.
Please contact a programmer with this error, they'd probably like to see it.
THIS IS A BUG.
   at Robust.Shared.Toolshed.ToolshedCommandImplementor.TryParseArguments(Boolean doAutocomplete, ParserContext parserContext, String subCommand, Type pipedType, Dictionary`2& args, Type[]& resolvedTypeArguments, IConError& error, Nullable`1& autocomplete)
   at Robust.Shared.Toolshed.ToolshedCommand.TryParseArguments(Boolean doAutocomplete, ParserContext parserContext, Type pipedType, String subCommand, Dictionary`2& args, Type[]& resolvedTypeArguments, IConError& error, Nullable`1& autocomplete)
   at Robust.Shared.Toolshed.Syntax.ParsedCommand.TryParseCommand(Boolean makeCompletions, ParserContext parserContext, CommandArgumentBundle bundle, Type pipedType, Type targetType, String& subCommand, Func`2& invocable, ToolshedCommand& command, IConError& error, Boolean& noCommand, Nullable`1& autocomplete)
   at Robust.Shared.Toolshed.Syntax.ParsedCommand.TryParse(Boolean doAutoComplete, ParserContext parserContext, Type pipedArgumentType, ParsedCommand& result, IConError& error, Boolean& noCommand, Nullable`1& autocomplete, Type targetType)
   at Robust.Shared.Toolshed.Syntax.CommandRun.TryParse(Boolean doAutocomplete, ParserContext parserContext, Type pipedType, Type targetOutput, Boolean once, CommandRun& expr, Nullable`1& autocomplete, IConError& error)
   at Robust.Shared.Toolshed.ToolshedManager.InvokeCommand(IInvocationContext ctx, String command, Object input, Object& result)
   at Robust.Shared.Toolshed.ToolshedManager.InvokeCommand(IConsoleShell session, String command, Object input, Object& result, IInvocationContext& ctx)
   at Robust.Server.Console.ServerConsoleHost.ExecuteInShell(IConsoleShell shell, String command)
   at Robust.Server.Console.ServerConsoleHost.ExecuteCommand(ICommonSession session, String command)
   at Robust.Server.Console.ServerConsoleHost.ProcessCommand(MsgConCmd message)
   at Robust.Shared.Network.NetManager.<>c__DisplayClass108_0`1.<RegisterNetMessage>b__0(NetMessage msg)
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg)
   at Robust.Shared.Network.NetManager.ProcessPackets()
   at Robust.Server.BaseServer.Input(FrameEventArgs args)
   at Robust.Server.BaseServer.<SetupMainLoop>b__67_0(Object sender, FrameEventArgs args)
   at Robust.Shared.Timing.GameLoop.Run()
   at Robust.Server.BaseServer.MainLoop()
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options)
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart)
   at Robust.Server.ContentStart.Start(String[] args)
   at Content.Server.Program.Main(String[] args)

[INFO] CON: Failed to execute toolshed command
```

**Reproduction**
Run any `stationevent` command such as `> stationevent:simulate`

**Screenshots**

**Additional context**
No other toolshed command seems to take `[CommandArgument] EntityPrototype`, although some take `[CommandArgument] Prototype<EntityPrototype>`.

**Comment by 0x6273** [comment]
@IProduceWidgets
