### ISSUE TITLE
SFML.LoadingFailedException

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#328]
This occurs randomly about 1/4th to 1/3rd of the time since the new SFML loading system was put into place.

```
   at SFML.Graphics.Image..ctor(Stream stream)
   at SS14.Client.Resources.ResourceCache.LoadTextureFrom(String name, Stream stream) in C:\Users\Age\Desktop\ss14\SS14.Client\ResourceManagement\ResourceCache.cs:line 308
   at SS14.Client.Resources.ResourceCache.LoadExternalSprites() in C:\Users\Age\Desktop\ss14\SS14.Client\ResourceManagement\ResourceCache.cs:line 528
   at SS14.Client.Resources.ResourceCache.LoadLocalResources() in C:\Users\Age\Desktop\ss14\SS14.Client\ResourceManagement\ResourceCache.cs:line 79
   at SS14.Client.GameController.Run() in C:\Users\Age\Desktop\ss14\SS14.Client\GameController.cs:line 81
   at SS14.Client.Program.Main() in C:\Users\Age\Desktop\ss14\SS14.Client\Program.cs:line 63
```

**Comment by clusterfack** [comment]
Doesn't seem to occur anymore
