### ISSUE TITLE
Implanter interactions are broken in Debug

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/space-station-14#32860]
Run game in Release, spawn an implanter and an empty implanter, insert implant into yourself then remove it. Works as expected.

(In both Release and Debug, everything works as expected on Urist)

Run game in Debug, spawn an implanter and an empty implanter. Using either one one yourself instantly crashes the game.

```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Expected: not 2363
   at Robust.Shared.Utility.DebugTools.AssertNotEqual[T](T objA, T objB) in /home/useriel/s14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 144
   at Content.Shared.Interaction.SharedInteractionSystem.DoContactInteraction(EntityUid uidA, Nullable`1 uidB, HandledEntityEventArgs args) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 1375
   at Content.Shared.Interaction.SharedInteractionSystem.InteractDoAfter(EntityUid user, EntityUid used, Nullable`1 target, EntityCoordinates clickLocation, Boolean canReach, Boolean checkDeletion) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 1055
   at Content.Shared.Interaction.SharedInteractionSystem.InteractUsing(EntityUid user, EntityUid used, EntityUid target, EntityCoordinates clickLocation, Boolean checkCanInteract, Boolean checkCanUse) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 1025
   at Content.Shared.Interaction.SharedInteractionSystem.UserInteraction(EntityUid user, EntityCoordinates coordinates, Nullable`1 target, Boolean altInteract, Boolean checkCanInteract, Boolean checkAccess, Boolean checkCanUse) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 440
   at Content.Shared.Interaction.SharedInteractionSystem.HandleUseInteraction(ICommonSession session, EntityCoordinates coords, EntityUid uid) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 314
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass5_0.<.ctor>b__0(PointerInputCmdArgs& args) in /home/useriel/s14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 97
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in /home/useriel/s14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 127
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in /home/useriel/s14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/InputSystem.cs:line 65
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in /home/useriel/s14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/useriel/s14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 266
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/useriel/s14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 192
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/useriel/s14/RobustToolbox/Robust.Server/BaseServer.cs:line 731
   at Robust.Server.BaseServer.<SetupMainLoop>b__67_1(Object sender, FrameEventArgs args) in /home/useriel/s14/RobustToolbox/Robust.Server/BaseServer.cs:line 544
   at Robust.Shared.Timing.GameLoop.Run() in /home/useriel/s14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in /home/useriel/s14/RobustToolbox/Robust.Server/BaseServer.cs:line 571
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/useriel/s14/RobustToolbox/Robust.Server/Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/useriel/s14/RobustToolbox/Robust.Server/Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in /home/useriel/s14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/useriel/s14/Content.Server/Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Expected: not 2363
   at Robust.Shared.Utility.DebugTools.AssertNotEqual[T](T objA, T objB) in /home/useriel/s14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 144
   at Content.Shared.Interaction.SharedInteractionSystem.DoContactInteraction(EntityUid uidA, Nullable`1 uidB, HandledEntityEventArgs args) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 1375
   at Content.Shared.Interaction.SharedInteractionSystem.InteractDoAfter(EntityUid user, EntityUid used, Nullable`1 target, EntityCoordinates clickLocation, Boolean canReach, Boolean checkDeletion) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 1055
   at Content.Shared.Interaction.SharedInteractionSystem.InteractUsing(EntityUid user, EntityUid used, EntityUid target, EntityCoordinates clickLocation, Boolean checkCanInteract, Boolean checkCanUse) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 1025
   at Content.Shared.Interaction.SharedInteractionSystem.UserInteraction(EntityUid user, EntityCoordinates coordinates, Nullable`1 target, Boolean altInteract, Boolean checkCanInteract, Boolean checkAccess, Boolean checkCanUse) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 440
   at Content.Shared.Interaction.SharedInteractionSystem.HandleUseInteraction(ICommonSession session, EntityCoordinates coords, EntityUid uid) in /home/useriel/s14/Content.Shared/Interaction/SharedInteractionSystem.cs:line 314
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass5_0.<.ctor>b__0(PointerInputCmdArgs& args) in /home/useriel/s14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 97
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in /home/useriel/s14/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 127
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in /home/useriel/s14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/InputSystem.cs:line 65
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in /home/useriel/s14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in /home/useriel/s14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/useriel/s14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 266
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/useriel/s14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 192
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/useriel/s14/RobustToolbox/Robust.Server/BaseServer.cs:line 731
   at Robust.Server.BaseServer.<SetupMainLoop>b__67_1(Object sender, FrameEventArgs args) in /home/useriel/s14/RobustToolbox/Robust.Server/BaseServer.cs:line 544
   at Robust.Shared.Timing.GameLoop.Run() in /home/useriel/s14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in /home/useriel/s14/RobustToolbox/Robust.Server/BaseServer.cs:line 571
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/useriel/s14/RobustToolbox/Robust.Server/Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/useriel/s14/RobustToolbox/Robust.Server/Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in /home/useriel/s14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/useriel/s14/Content.Server/Program.cs:line 9
```

**Comment by Errant-4** [comment]
Duplicate of #32811
