### ISSUE TITLE
Map Renderer error on entity that doesn't exist in map file, entity '0'

### ISSUE THREAD

**Issue by hobolyra** [space-wizards/space-station-14#33359]
**The basic:** When running the map renderer on a map (that I have rendered in the past) it says it can't find some entity with UID of '0'. Looking at the map YML in notepad++ and searching UIDs (both of just 0 or even everthing that might errenously start with 0) there are no entries that would match or look to be causing an error. I have checked the map code a few ways now to try to identify what it might be finding.

I went back to the map in the game itself, and it runs fine (both mapping and initialized) but will not render any longer. Tested base maps (such as box) and those render just fine... or so I thought. Oasis also throws this very same error.

Error log here (ignore stupid folder name...)

`Painting map Mitosis failed due to an internal exception:
NUnit.Framework.AssertionException: SERVER: 3.149s [ERRO] map: Error in map file: found local entity UID '0' which does not exist. Exception:
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message)
   at Content.IntegrationTests.PoolTestLogHandler.Log(String sawmillName, LogEvent message) in E:\ss14SHIT\Content.IntegrationTests\PoolTestLogHandler.cs:line 66
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Log\LogManager.Sawmill.cs:line 116
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Log\LogManager.Sawmill.cs:line 124
   at Robust.Shared.Log.LogManager.Sawmill.Log(LogLevel level, Exception exception, String message, Object[] args) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Log\LogManager.Sawmill.cs:line 84
   at Robust.Shared.Log.LogManager.Sawmill.Log(LogLevel level, String message, Object[] args) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Log\LogManager.Sawmill.cs:line 96
   at Robust.Shared.Log.LogManager.Sawmill.Error(String message, Object[] args) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Log\LogManager.Sawmill.cs:line 169
   at Robust.Shared.Map.MapSerializationContext.Robust.Shared.Serialization.TypeSerializers.Interfaces.ITypeReader<Robust.Shared.GameObjects.EntityUid,Robust.Shared.Serialization.Markdown.Value.ValueDataNode>.Read(ISerializationManager serializationManager, ValueDataNode node, IDependencyCollection dependencies, SerializationHookContext hookCtx, ISerializationContext context, InstantiationDelegate`1 _) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Map\MapSerializationContext.cs:line 157
   at Robust.Shared.Serialization.Manager.SerializationManager.Read[T,TNode](ITypeReader`2 reader, TNode node, SerializationHookContext hookCtx, ISerializationContext context, InstantiationDelegate`1 instanceProvider, Boolean notNullableOverride) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Serialization\Manager\SerializationManager.Reading.cs:line 109
   at lambda_method39633(Closure, DataNode, SerializationHookContext, ISerializationContext, InstantiationDelegate`1)
   at Robust.Shared.Serialization.Manager.SerializationManager.Read[T](DataNode node, SerializationHookContext hookCtx, ISerializationContext context, InstantiationDelegate`1 instanceProvider, Boolean notNullableOverride) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Serialization\Manager\SerializationManager.Reading.cs:line 82
   at Robust.Shared.Serialization.TypeSerializers.Implementations.Generic.HashSetSerializer`1.Robust.Shared.Serialization.TypeSerializers.Interfaces.ITypeReader<System.Collections.Generic.HashSet<T>,Robust.Shared.Serialization.Markdown.Sequence.SequenceDataNode>.Read(ISerializationManager serializationManager, SequenceDataNode node, IDependencyCollection dependencies, SerializationHookContext hookCtx, ISerializationContext context, InstantiationDelegate`1 instanceProvider) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Serialization\TypeSerializers\Implementations\Generic\HashSetSerializer.cs:line 38
   at Robust.Shared.Serialization.Manager.SerializationManager.Read[T,TNode](ITypeReader`2 reader, TNode node, SerializationHookContext hookCtx, ISerializationContext context, InstantiationDelegate`1 instanceProvider, Boolean notNullableOverride) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Serialization\Manager\SerializationManager.Reading.cs:line 109
   at lambda_method39632(Closure, DataNode, SerializationHookContext, ISerializationContext, InstantiationDelegate`1)
   at Robust.Shared.Serialization.Manager.SerializationManager.Read[T](DataNode node, SerializationHookContext hookCtx, ISerializationContext context, InstantiationDelegate`1 instanceProvider, Boolean notNullableOverride) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Serialization\Manager\SerializationManager.Reading.cs:line 82
   at lambda_method19213(Closure, DeviceNetworkComponent&, MappingDataNode, SerializationHookContext, ISerializationContext)
   at Robust.Shared.Serialization.Manager.SerializationManager.ReadGenericMapping[TValue](MappingDataNode node, DataDefinition`1 definition, SerializationHookContext hookCtx, ISerializationContext context, InstantiationDelegate`1 instanceProvider) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Serialization\Manager\SerializationManager.Reading.cs:line 520
   at lambda_method34433(Closure, DataNode, SerializationHookContext, ISerializationContext, InstantiationDelegate`1)
   at Robust.Shared.Serialization.Manager.SerializationManager.Read[T](DataNode node, SerializationHookContext hookCtx, ISerializationContext context, InstantiationDelegate`1 instanceProvider, Boolean notNullableOverride) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Serialization\Manager\SerializationManager.Reading.cs:line 82
   at lambda_method34416(Closure, DataNode, SerializationHookContext, ISerializationContext)
   at Robust.Shared.Serialization.Manager.SerializationManager.Read(Type type, DataNode node, SerializationHookContext hookCtx, ISerializationContext context, Boolean notNullableOverride) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Serialization\Manager\SerializationManager.Reading.cs:line 158
   at Robust.Shared.Serialization.Manager.SerializationManager.Read(Type type, DataNode node, ISerializationContext context, Boolean skipHook, Boolean notNullableOverride) in E:\ss14SHIT\RobustToolbox\Robust.Shared\Serialization\Manager\SerializationManager.Reading.cs:line 148
   at Robust.Server.GameObjects.MapLoaderSystem.LoadEntity(EntityUid uid, MappingDataNode data, MetaDataComponent meta) in E:\ss14SHIT\RobustToolbox\Robust.Server\GameObjects\EntitySystems\MapLoaderSystem.cs:line 568
   at Robust.Server.GameObjects.MapLoaderSystem.LoadEntities(MapData mapData) in E:\ss14SHIT\RobustToolbox\Robust.Server\GameObjects\EntitySystems\MapLoaderSystem.cs:line 531
   at Robust.Server.GameObjects.MapLoaderSystem.Deserialize(MapData data) in E:\ss14SHIT\RobustToolbox\Robust.Server\GameObjects\EntitySystems\MapLoaderSystem.cs:line 280
   at Robust.Server.GameObjects.MapLoaderSystem.TryLoad(MapId mapId, String path, IReadOnlyList`1& rootUids, MapLoadOptions options) in E:\ss14SHIT\RobustToolbox\Robust.Server\GameObjects\EntitySystems\MapLoaderSystem.cs:line 155
   at Robust.Server.GameObjects.MapLoaderSystem.LoadMap(MapId mapId, String path, MapLoadOptions options) in E:\ss14SHIT\RobustToolbox\Robust.Server\GameObjects\EntitySystems\MapLoaderSystem.cs:line 97
   at Content.Server.GameTicking.GameTicker.LoadGameMap(GameMapPrototype map, MapId targetMapId, MapLoadOptions loadOptions, String stationName) in E:\ss14SHIT\Content.Server\GameTicking\GameTicker.RoundFlow.cs:line 174
   at Content.Server.GameTicking.GameTicker.LoadMaps() in E:\ss14SHIT\Content.Server\GameTicking\GameTicker.RoundFlow.cs:line 145
   at Content.Server.GameTicking.GameTicker.StartRound(Boolean force) in E:\ss14SHIT\Content.Server\GameTicking\GameTicker.RoundFlow.cs:line 255
   at Content.Server.GameTicking.GameTicker.RestartRound() in E:\ss14SHIT\Content.Server\GameTicking\GameTicker.RoundFlow.cs:line 516
   at Content.IntegrationTests.Pair.TestPair.<>c__DisplayClass34_1.<Initialize>b__2() in E:\ss14SHIT\Content.IntegrationTests\Pair\TestPair.cs:line 81
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.SingleThreadRunUntilEmpty() in E:\ss14SHIT\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 1121
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.Run() in E:\ss14SHIT\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 1085
   at Robust.UnitTesting.RobustIntegrationTest.ServerIntegrationInstance._serverMain() in E:\ss14SHIT\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 657
--- End of stack trace from previous location ---
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitIdleImplAsync(Boolean throwOnUnhandled, CancellationToken cancellationToken) in E:\ss14SHIT\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 450
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitPost(Action post) in E:\ss14SHIT\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 573
   at Content.IntegrationTests.Pair.TestPair.Initialize(PoolSettings settings, TextWriter testOut, List`1 testPrototypes) in E:\ss14SHIT\Content.IntegrationTests\Pair\TestPair.cs:line 81
   at Content.IntegrationTests.PoolManager.CreateServerClientPair(PoolSettings poolSettings, TextWriter testOut) in E:\ss14SHIT\Content.IntegrationTests\PoolManager.cs:line 354
   at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in E:\ss14SHIT\Content.IntegrationTests\PoolManager.cs:line 216
   at Content.IntegrationTests.PoolManager.GetServerClientPair(PoolSettings poolSettings) in E:\ss14SHIT\Content.IntegrationTests\PoolManager.cs:line 262
   at Content.IntegrationTests.PoolManager.GetServerClient(PoolSettings poolSettings) in E:\ss14SHIT\Content.IntegrationTests\PoolManager.cs:line 187
   at Content.MapRenderer.Painters.MapPainter.Paint(String map)+MoveNext() in E:\ss14SHIT\Content.MapRenderer\Painters\MapPainter.cs:line 30
   at Content.MapRenderer.Painters.MapPainter.Paint(String map)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Content.MapRenderer.Program.Run(CommandLineArguments arguments) in E:\ss14SHIT\Content.MapRenderer\Program.cs:line 163
   at Content.MapRenderer.Program.Run(CommandLineArguments arguments) in E:\ss14SHIT\Content.MapRenderer\Program.cs:line 163`

**Comment by hobolyra** [comment]
UPDATE: I found the content causing the error by slowly deleting pieces of the map, saving those sections, trying it... etc until I found all of the parts causing this.

Turns out if you have air sensors on a network, sometimes it will save them with the tag
```
      configurators:
      - invalid
```
(and it seems very random about it, since 12 had this issue, but every other one on the ship was fine) and using regex to mass search and remove those 12 instances of this one line fixed the issue. 

Meaning now, the issue is why the heck are some getting this flag that breaks rendering and also tosses other errors?
