### ISSUE TITLE
Any object traveling on a conveyor belt into a recycler will crash the dev server

### ISSUE THREAD

**Issue by MossyGreySlope** [space-wizards/space-station-14#33490]
## Description
If a conveyor belt carries any object into a running recycler, then the server will crash. Additionally, if the player rides the conveyor belt into the recycler both the client and server will crash. This does not require the the recycler to be emagged.
Since the error is a `DebugAssertException`, this likely only affects dev servers.

**Reproduction**
- Place a conveyor belt.
- Place a recycler after it.
- Placer a lever and link it to both the conveyor and the recycler.
- Pull the lever.
- Drop something (or step) onto the conveyor.

**Screenshots**

https://github.com/user-attachments/assets/341ac647-5f9b-45ee-90eb-dc6f2650fab9

**Additional context**
Server stacktrace:
```
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 37
   at Content.Shared.Physics.Controllers.SharedConveyorController.TryConvey(Entity`3 entity, Boolean prediction, Single frameTime) in /redacted/SS14/space-station-14/Content.Shared/Physics/Controllers/SharedConveyorController.cs:line 119
   at Content.Shared.Physics.Controllers.SharedConveyorController.UpdateBeforeSolve(Boolean prediction, Single frameTime) in /redacted/SS14/space-station-14/Content.Shared/Physics/Controllers/SharedConveyorController.cs:line 83
   at Robust.Shared.Physics.Controllers.VirtualController.OnBeforeSolve(PhysicsUpdateBeforeSolveEvent& ev) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/Physics/Controllers/VirtualController.cs:line 48
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass6_0`1.<SubscribeEvent>b__0(Unit& ev) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 195
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T& toRaise) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 283
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[T](T& message) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 105
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.cs:line 286
   at Robust.Client.Physics.PhysicsSystem.Update(Single frameTime) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Client/Physics/PhysicsSystem.cs:line 23
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 306
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 273
   at Robust.Client.GameObjects.ClientEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 194
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /redacted/SS14/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 459
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 552
   at Robust.Client.GameController.<StartupContinue>b__63_0(Object sender, FrameEventArgs args) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 243
   at Robust.Shared.Timing.GameLoop.Run() in /redacted/SS14/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /redacted/SS14/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass105_0.<Run>b__0() in /redacted/SS14/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106
```

**Comment by red15** [comment]
Blaming shows 65821c96f49186238726ad69231a35b0ea508f62
This was a fairly big change into how the conveyors work.

Not sure why the debug assertion is left there?

A [few lines down](https://github.com/space-wizards/space-station-14/commit/65821c96f49186238726ad69231a35b0ea508f62#diff-f81607979c82968a141a385542043bbce29f8848f922526fad472b53d840411bR134) in fact it starts looping over all the conveyors found so it should be allowed to be more than 1.

@metalgearsloth any comments on that `DebugTools.Assert` call ?

**Comment by Winkarst-cpu** [comment]
Was fixed in the https://github.com/space-wizards/space-station-14/commit/948588399c14fc13021efea4c34f5cbfc3a5f13b since ``DebugTools.Assert(_conveyors.Count <= 1)`` was removed.

**Comment by Winkarst-cpu** [comment]
https://github.com/user-attachments/assets/6eaa3c01-89f0-41d9-bb96-6dafb05d7fb7

**Comment by FairlySadPanda** [comment]
Closed as fixed.
