### ISSUE TITLE
Can't Place Construction Ghost

### ISSUE THREAD

**Issue by Broken-Milk** [space-wizards/space-station-14#33623]
## Description
When I open the construction menu and left click 'Place construction ghost' under any construction, then click a tile, I cannot place the ghost. I have tried this with many constructables. I also cannot right click to exit construction mode at this point, I have to open the crafting menu by clicking it's icon and left click 'Place construction ghost' to exit the mode. Please help.

**Comment by Broken-Milk** [comment]
solution here, rebind the map editor keybinds: https://github.com/space-wizards/space-station-14/issues/27457

**Comment by c01dc0ffee** [comment]
'Clear all' fixes this for me. It never happens in the first round after launching the game. Presumably some state error going on.

**Comment by VerinSenpai** [comment]
state corruption you say >.>

**Comment by VerinSenpai** [comment]
[ERRO] clyde.win: Error dispatching window event DEventKeyUp:
System.Collections.Generic.KeyNotFoundException: Entity 1051 does not have a component of type Robust.Shared.GameObjects.TransformComponent
   at Content.Client.Construction.ConstructionSystem.GhostPresent(EntityCoordinates loc) in C:\Users\akika\projects\space-station-14\Content.Client\Construction\ConstructionSystem.cs:line 258
   at Content.Client.Construction.ConstructionSystem.TrySpawnGhost(ConstructionPrototype prototype, EntityCoordinates loc, Direction dir, Nullable`1& ghost) in C:\Users\akika\projects\space-station-14\Content.Client\Construction\ConstructionSystem.cs:line 195
   at Content.Client.Construction.ConstructionSystem.SpawnGhost(ConstructionPrototype prototype, EntityCoordinates loc, Direction dir) in C:\Users\akika\projects\space-station-14\Content.Client\Construction\ConstructionSystem.cs:line 177
   at Content.Client.Construction.ConstructionPlacementHijack.HijackPlacementRequest(EntityCoordinates coordinates) in C:\Users\akika\projects\space-station-14\Content.Client\Construction\ConstructionPlacementHijack.cs:line 29  
   at Robust.Client.Placement.PlacementManager.RequestPlacement(EntityCoordinates coordinates) in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\Placement\PlacementManager.cs:line 764
   at Robust.Client.Placement.PlacementManager.HandlePlacement() in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\Placement\PlacementManager.cs:line 404
   at Robust.Client.Placement.PlacementManager.<SetupInput>b__92_3(ICommonSession session, EntityCoordinates coords, EntityUid uid) in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\Placement\PlacementManager.cs:line 279
   at Robust.Shared.Input.Binding.PointerStateInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:line 181
   at Robust.Client.GameObjects.InputSystem.HandleInputCommand(ICommonSession session, BoundKeyFunction function, IFullInputCmdMessage message, Boolean replay) in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\InputSystem.cs:line 79
   at Content.Client.Gameplay.GameplayStateBase.OnKeyBindStateChanged(ViewportBoundKeyEventArgs args) in C:\Users\akika\projects\space-station-14\Content.Client\Gameplay\GameplayStateBase.cs:line 242
   at Robust.Client.Input.InputManager.ViewportKeyEvent(Control viewport, BoundKeyEventArgs eventArgs) in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 432
   at Content.Client.Viewport.ScalingViewport.KeyBindUp(GUIBoundKeyEventArgs args) in C:\Users\akika\projects\space-station-14\Content.Client\Viewport\ScalingViewport.cs:line 144
   at Robust.Client.UserInterface.UserInterfaceManager.KeyBindUp(BoundKeyEventArgs args) in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.Input.cs:line 130
   at Robust.Client.Input.InputManager.SetBindState(KeyBinding binding, BoundKeyState state, Boolean uiOnly, Boolean isRepeat) in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 412
   at Robust.Client.Input.InputManager.KeyUp(KeyEventArgs args) in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 326
   at Robust.Client.Graphics.Clyde.Clyde.DispatchSingleEvent(DEventBase ev) in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Clyde.Events.cs:line 50
   at Robust.Client.Graphics.Clyde.Clyde.DispatchEvents() in C:\Users\akika\projects\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Clyde.Events.cs:line 31
[INFO] system.map: Grid Patella-33-B (2180/n93904) changed parent. Old parent: Map Entity (2179/n93903). New parent: Reach (2177/n76498)

**Comment by VerinSenpai** [comment]
Right. I have some steps to reproduce. Running on the latest master.
I observed that it seems to happen if a build ghost exists when the round ends, hence why clearing ghosts in the next round fixes the issue.


Start the round while not readied up.
Late join in.
Place something down, notice that its functional.
End round.
Restart round now.
Ready up. Start round.
Attempt to place a build ghost.
Notice that it is non functional.

https://github.com/user-attachments/assets/b41fd0a0-6315-4dbd-a163-615fe7630c04

The steps above are guaranteed to work, however they can probably be simplified to the following.

Ready up and start round
Place build ghost.
restart round now.
ready up and start round.
Attempt to place build ghost.

It would probably fix the issue but is likely a band-aid fix to have the client clear build ghosts when the round ends.
