### ISSUE TITLE
Flaky integration test `DeleteThemAllThenGhost`

### ISSUE THREAD

**Issue by CrafterKolyan** [space-wizards/space-station-14#33627]
Test `DeleteThemAllThenGhost` ocassionally fails in Github actions.

Logs:
```
 Failed DeleteAllThenGhost [321 ms]
  Error Message:
   Multiple failures or warnings in test:
  1) SERVER: 0.294s [ERRO] system.role: Mind Role Entity 97715/n0D does not have a MindRoleComponent, despite being listed as a role belonging to mind (Priskake) (97714/n97714)| Exception: 
  2) SERVER: 0.302s [ERRO] entity: Caught exception while raising event EntityTerminatingEvent on entity Priskake (97716/n97716, MobVox)
NUnit.Framework.AssertionException: SERVER: 0.294s [ERRO] system.role: Mind Role Entity 97715/n0D does not have a MindRoleComponent, despite being listed as a role belonging to mind (Priskake) (97714/n97714)| Exception: 
   at NUnit.Framework.Assert.ReportFailure(String message)
   at Content.IntegrationTests.PoolTestLogHandler.Log(String sawmillName, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/Content.IntegrationTests/PoolTestLogHandler.cs:line 66
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 106
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 125
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 125
   at Robust.Shared.Log.LogManager.Sawmill.Log(LogLevel level, String message, Object[] args) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 96
   at Robust.Shared.Log.LogManager.Sawmill.Error(String message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 174
   at Content.Shared.Roles.SharedRoleSystem.CheckAntagonistStatus(Entity`1 mind) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Shared/Roles/SharedRoleSystem.cs:line 471
   at Content.Shared.Roles.SharedRoleSystem.MindIsAntagonist(Nullable`1 mindId) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Shared/Roles/SharedRoleSystem.cs:line 441
   at Content.Server.Administration.Systems.AdminSystem.GetPlayerInfo(SessionData data, ICommonSession session) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Server/Administration/Systems/AdminSystem.cs:line 245
   at Content.Server.Administration.Systems.AdminSystem.UpdatePlayerList(ICommonSession player) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Server/Administration/Systems/AdminSystem.cs:line 135
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.Player.SharedPlayerManager.Detach(ICommonSession session) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Player/SharedPlayerManager.Sessions.cs:line 188
   at Content.Server.Mind.MindSystem.TransferTo(EntityUid mindId, Nullable`1 entity, Boolean ghostCheckOverride, Boolean createGhost, MindComponent mind) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Server/Mind/MindSystem.cs:line 259
   at Content.Server.Mind.MindSystem.OnMindContainerTerminating(EntityUid uid, MindContainerComponent component, EntityTerminatingEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Server/Mind/MindSystem.cs:line 69
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 633
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 218
   at Robust.Shared.GameObjects.EntityManager.RecursiveFlagEntityTermination(EntityUid uid, MetaDataComponent metadata, TransformComponent xform) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 568 Exception: 
  3) Console command encountered an error: Failed to execute toolshed command
  4) SERVER: 0.306s [ERRO] con: [HOST]: ExecuteError - entities delete:
NUnit.Framework.AssertionException: Multiple failures or warnings in test:
  1) SERVER: 0.294s [ERRO] system.role: Mind Role Entity 97715/n0D does not have a MindRoleComponent, despite being listed as a role belonging to mind (Priskake) (97714/n97714)| Exception: 
  2) SERVER: 0.302s [ERRO] entity: Caught exception while raising event EntityTerminatingEvent on entity Priskake (97716/n97716, MobVox)
NUnit.Framework.AssertionException: SERVER: 0.294s [ERRO] system.role: Mind Role Entity 97715/n0D does not have a MindRoleComponent, despite being listed as a role belonging to mind (Priskake) (97714/n97714)| Exception: 
   at NUnit.Framework.Assert.ReportFailure(String message)
   at Content.IntegrationTests.PoolTestLogHandler.Log(String sawmillName, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/Content.IntegrationTests/PoolTestLogHandler.cs:line 66
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 106
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 125
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 125
   at Robust.Shared.Log.LogManager.Sawmill.Log(LogLevel level, String message, Object[] args) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 96
   at Robust.Shared.Log.LogManager.Sawmill.Error(String message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 174
   at Content.Shared.Roles.SharedRoleSystem.CheckAntagonistStatus(Entity`1 mind) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Shared/Roles/SharedRoleSystem.cs:line 471
   at Content.Shared.Roles.SharedRoleSystem.MindIsAntagonist(Nullable`1 mindId) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Shared/Roles/SharedRoleSystem.cs:line 441
   at Content.Server.Administration.Systems.AdminSystem.GetPlayerInfo(SessionData data, ICommonSession session) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Server/Administration/Systems/AdminSystem.cs:line 245
   at Content.Server.Administration.Systems.AdminSystem.UpdatePlayerList(ICommonSession player) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Server/Administration/Systems/AdminSystem.cs:line 135
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.Player.SharedPlayerManager.Detach(ICommonSession session) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Player/SharedPlayerManager.Sessions.cs:line 188
   at Content.Server.Mind.MindSystem.TransferTo(EntityUid mindId, Nullable`1 entity, Boolean ghostCheckOverride, Boolean createGhost, MindComponent mind) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Server/Mind/MindSystem.cs:line 259
   at Content.Server.Mind.MindSystem.OnMindContainerTerminating(EntityUid uid, MindContainerComponent component, EntityTerminatingEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Content.Server/Mind/MindSystem.cs:line 69
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 633
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 218
   at Robust.Shared.GameObjects.EntityManager.RecursiveFlagEntityTermination(EntityUid uid, MetaDataComponent metadata, TransformComponent xform) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 568 Exception: 
  3) Console command encountered an error: Failed to execute toolshed command

   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message)
   at Robust.UnitTesting.TestingServerConsoleHost.WriteError(ICommonSession session, String text) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.UnitTesting/TestingConsoleHost.cs:line 13
   at Robust.Shared.Console.ConsoleShell.WriteError(String text) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Console/ConsoleShell.cs:line 60
   at Robust.Server.Console.ServerConsoleHost.ExecuteInShell(IConsoleShell shell, String command) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Server/Console/ServerConsoleHost.cs:line 142 Exception: 

  Stack Trace:
     at Content.IntegrationTests.PoolTestLogHandler.Log(String sawmillName, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/Content.IntegrationTests/PoolTestLogHandler.cs:line 66
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 106
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 125
   at Robust.Shared.Log.LogManager.Sawmill.Log(LogLevel level, String message, Object[] args) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 96
   at Robust.Shared.Log.LogManager.Sawmill.Error(String message) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 174
   at Robust.Server.Console.ServerConsoleHost.ExecuteInShell(IConsoleShell shell, String command) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Server/Console/ServerConsoleHost.cs:line 150
   at Robust.Server.Console.ServerConsoleHost.ExecuteCommand(ICommonSession session, String command) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Server/Console/ServerConsoleHost.cs:line 36
   at Robust.Shared.Console.ConsoleHost.ExecuteCommand(String command) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.Shared/Console/ConsoleHost.cs:line 239
   at Content.IntegrationTests.Tests.Minds.MindTests.<>c__DisplayClass0_0.<DeleteAllThenGhost>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs:line 27
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.SingleThreadRunUntilEmpty() in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1098
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1085
   at Robust.UnitTesting.RobustIntegrationTest.ServerIntegrationInstance._serverMain() in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 656
--- End of stack trace from previous location ---
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitIdleImplAsync(Boolean throwOnUnhandled, CancellationToken cancellationToken) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 450
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitPost(Action post) in /home/runner/work/RobustToolbox/RobustToolbox/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 573
   at Content.IntegrationTests.Tests.Minds.MindTests.DeleteAllThenGhost() in /home/runner/work/RobustToolbox/RobustToolbox/Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs:line 27
   at Content.IntegrationTests.Tests.Minds.MindTests.DeleteAllThenGhost() in /home/runner/work/RobustToolbox/RobustToolbox/Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs:line 59
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

1)    at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose() in /home/runner/work/RobustToolbox/RobustToolbox/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 34
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose()
   at Content.IntegrationTests.Pair.TestPair.DisposeAsync() in /home/runner/work/RobustToolbox/RobustToolbox/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 121
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Content.IntegrationTests.Pair.TestPair.DisposeAsync()
   at Content.IntegrationTests.Tests.Minds.MindTests.DeleteAllThenGhost() in /home/runner/work/RobustToolbox/RobustToolbox/Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs:line 59
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)


  Standard Output Messages:
 GetServerClientPair: Called by test Minds.MindTests.DeleteAllThenGhost
 GetServerClientPair: Looking in pool for a suitable pair
 GetServerClientPair: Suitable pair found
 GetServerClientPair: Cleaning existing pair
 Recycling...
 Recycling: 0.9862 ms: Disconnecting client.
 CLIENT: 0.004s [INFO] player: Detaching local player from DummyPlayerEntity (89262/n97702, MobObserver).
 CLIENT: 0.004s [INFO] player: Local player is no longer attached to any entity.
 CLIENT: 0.005s [INFO] entity: Flushing entities. Entity count: 77
 CLIENT: 0.006s [INFO] system.map: Grid Empty (89202/n97622) changed parent. Old parent: Empty (89201/n97623). New parent: 0/n0D
 CLIENT: 0.006s [INFO] system.map: Removing grid Empty (89202/n97622)
 CLIENT: 0.009s [INFO] system.mind: Wiping all minds
 CLIENT: 0.011s [DEBG] client: Runlevel changed to: Initialize
 CLIENT: 0.011s [DEBG] root: Switching to state Content.Client.MainMenu.MainScreen
 Recycling: 11.8729 ms: Restarting round.
 SERVER: 0.012s [INFO] ticker: Restarting round!
 SERVER: 0.012s [INFO] SERVER: OOC chat has been enabled.
 SERVER: 0.012s [INFO] system.mind: Wiping all minds
 SERVER: 0.012s [INFO] entity: Flushing entities. Entity count: 71
 SERVER: 0.012s [INFO] system.map: Grid Empty (97622/n97622) changed parent. Old parent: Empty (97623/n97623). New parent: 0/n0D
 SERVER: 0.012s [INFO] system.map: Removing grid Empty (97622/n97622)
 Recycling: 16.3941 ms: Setting CVar 
 Recycling: 17.4424 ms: Restarting server again
 SERVER: 0.017s [INFO] entity: Flushing entities. Entity count: 0
 SERVER: 0.018s [INFO] ticker: Restarting round!
 SERVER: 0.018s [INFO] system.mind: Wiping all minds
 SERVER: 0.018s [INFO] entity: Flushing entities. Entity count: 0
 SERVER: 0.019s [INFO] ticker: Starting round!
 SERVER: 0.019s [INFO] loader: No user map found: /Maps/Test/empty.yml
 SERVER: 0.019s [INFO] loader: Loading Map: /Maps/Test/empty.yml
 SERVER: 0.021s [INFO] loader: Loading map file with a root node onto an existing map!
 SERVER: 0.022s [INFO] station: Set up station Empty (97712).
 SERVER: 0.023s [INFO] station: Adding grid 97709 to station Empty (97712)
 SERVER: 0.023s [INFO] SERVER: OOC chat has been disabled.
 Recycling: 23.7247 ms: Connecting client
 Recycling: 23.7954 ms: Idling
 SERVER: 0.029s [INFO] cfg: Robust.UnitTesting.RobustIntegrationTest+IntegrationNetManager+IntegrationNetChannel: Sending server info...
 CLIENT: 0.030s [INFO] cfg: Sending client info...
 CLIENT: 0.030s [DEBG] client: Synchronized time base: 3488: 00:01:56.2332171
 CLIENT: 0.030s [INFO] player: Changing local session from null to integration_29.
 SERVER: 0.050s [INFO] system.mind: Session integration_29 transferred to entity 97716.
 CLIENT: 0.054s [DEBG] admin: Have 21 commands available
 CLIENT: 0.054s [INFO] admin: Updated admin status: Not admin
 CLIENT: 0.055s [DEBG] client: Runlevel changed to: Connected
 CLIENT: 0.229s [DEBG] admin: Have 324 commands available
 CLIENT: 0.229s [INFO] admin: Updated admin status: True/Host/ADMIN|BAN|DEBUG|FUN|PERMISSIONS|SERVER|SPAWN|VAREDIT|MAPPING|LOGS|ROUND|QUERY|ADMINHELP|VIEWNOTES|EDITNOTES|MASSBAN|STEALTH|ADMINCHAT|PII|MODERATOR|ADMINWHO|NAMECOLOR|HOST
 CLIENT: 0.229s [DEBG] job_requirements: Received roleban info containing 0 entries.
 CLIENT: 0.231s [INFO] state: Received Full GameState: to=55493, sz=17716
 CLIENT: 0.233s [INFO] state: Resetting all entity states to tick 55493.
 CLIENT: 0.240s [INFO] player: Attaching local player to Priskake (89339/n97716, MobVox, integration_29).
 CLIENT: 0.240s [DEBG] client: Runlevel changed to: InGame
 CLIENT: 0.241s [DEBG] root: Switching to state Content.Client.Gameplay.GameplayState
 Recycling: 269.7183 ms: Done recycling
```

**Comment by ElectroJr** [comment]
AFAIK #33582 should've fixed this
