### ISSUE TITLE
MeleeChemicalInjectorComponent throws exception if hit entity is destroyed

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#3364]
```
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustT
oolbox\Robust.Shared\Utility\DebugTools.cs:line 46
   at Robust.Shared.GameObjects.Entity.TryGetComponent[T](T& component) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustToolbox\Ro
bust.Shared\GameObjects\Entity.cs:line 273
   at Content.Server.GameObjects.Components.Weapon.Melee.MeleeChemicalInjectorComponent.InjectEntities(List`1 hitEntities) in C:\Users\Pieter-Ja
n Briers\Projects\space-station-14\Content.Server\GameObjects\Components\Weapon\Melee\MeleeChemicalInjectorComponent.cs:line 51
   at Content.Server.GameObjects.Components.Weapon.Melee.MeleeChemicalInjectorComponent.HandleMessage(ComponentMessage message, IComponent compo
nent) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\Content.Server\GameObjects\Components\Weapon\Melee\MeleeChemicalInjectorComponent.
cs:line 38
   at Robust.Shared.GameObjects.Entity.SendMessage(IComponent owner, ComponentMessage message) in C:\Users\Pieter-Jan Briers\Projects\space-stat
ion-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 197
   at Robust.Shared.GameObjects.Component.SendMessage(ComponentMessage message) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustTo
olbox\Robust.Shared\GameObjects\Component.cs:line 185
   at Content.Server.GameObjects.Components.Weapon.Melee.MeleeWeaponComponent.Content.Shared.Interfaces.GameObjects.Components.IAttack.ClickAtta
ck(AttackEventArgs eventArgs) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\Content.Server\GameObjects\Components\Weapon\Melee\MeleeWe
aponComponent.cs:line 165
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.DoAttack(IEntity player, EntityCoordinates coordinates, Boolean wideAttac
k, EntityUid target) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionSystem.cs
:line 872
   at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.HandleClientUseItemInHand(ICommonSession session, EntityCoordinates coord
s, EntityUid uid) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\Content.Server\GameObjects\EntitySystems\Click\InteractionSystem.cs:li
ne 228
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass2_0.<.ctor>b__0(PointerInputCmdArgs& args) in C:\Users\Pieter-Jan Brie
rs\Projects\space-station-14\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:line 92
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(ICommonSession session, InputCmdMessage message) in C:\Users\Pieter-Ja
n Briers\Projects\space-station-14\RobustToolbox\Robust.Shared\Input\Binding\InputCmdHandler.cs:line 112
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in C:\Users\Pieter-Ja
n Briers\Projects\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySystems\InputSystem.cs:line 62
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in C:\Users\Pieter-Jan Briers\Projects\space-sta
tion-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 23
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(Object ev) in C:\Users\Pieter-Jan Briers\Projects\spa
ce-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 150
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in C:\Users\Pieter-Jan Briers\Projects\s
pace-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 284
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\Users\Pieter-Jan Briers\Projects\space-stati
on-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.cs:line 200
   at Robust.Shared.GameObjects.EntityManager.<Initialize>b__24_1(Object sender, Object systemMsg) in C:\Users\Pieter-Jan Briers\Projects\space-
station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 61
   at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) in C:\Users\Pieter-Jan Briers\Project
s\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityNetworkManager.cs:line 159
   at Robust.Server.GameObjects.ServerEntityNetworkManager.Update() in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustToolbox\Robust
.Server\GameObjects\ServerEntityNetworkManager.cs:line 54
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime, Histogram histogram) in C:\Users\Pieter-Jan Briers\Projects\space-station
-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 83
   at Robust.Server.GameObjects.ServerEntityManager.Update(Single frameTime, Histogram histogram) in C:\Users\Pieter-Jan Briers\Projects\space-s
tation-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 957
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustToolbox\Robus
t.Server\BaseServer.cs:line 564
   at Robust.Server.BaseServer.<MainLoop>b__44_1(Object sender, FrameEventArgs args) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\Rob
ustToolbox\Robust.Server\BaseServer.cs:line 408
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs
:line 192
   at Robust.Server.BaseServer.MainLoop() in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line
 414
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\Robus
tToolbox\Robust.Server\Program.cs:line 83
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustToolbox\Robust.Serv
er\Program.cs:line 50
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Robust.Server.Program.Start(String[] args, Boolean contentStart) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustToolbox\Rob
ust.Server\Program.cs:line 45
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\RobustToolbox\Robust.Server\Conten
tStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\Users\Pieter-Jan Briers\Projects\space-station-14\Content.Server\Program.cs:line 9

```

**Comment by PaulRitter** [comment]
prob just needs a check to see if the entity is deleted
