### ISSUE TITLE
Tile Migration is not working

### ISSUE THREAD

**Issue by UrPrice** [space-wizards/space-station-14#33770]
## Description
After merged https://github.com/space-wizards/space-station-14/pull/33422 when I started loading my game maps, I ran into this issue where there were tiles named `PlatingBurnt` and `FloorSteelBurnt` that were supposed to migrate when loading (doesn't matter if it's the `loadmap` command or `mapping` command) - but they ain't migrating as intended. And that's causing an error like: 

```
[INFO] con: localhost@UrPrice2:savemap 5 /Maps220/ss220-box.yml
[ERRO] con: localhost@UrPrice2: ExecuteError - savemap 5 /Maps220/ss220-box.yml:
System.ArgumentException: An item with the same key has already been added. Key: 136
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Robust.Server.GameObjects.MapLoaderSystem.WriteTileMapSection(MappingDataNode rootNode, List`1 entities) in D:\SS220\SS220_work\work\RobustToolbox\Robust.Server\GameObjects\EntitySystems\MapLoaderSystem.cs:line 1021
   at Robust.Server.GameObjects.MapLoaderSystem.GetSaveData(EntityUid uid) in D:\SS220\SS220_work\work\RobustToolbox\Robust.Server\GameObjects\EntitySystems\MapLoaderSystem.cs:line 950
   at Robust.Server.GameObjects.MapLoaderSystem.Save(EntityUid uid, String ymlPath) in D:\SS220\SS220_work\work\RobustToolbox\Robust.Server\GameObjects\EntitySystems\MapLoaderSystem.cs:line 204
   at Robust.Server.GameObjects.MapLoaderSystem.SaveMap(MapId mapId, String ymlPath) in D:\SS220\SS220_work\work\RobustToolbox\Robust.Server\GameObjects\EntitySystems\MapLoaderSystem.cs:line 226
   at Robust.Server.Console.Commands.SaveMap.Execute(IConsoleShell shell, String argStr, String[] args) in D:\SS220\SS220_work\work\RobustToolbox\Robust.Server\Console\Commands\MapCommands.cs:line 206
   at Robust.Server.Console.ServerConsoleHost.ExecuteInShell(IConsoleShell shell, String command) in D:\SS220\SS220_work\work\RobustToolbox\Robust.Server\Console\ServerConsoleHost.cs:line 126
```

Turns out, the tile migration itself ain't happening, which leads to the error of trying to add a key to the dictionary for a non-existent tile prototype. Can you please fix the tile migration so we don't have trouble saving them?

**Reproduction**
You can see this happening right now on the map `Maps/Salvages/small_cargo.yml`
Load this salvage and try save

**Screenshots**
not req

**Comment by UrPrice** [comment]
💀

**Comment by UrPrice** [comment]
@PJB3005 @DrSmugleaf FYI pls
We cant update our server for mappers with this issue, bcz in this case they cant save maps..

**Comment by PJB3005** [comment]
Do not ping staff directly

**Comment by metalgearsloth** [comment]
Wrong repo brother
