### ISSUE TITLE
Spamming disconnect/connect causes a client crash

### ISSUE THREAD

**Issue by ike709** [space-wizards/space-station-14#3623]
## Description
See tin. Only tested it with lobby enabled and before the round started.

Specific steps:
1. Start a server with lobby enabled.
2. Direct connect.
3. Disconnect.
4. Repeat steps 2-3 until client crashes.

```
[FATL] unhandled: Lidgren.Network.NetException: Got ack for message not yet sent?
   at Lidgren.Network.NetException.Assert(Boolean isOk, String message) in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetException.cs:line 61
   at Lidgren.Network.NetReliableSenderChannel.ReceiveAcknowledge(Double now, Int32 seqNr) in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetReliableSenderCha
nnel.cs:line 246
   at Lidgren.Network.NetConnection.Heartbeat(Double now, UInt32 frameCounter) in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetConnection.cs:line 255
   at Lidgren.Network.NetPeer.Heartbeat() in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetPeer.Internal.cs:line 379
   at Lidgren.Network.NetPeer.ExecutePeerShutdown() in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetPeer.Internal.cs:line 268
   at Lidgren.Network.NetPeer.NetworkLoop() in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetPeer.Internal.cs:line 236
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception. Lidgren.Network.NetException: Got ack for message not yet sent?
   at Lidgren.Network.NetException.Assert(Boolean isOk, String message) in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetException.cs:line 61
   at Lidgren.Network.NetReliableSenderChannel.ReceiveAcknowledge(Double now, Int32 seqNr) in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetReliableSenderCha
nnel.cs:line 246
   at Lidgren.Network.NetConnection.Heartbeat(Double now, UInt32 frameCounter) in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetConnection.cs:line 255
   at Lidgren.Network.NetPeer.Heartbeat() in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetPeer.Internal.cs:line 379
   at Lidgren.Network.NetPeer.ExecutePeerShutdown() in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetPeer.Internal.cs:line 268
   at Lidgren.Network.NetPeer.NetworkLoop() in C:\Users\Ike\Documents\GitHub\SS14\space-station-14\RobustToolbox\Lidgren.Network\Lidgren.Network\Lidgren.Network\NetPeer.Internal.cs:line 236
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
   ```

**Screenshots**

**Additional context**

**Comment by Visne** [comment]
Not entirely sure if this is the exact same bug, but you can replicate this more easily by using the `--connect --connect-address localhost` startup arguments, then clicking direct connect once the game starts.

**Comment by AJCM-git** [comment]
This issue is very outdated and cant be reproduced anymore with neither instructions. If someone finds new reproduction steps make a new issue

**Comment by Visne** [comment]
Then I assume it's solved, as my repro steps make it almost impossible to miss. Basically you would click direct connect when the game first opens, and then the game is already attempting to connect to a server because of the arg and then it gives an exception.
