### ISSUE TITLE
Lobby squashed when game is minimized on round restart

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#3726]
## Description

Having the game minimized when the round restarts causes the lobby UI to mess up.

Resizing the window fixes it.

**Screenshots**

![image](https://user-images.githubusercontent.com/10494922/112708111-454a2a80-8e6d-11eb-8fcc-9dfce77c6b45.png)

**Additional context**

Error log
```
[ERRO] runtime: Caught exception in "GameLoop Update"
System.InvalidOperationException: Invalid size returned from Measure()
   at Robust.Client.UserInterface.Control.Measure(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 537
   at Content.Client.UserInterface.StripeBack.MeasureOverride(Vector2 availableSize) in /home/runner/work/space-station-14/space-station-14/Content.Client/UserInterface/StripeBack.cs:line 65
   at Robust.Client.UserInterface.Control.MeasureCore(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 591
   at Robust.Client.UserInterface.Control.Measure(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 537
   at Robust.Client.UserInterface.Controls.BoxContainer.MeasureOverride(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Controls/BoxContainer.cs:line 52
   at Robust.Client.UserInterface.Control.MeasureCore(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 591
   at Robust.Client.UserInterface.Control.Measure(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 537
   at Robust.Client.UserInterface.Controls.BoxContainer.MeasureOverride(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Controls/BoxContainer.cs:line 52
   at Robust.Client.UserInterface.Control.MeasureCore(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 591
   at Robust.Client.UserInterface.Control.Measure(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 537
   at Robust.Client.UserInterface.Controls.BoxContainer.MeasureOverride(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Controls/BoxContainer.cs:line 52
   at Robust.Client.UserInterface.Control.MeasureCore(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 591
   at Robust.Client.UserInterface.Control.Measure(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 537
   at Robust.Client.UserInterface.Controls.MarginContainer.MeasureOverride(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Controls/MarginContainer.cs:line 22
   at Robust.Client.UserInterface.Control.MeasureCore(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 591
   at Robust.Client.UserInterface.Control.Measure(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 537
   at Robust.Client.UserInterface.Control.MeasureOverride(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 600
   at Robust.Client.UserInterface.Control.MeasureCore(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 591
   at Robust.Client.UserInterface.Control.Measure(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 537
   at Robust.Client.UserInterface.Controls.LayoutContainer.MeasureOverride(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Controls/LayoutContainer.cs:line 468
   at Robust.Client.UserInterface.Control.MeasureCore(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 591
   at Robust.Client.UserInterface.Control.Measure(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 537
   at Robust.Client.UserInterface.Control.MeasureOverride(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 600
   at Robust.Client.UserInterface.Control.MeasureCore(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 591
   at Robust.Client.UserInterface.Control.Measure(Vector2 availableSize) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 537
   at Robust.Client.UserInterface.UserInterfaceManager.FrameUpdate(FrameEventArgs args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 206
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController.cs:line 323
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 239
```

**Comment by ElectroJr** [comment]
This doesn't seem to happen anymore after the lobby UI changes. If there are still issues with calling `Measure()` while minimized that should probably be an engine issue.
