### ISSUE TITLE
RCD Exceptions on Live Servers

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#3780]
```
Caught exception in "Async Queued Callback" The given key '0' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Robust.Shared.Map.MapManager.GetGrid(GridId gridID) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Map/MapManager.cs:line 501
at Content.Server.GameObjects.Components.Items.RCD.RCDComponent.Content.Shared.Interfaces.GameObjects.Components.IAfterInteract.AfterInteract(AfterInteractEventArgs eventArgs) in /home/runner/work/space-station-14/space-station-14/Content.Server/GameObjects/Components/Items/RCD/RCDComponent.cs:line 102
at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.DoAfterInteract(IEntity weapon, AfterInteractEventArgs afterAttackEventArgs) in /home/runner/work/space-station-14/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 781
at Content.Server.GameObjects.EntitySystems.Click.InteractionSystem.Interaction(IEntity user, IEntity weapon, IEntity attacked, EntityCoordinates clickLocation) in /home/runner/work/space-station-14/space-station-14/Content.Server/GameObjects/EntitySystems/Click/InteractionSystem.cs:line 460
at Content.Server.GameObjects.Components.GUI.InventoryComponent.HandleInventoryMessage(ClientInventoryMessage msg) in /home/runner/work/space-station-14/space-station-14/Content.Server/GameObjects/Components/GUI/InventoryComponent.cs:line 542
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
at Robust.Shared.Asynchronous.RobustSynchronizationContext.ProcessPendingTasks() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Asynchronous/RobustSynchronizationContext.cs:line 48
```
probably causes RCD to break and then cause
```
Player named <Player> clicked on object RCD that isn't currently on the map somehow 
```

**Comment by mirrorcult** [comment]
this is not really relevant anymore exception doesnt exist with that name now or is fixed
