### ISSUE TITLE
ViewVariables crashes when trying to view SolutionContainerComponent

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#3925]
## Description
to repro:
- Spawn a bucket
- VV it, go to servercomponents, try to view its SolutionContainerComponent
- die in real life
not sure if this is exclusive to solutioncontainer

stack trace
```
[FATL] unhandled: System.Collections.Generic.KeyNotFoundException: The given key '60' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Client.UserInterface.Controls.OptionButton.GetIdx(Int32 id) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\UserInterface\Controls\OptionButton.cs:line 241
   at Robust.Client.UserInterface.Controls.OptionButton.SelectId(Int32 id) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\UserInterface\Controls\OptionButton.cs:line 230
   at Robust.Client.ViewVariables.Editors.VVPropEditorEnum.MakeUI(Object value) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\ViewVariables\Editors\VVPropEditorEnum.cs:line 25
   at Robust.Client.ViewVariables.VVPropEditor.Initialize(Object value, Boolean readOnly) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\ViewVariables\VVPropEditor.cs:line 21
   at Robust.Client.ViewVariables.ViewVariablesPropertyControl.SetProperty(MemberData member) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\ViewVariables\ViewVariablesPropertyControl.cs:line 90
   at Robust.Client.ViewVariables.Traits.ViewVariablesTraitMembers.Refresh() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\ViewVariables\Traits\ViewVariablesTraitMembers.cs:line 69
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Robust.Shared.Asynchronous.RobustSynchronizationContext.ProcessPendingTasks() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Asynchronous\RobustSynchronizationContext.cs:line 48
   at Robust.Shared.Asynchronous.TaskManager.ProcessPendingTasks() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Asynchronous\TaskManager.cs:line 22
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 339
   at Robust.Client.GameController.<StartupContinue>b__48_2(Object sender, FrameEventArgs args) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 176
   at Robust.Shared.Timing.GameLoop.Run() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 159
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 131
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 116
   at Robust.Client.GameController.<>c__DisplayClass77_0.<Run>b__0() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 83
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '60' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Client.UserInterface.Controls.OptionButton.GetIdx(Int32 id) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\UserInterface\Controls\OptionButton.cs:line 241
   at Robust.Client.UserInterface.Controls.OptionButton.SelectId(Int32 id) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\UserInterface\Controls\OptionButton.cs:line 230
   at Robust.Client.ViewVariables.Editors.VVPropEditorEnum.MakeUI(Object value) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\ViewVariables\Editors\VVPropEditorEnum.cs:line 25
   at Robust.Client.ViewVariables.VVPropEditor.Initialize(Object value, Boolean readOnly) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\ViewVariables\VVPropEditor.cs:line 21
   at Robust.Client.ViewVariables.ViewVariablesPropertyControl.SetProperty(MemberData member) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\ViewVariables\ViewVariablesPropertyControl.cs:line 90
   at Robust.Client.ViewVariables.Traits.ViewVariablesTraitMembers.Refresh() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\ViewVariables\Traits\ViewVariablesTraitMembers.cs:line 69
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Robust.Shared.Asynchronous.RobustSynchronizationContext.ProcessPendingTasks() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Asynchronous\RobustSynchronizationContext.cs:line 48
   at Robust.Shared.Asynchronous.TaskManager.ProcessPendingTasks() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Asynchronous\TaskManager.cs:line 22
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 339
   at Robust.Client.GameController.<StartupContinue>b__48_2(Object sender, FrameEventArgs args) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 176
   at Robust.Shared.Timing.GameLoop.Run() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 159
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 131
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 116
   at Robust.Client.GameController.<>c__DisplayClass77_0.<Run>b__0() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 83
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by mirrorcult** [comment]
ok i cant get it to always crash but it does sometimes and i'm not sure why

**Comment by Ygg01** [comment]
@mirrorcult It's caused by BitFlags. SolutionContainer has Capabilities which are BitFlags. VVProp menu expects enum variants to be exclusive. Which isn't true for BitFlags.

**Comment by AJCM-git** [comment]
Seems to have been fixed
