### ISSUE TITLE
Deletion fix broke deletion

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14#412]
The PR https://github.com/space-wizards/space-station-14/pull/401 broke deletion, at the very least from the clientside placement manager eraser function. Deletion causes the client to terminate with an argument exception. Here is the stack trace of where it fails

```
Unhandled Exception: System.ArgumentException: No entity with ID 284 exists.
   at SS14.Shared.GameObjects.EntityManager.DeleteEntity(Int32 entityUid) in C:\Users\Age\Desktop\ss14\SS14.Shared\GameObjects\EntityManager.cs:line 148
   at SS14.Client.GameObjects.ClientEntityManager.ApplyEntityStates(IEnumerable`1 entityStates, Single serverTime) in C:\Users\Age\Desktop\ss14\SS14.Client\GameObjects\ClientEntityManager.cs:line 133
   at SS14.Client.GameStates.GameStateManager.ApplyGameState(GameState gameState) in C:\Users\Age\Desktop\ss14\SS14.Client\GameStates\GameStateManager.cs:line 87
   at SS14.Client.GameStates.GameStateManager.HandleStateUpdateMessage(MsgStateUpdate message) in C:\Users\Age\Desktop\ss14\SS14.Client\GameStates\GameStateManager.cs:line 60
   at SS14.Client.GameController.<>c.<Run>b__13_1(NetMessage message) in C:\Users\Age\Desktop\ss14\SS14.Client\GameController.cs:line 109
   at SS14.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in C:\Users\Age\Desktop\ss14\SS14.Shared\Network\NetManager.cs:line 370
   at SS14.Shared.Network.NetManager.ProcessPackets() in C:\Users\Age\Desktop\ss14\SS14.Shared\Network\NetManager.cs:line 176
   at SS14.Client.GameController.Update(FrameEventArgs e) in C:\Users\Age\Desktop\ss14\SS14.Client\GameController.cs:line 242
   at SS14.Client.GameController.Run() in C:\Users\Age\Desktop\ss14\SS14.Client\GameController.cs:line 164
   at SS14.Client.Program.Main() in C:\Users\Age\Desktop\ss14\SS14.Client\Program.cs:line 64
```

**Comment by clusterfack** [comment]
Fixed by https://github.com/space-wizards/space-station-14/pull/413
