### ISSUE TITLE
Lord Singuloth crashes the game after it crit/kills you.

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#4162]
## Description

How replicate: 
Spawn a Singularity, get close to it, get killed by it. This was made in debug mode.
**Screenshots**

**Additional context**
```System.InvalidOperationException
  HResult=0x80131509
  Mensaje = Collection was modified; enumeration operation may not execute.
  Origen = System.Private.CoreLib
  Stack trace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Robust.Shared.GameObjects.ComponentManager.<GetComponents>d__50`1.MoveNext() in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\ComponentManager.cs:line 465
   at Content.Server.GameObjects.EntitySystems.StationEvents.RadiationPulseSystem.Update(Single frameTime) in C:\Users\User\Documents\GitHub\space-station-14\Content.Server\GameObjects\EntitySystems\StationEvents\RadiationPulseSystem.cs:line 57
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime) in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 272
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Histogram histogram) in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 109
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Histogram histogram) in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 128
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 626
   at Robust.Server.BaseServer.<MainLoop>b__46_1(Object sender, FrameEventArgs args) in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 469
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 192
   at Robust.Server.BaseServer.MainLoop() in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 475
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart) in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 80
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in C:\Users\User\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 50
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by AJCM-git** [comment]
This no longer seems to happen in debug nor release anymore
