### ISSUE TITLE
[BUG] Restarting a round from the admin menu results in a client crash

### ISSUE THREAD

**Issue by iamgreaser** [space-wizards/space-station-14#4214]
## Description
When running a local server and local client, doing F7 Admin menu -> Round -> Restart Round results in the client crashing with a traceback complaining about a `ComponentStateApplyException` exception. Sometimes I can "play" the round for a bit, but it does crash within a few seconds.

If I leave the server running and relaunch the client, doing the same things as above, it still crashes when I do a Restart Round.

**Additional context**
Git commit 64813d9c56d607f52f9464f90a8d86acff670eb7
Running on Void Linux
.NET SDK 5.0.301

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     void
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/ben/Downloads/libs/dotnet/sdk/5.0.301/

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [/home/ben/Downloads/libs/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [/home/ben/Downloads/libs/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [/home/ben/Downloads/libs/dotnet/shared/Microsoft.NETCore.App]
```

**Traceback**
```
[DEBG] root: Server: Welcome to Space Station 14! If this is your first time checking out the game, be sure to check out the tutorial in the top left!
[DEBG] root: Server: You're a new assistant. Do your best!
[WARN] eng: MainLoop: Cannot keep up!
[FATL] unhandled: Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=emergency closet (6622, LockerEmergencyFilledRandom), comp=ContainerContainer
 ---> System.Collections.Generic.KeyNotFoundException: The given key '10958' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 209
   at Robust.Shared.Containers.ContainerManagerComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Shared/Containers/ContainerManagerComponent.cs:line 124
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityEventBus bus, EntityState curState, EntityState nextState) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 594
   --- End of inner exception stack trace ---
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityEventBus bus, EntityState curState, EntityState nextState) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 603
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(EntityState[] curEntStates, IEnumerable`1 deletions, EntityState[] nextEntStates) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 468
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 401
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 217
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 372
   at Robust.Client.GameController.<StartupContinue>b__48_0(Object sender, FrameEventArgs args) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 159
   at Robust.Shared.Timing.GameLoop.Run() in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 197
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 131
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 116
   at Robust.Client.GameController.<>c__DisplayClass77_0.<Run>b__0() in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 83
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception. Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=emergency closet (6622, LockerEmergencyFilledRandom), comp=ContainerContainer
 ---> System.Collections.Generic.KeyNotFoundException: The given key '10958' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 209
   at Robust.Shared.Containers.ContainerManagerComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Shared/Containers/ContainerManagerComponent.cs:line 124
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityEventBus bus, EntityState curState, EntityState nextState) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 594
   --- End of inner exception stack trace ---
   at Robust.Client.GameStates.ClientGameStateManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityEventBus bus, EntityState curState, EntityState nextState) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 603
   at Robust.Client.GameStates.ClientGameStateManager.ApplyEntityStates(EntityState[] curEntStates, IEnumerable`1 deletions, EntityState[] nextEntStates) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 468
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 401
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 217
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 372
   at Robust.Client.GameController.<StartupContinue>b__48_0(Object sender, FrameEventArgs args) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.cs:line 159
   at Robust.Shared.Timing.GameLoop.Run() in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 197
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 131
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 116
   at Robust.Client.GameController.<>c__DisplayClass77_0.<Run>b__0() in /home/ben/Downloads/gamez/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 83
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by mirrorcult** [comment]
probably related to space-wizards/RobustToolbox#1827, running in release mode should at least stop it from crashing (although since its local you can just rerun the game in debug anyway, so)

**Comment by Acruid** [comment]
An instance of https://github.com/space-wizards/RobustToolbox/issues/1827.

**Comment by iamgreaser** [comment]
Alright, thanks for that.
