### ISSUE TITLE
Crayon exception

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4222]
I just threw it around a bit, picked it up, used it and exception threw. I was on Y's MappedStorageVisualizer branch but I don't think that'd affect it.

```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Robust.Shared.Maths.Color'.
   at Robust.Client.GameObjects.AppearanceComponent.TryGetData[T](Object key, T& data) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Appearance\AppearanceComponent.cs:line 65
   at Robust.Client.GameObjects.AppearanceComponent.TryGetData[T](Enum key, T& data) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Appearance\AppearanceComponent.cs:line 53
   at Content.Client.Crayon.CrayonDecalVisualizer.OnChangeData(AppearanceComponent component) in E:\Programming\space-station-14\Content.Client\Crayon\CrayonDecalVisualizer.cs:line 22
   at Robust.Client.GameObjects.AppearanceSystem.FrameUpdate(Single frameTime) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\AppearanceSystem.cs:line 26
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in E:\Programming\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 275
   at Robust.Shared.GameObjects.EntityManager.FrameUpdate(Single frameTime) in E:\Programming\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 139
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 394
   at Robust.Client.GameController.<StartupContinue>b__48_3(Object sender, FrameEventArgs args) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 183
   at Robust.Shared.Timing.GameLoop.Run() in E:\Programming\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 239
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 131
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 116
   at Robust.Client.GameController.<>c__DisplayClass77_0.<Run>b__0() in E:\Programming\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 83
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by SweptWasTaken** [comment]
Not really sure when these broke but it wasn't recent.

**Comment by GalacticChimp** [comment]
I'll try this one, just spawning and using a crayon is enough to trigger the exception
