### ISSUE TITLE
Anchoring and Unanchoring something crashes the server

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4572]
## Description

To replicate load into Saltern, spawn a wrench and anchor then unanchor the vending machine closest to you.

The server should crash.

**Additional context**

```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 31
   at Robust.Shared.GameObjects.EntityLookup.Update() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\EntityLookup.cs:line 245
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 617
   at Robust.Server.BaseServer.<SetupMainLoop>b__47_1(Object sender, FrameEventArgs args) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 481
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 192
   at Robust.Server.BaseServer.MainLoop() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 502
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 80
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 50
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 45
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\Users\Swept\Desktop\Fork\space-station-14\Content.Server\Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 31
   at Robust.Shared.GameObjects.EntityLookup.Update() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\EntityLookup.cs:line 245
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 617
   at Robust.Server.BaseServer.<SetupMainLoop>b__47_1(Object sender, FrameEventArgs args) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 481
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 192
   at Robust.Server.BaseServer.MainLoop() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 502
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 80
   at Robust.Server.Program.<>c__DisplayClass2_0.<Start>b__0() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 50
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 45
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\Users\Swept\Desktop\Fork\space-station-14\Content.Server\Program.cs:line 9
```

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/commit/49c6c0c9d865b8293f0e8a2035ab8d21dbcd5a96
