### ISSUE TITLE
Chemical dispenser crash

### ISSUE THREAD

**Issue by unusualcrow** [space-wizards/space-station-14#460]
Threw some hydrogen, potassium, and oxygen in a dispenser and everything died

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Content.Client
  StackTrace:
   at Content.Client.GameObjects.Components.Chemistry.ReagentDispenserWindow.UpdateContainerInfo(ReagentDispenserBoundUserInterfaceState state, String highlightedReagentId) in E:\space-station-14\Content.Client\GameObjects\Components\Chemistry\ReagentDispenserWindow.cs:line 240
   at Content.Client.GameObjects.Components.Chemistry.ReagentDispenserWindow.UpdateState(BoundUserInterfaceState state) in E:\space-station-14\Content.Client\GameObjects\Components\Chemistry\ReagentDispenserWindow.cs:line 170
   at Content.Client.GameObjects.Components.Chemistry.ReagentDispenserBoundUserInterface.UpdateState(BoundUserInterfaceState state) in E:\space-station-14\Content.Client\GameObjects\Components\Chemistry\ReagentDispenserBoundUserInterface.cs:line 76
   at Robust.Client.GameObjects.Components.UserInterface.BoundUserInterface.InternalReceiveMessage(BoundUserInterfaceMessage message) in E:\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\UserInterface\ClientUserInterfaceComponent.cs:line 175
   at Robust.Client.GameObjects.Components.UserInterface.ClientUserInterfaceComponent.HandleMessage(ComponentMessage message, INetChannel netChannel, IComponent component) in E:\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\UserInterface\ClientUserInterfaceComponent.cs:line 74
   at Robust.Shared.GameObjects.EntityManager.DispatchComponentMessage(MsgEntity msgEntity) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 522
   at Robust.Shared.GameObjects.EntityManager.ProcessEntityMessage(MsgEntity msgEntity) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 507
   at Robust.Shared.GameObjects.EntityManager.HandleEntityNetworkMessage(MsgEntity msg) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 470
   at Robust.Client.GameObjects.ClientEntityNetworkManager.HandleEntityNetworkMessage(MsgEntity message) in E:\space-station-14\RobustToolbox\Robust.Client\GameObjects\ClientEntityNetworkManager.cs:line 74
   at Robust.Shared.Network.NetManager.<>c__DisplayClass57_0`1.<RegisterNetMessage>b__0(NetMessage msg) in E:\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 615
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in E:\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 600
   at Robust.Shared.Network.NetManager.ProcessPackets() in E:\space-station-14\RobustToolbox\Robust.Shared\Network\NetManager.cs:line 266
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in E:\space-station-14\RobustToolbox\Robust.Client\GameController.cs:line 242
   at Robust.Client.GameController.<MainLoop>b__59_0(Object sender, FrameEventArgs args) in E:\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 62
   at Robust.Shared.Timing.GameLoop.Run() in E:\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 180
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in E:\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 91
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args) in E:\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 37
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Robust.Client.GameController.Main(String[] args) in E:\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 22

```

**Comment by Ephememory** [comment]
Failed to repro 🤔

**Comment by Moneyl** [comment]
Same. Based on the trace it was caused by `proto` being null [here](https://github.com/space-wizards/space-station-14/blob/d63c879404e38decd028ad70fcf5127b5c74ab94/Content.Client/GameObjects/Components/Chemistry/ReagentDispenserWindow.cs#L240). We should at least have a null check for `proto` there. So it'd now be
```cs
                if (proto != null && proto.ID == highlightedReagentId)
                {
                     ...
```
Was this on a version you built or a version you got from the installer? I didn't test it on the installer version yet.

**Comment by Ephememory** [comment]
Yeah I was gonna just add a nullcheck lol

**Comment by unusualcrow** [comment]
Happened on built version
