### ISSUE TITLE
Closing the admin menu with windows open causes the windows to close and never be openable until a client restart

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4686]
## Description

To replicate open the admin window, open the spawn entities window, close the admin menu without closing the spawn entities window and then open the admin menu and try to open the spawn entities window.

**Comment by PaulRitter** [comment]
swept you cant just put replicated on issues because you yourself replicated them

![image](https://user-images.githubusercontent.com/16618384/135322197-b24001e1-fa0d-4201-9915-f82d2806b141.png)

**Comment by Zumorica** [comment]
I cannot replicate this.

**Comment by PaulRitter** [comment]
absolutely ratio'd

**Comment by SweptWasTaken** [comment]
Try this

1. Open admin menu with F7
2. Open spawn entities panel
3. Close admin menu with F7 (It should make spawn entities window vanish).
4. Open admin menu again with F7 and open spawn entities panel.

<details>
  <summary>Stack</summary>

```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Child is disposed.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 46
   at Robust.Client.UserInterface.Control.AddChild(Control child) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\UserInterface\Control.cs:line 575
   at Robust.Client.UserInterface.CustomControls.BaseWindow.Open() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\UserInterface\CustomControls\BaseWindow.cs:line 224
   at Robust.Client.UserInterface.CustomControls.BaseWindow.OpenCentered() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\UserInterface\CustomControls\BaseWindow.cs:line 245
   at Content.Client.Administration.Managers.AdminMenuManager.OpenCommand(SS14Window window) in C:\Users\Swept\Desktop\Fork\space-station-14\Content.Client\Administration\Managers\AdminMenuManager.cs:line 110
   at Content.Client.Administration.UI.Tabs.AdminbusTab.AdminbusTab.SpawnEntitiesButtonOnOnPressed(ButtonEventArgs obj) in C:\Users\Swept\Desktop\Fork\space-station-14\Content.Client\Administration\UI\Tabs\AdminbusTab\AdminbusTab.xaml.cs:line 34
   at Robust.Client.UserInterface.Controls.BaseButton.KeyBindUp(GUIBoundKeyEventArgs args) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\UserInterface\Controls\BaseButton.cs:line 264
   at Robust.Client.UserInterface.UserInterfaceManager.<>c.<KeyBindUp>b__95_0(Control c, GUIBoundKeyEventArgs ev) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 436
   at Robust.Client.UserInterface.UserInterfaceManager._doGuiInput[T](Control control, T guiEvent, Action`2 action, Boolean ignoreStop) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 841
   at Robust.Client.UserInterface.UserInterfaceManager.KeyBindUp(BoundKeyEventArgs args) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 436
   at Robust.Client.UserInterface.UserInterfaceManager.OnUIKeyBindStateChanged(BoundKeyEventArgs args) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\UserInterface\UserInterfaceManager.cs:line 986
   at Robust.Client.Input.InputManager.SetBindState(KeyBinding binding, BoundKeyState state, Boolean uiOnly) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 382
   at Robust.Client.Input.InputManager.UpBind(KeyBinding binding) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 357
   at Robust.Client.Input.InputManager.KeyUp(KeyEventArgs args) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\Input\InputManager.cs:line 308
   at Robust.Client.GameController.KeyUp(KeyEventArgs keyEvent) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Input.cs:line 20
   at Robust.Client.Graphics.Clyde.Clyde.DispatchSingleEvent(DEventBase ev) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Clyde.Events.cs:line 50
   at Robust.Client.Graphics.Clyde.Clyde.DispatchEvents() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Clyde.Events.cs:line 31
   at Robust.Client.Graphics.Clyde.Clyde.ProcessInput(FrameEventArgs frameEventArgs) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\Graphics\Clyde\Clyde.Windowing.cs:line 371
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 410
   at Robust.Client.GameController.<StartupContinue>b__45_2(Object sender, FrameEventArgs args) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 180
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 159
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 129
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 114
   at Robust.Client.GameController.<>c__DisplayClass79_0.<Run>b__0() in C:\Users\Swept\Desktop\Fork\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 81
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```
 
</details>

**Comment by AJCM-git** [comment]
Replicated this one. You need to open the spawn entities menu **from** the admind menu to replicate

**Comment by SweptWasTaken** [comment]
Fixed.
