### ISSUE TITLE
Controlmob an airlock then click spams exceptions for game states

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4711]
![image](https://user-images.githubusercontent.com/31366439/135477323-6f7f8878-69b1-444f-b5ee-b9ac381d7ec1.png)

**Comment by Efruit** [comment]
Replicated, but... not in Client. Mine trips an assert elsewhere, soft-locking the game for the client that controlmob'd the door.
<details><summary>Traceback</summary>

```
[ERRO] PVS: Caught exception while generating mail.                                                                                                                                                                                                                                                                           
Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.                                                                                                                                                                                                        
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /home/steam/SS14/src/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 31                                                                                                                                                           
   at Robust.Server.GameStates.EntityViewCulling.GenerateEntityStates(List`1 entityStates, ICommonSession session, GameTick fromTick, HashSet`1 currentSet, List`1 deletions) in /home/steam/SS14/src/space-station-14/RobustToolbox/Robust.Server/GameStates/EntityViewCulling.cs:line 445                                   
   at Robust.Server.GameStates.EntityViewCulling.CalculateEntityStates(ICommonSession session, GameTick fromTick, GameTick toTick) in /home/steam/SS14/src/space-station-14/RobustToolbox/Robust.Server/GameStates/EntityViewCulling.cs:line 232
   at Robust.Server.GameStates.ServerGameStateManager.<>c__DisplayClass29_0.<SendGameStateUpdate>g__SendStateUpdate|0(IPlayerSession session) in /home/steam/SS14/src/space-station-14/RobustToolbox/Robust.Server/GameStates/ServerGameStateManager.cs:line 204
   at Robust.Server.GameStates.ServerGameStateManager.<>c__DisplayClass29_0.<SendGameStateUpdate>b__1(IPlayerSession session) in /home/steam/SS14/src/space-station-14/RobustToolbox/Robust.Server/GameStates/ServerGameStateManager.cs:line 241
```
</details>

It looks like

https://github.com/space-wizards/RobustToolbox/blob/8d0070b5c39c1c829f7d21b5ded28c9713923da6/Robust.Server/GameStates/EntityViewCulling.cs#L446

assumes that the player is never going to be anchored, which doors obviously are. I was also able to trigger the same behavior by anchoring the player's TransformComponent through VV.
