### ISSUE TITLE
Issue with AME causing strobing

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4761]
## Description

From MetroReactive on Discord
> I made the antimater machine, I put fuel in it, I wanted to see what would happen if i injected 500 at a time, ship started to shake, I panicked, I checked the gravitation device to see if anyone was spamming it, No one was there to my knowledge, I ran back in and I didnt know if it was the machine that did it or if it was me so i put more fuel in it to see, It started to shaked again, I was going to turn it off but then i was killed.

Will update with proper replication steps.

**Comment by TimrodDX** [comment]
I have tested this on local, and I can reproduce every time. Here are the exact steps I used.

Step 1. Build an AME in Engineering. I used the exact spot MetroReactive told me they used, which is in the AME room. 

![image](https://user-images.githubusercontent.com/7907891/135777803-c44c8b1f-61d3-4fe2-a9db-8dc73352b7ed.png)

Step 2.  Crank the control unit to 500 input, put in the fuel, and then turn it on.

Step 3. The entire station's power grid will rapidly fluctuate on and off, causing constant shaking from the gravity generator, as well as an extremely loud noise from the gravgen's on/off sounds layering over each other. The lights on the station will also flash rapidly.

![image](https://user-images.githubusercontent.com/7907891/135777866-6d107f3f-2272-454f-b2e0-92947b4f7f54.png)

**Comment by 20kdc** [comment]
I tried it and got this:
```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in /home/20kdc/Documents/External/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 31
   at Content.Server.Power.Pow3r.BatteryRampPegSolver.Tick(Single frameTime, PowerState state) in /home/20kdc/Documents/External/space-station-14/Content.Server/Power/Pow3r/BatteryRampPegSolver.cs:line 129
   at Content.Server.Power.EntitySystems.PowerNetSystem.Update(Single frameTime) in /home/20kdc/Documents/External/space-station-14/Content.Server/Power/EntitySystems/PowerNetSystem.cs:line 190
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime) in /home/20kdc/Documents/External/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 232
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Histogram histogram) in /home/20kdc/Documents/External/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 103
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Histogram histogram) in /home/20kdc/Documents/External/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 128
```
(rest omitted for brevity)

It's definitely doing *something*

**Comment by 20kdc** [comment]
```
$ lua
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio> 500 * 20000
10000000
> 0x100000000
4294967296
> 500 * 500 * 20000
5000000000
> 0x100000000
4294967296
> 
```
\> AME energy calculations are done in floats and then converted into an int

Oh dear. Ooooh dear.
