### ISSUE TITLE
Shooting things throws an exception

### ISSUE THREAD

**Issue by unusualcrow** [space-wizards/space-station-14#488]
Shooting with a gun that uses bullets throws exception from physics system

```
Robust.Shared.Utility.DebugAssertException
  HResult=0x80131500
  Message=Tried to get component on a deleted entity.
  Source=Robust.Shared
  StackTrace:
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in E:\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 48
   at Robust.Shared.GameObjects.Entity.GetComponent[T]() in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity.cs:line 262
   at Robust.Server.GameObjects.EntitySystems.PhysicsSystem.DoMovement(IEntity entity, Single frameTime) in E:\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySystems\PhysicsSystem.cs:line 112
   at Robust.Server.GameObjects.EntitySystems.PhysicsSystem.Update(Single frameTime) in E:\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySystems\PhysicsSystem.cs:line 48
   at Robust.Shared.GameObjects.EntitySystemManager.Update(Single frameTime) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 151
   at Robust.Shared.GameObjects.EntityManager.Update(Single frameTime) in E:\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 102
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in E:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 364
   at Robust.Server.BaseServer.<MainLoop>b__34_0(Object sender, FrameEventArgs args) in E:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 267
   at Robust.Shared.Timing.GameLoop.Run() in E:\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 180
   at Robust.Server.BaseServer.MainLoop() in E:\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 270
   at Robust.Server.Program.ParsedMain(CommandLineArgs args) in E:\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 48
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Robust.Server.Program.Main(String[] args) in E:\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 19

```

**Comment by Moneyl** [comment]
Was this fixed? Not able to reproduce it now.

**Comment by Acruid** [comment]
Resolved https://github.com/space-wizards/RobustToolbox/commit/a69738a7a4982e9cd4d9635aec0484dc8c3bdb40.
