### ISSUE TITLE
Exception if you disconnect from server while placement is active.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#494]
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '2' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.Map.MapManager.GetGrid(GridId gridID) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Shared/Map/MapManager.cs:line 219
   at Robust.Client.Placement.PlacementMode.Render(DrawingHandleWorld handle) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/Placement/PlacementMode.cs:line 110
   at Robust.Client.Placement.PlacementManager.Render(DrawingHandleWorld handle) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/Placement/PlacementManager.cs:line 536
   at Robust.Client.Placement.PlacementManager.PlacementOverlay.Draw(DrawingHandleBase handle) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/Placement/PlacementOverlay.cs:line 22
   at Robust.Client.Graphics.Overlays.Overlay.ClydeRender(IRenderHandle renderHandle) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/Graphics/Overlays/Overlay.cs:line 99
   at Robust.Client.Graphics.Clyde.Clyde.<Render>g__RenderOverlays|171_0(OverlaySpace space) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Rendering.cs:line 106
   at Robust.Client.Graphics.Clyde.Clyde.Render() in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.Rendering.cs:line 218
   at Robust.Client.GameController.<MainLoop>b__59_1(Object sender, FrameEventArgs args) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 71
   at Robust.Shared.Timing.GameLoop.Run() in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 236
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 91
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 37
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Robust.Client.GameController.Main(String[] args) in /ssdhome/pj/Projects/space-station-14-content/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 22
```

**Comment by PJB3005** [comment]
`GameScreen` is now part of content so I feel this belongs here.

Just make placement get shut down correctly when the `GameScreen` gets switched out of, I'd say.

**Comment by SweptWasTaken** [comment]
Cannot reproduce
