### ISSUE TITLE
Explosions cause errors

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#602]
`[ERRO] runtime: Caught exception in GameLoop Update: System.ArithmeticException: Function does not accept floating point Not-a-Number values.
   at System.Math.Sign(Single value)
   at Content.Client.GameObjects.Components.Mobs.CameraRecoilComponent.FrameUpdate(Single frameTime)
   at Content.Client.GameObjects.EntitySystems.CameraRecoilSystem.FrameUpdate(Single frameTime)
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 157
   at Content.Client.State.GameScreen.FrameUpdate(FrameEventArgs e)
   at Robust.Client.GameController._frameProcessMain(FrameEventArgs frameEventArgs) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController.cs:line 271
   at Robust.Shared.Timing.GameLoop.Run() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 222`

**Comment by PJB3005** [comment]
This happens specifically when you let a bomb explode in your own hand. The code tries to calculate a direction to kick your camera in but because the relative distance is 0 it ends up with NaN instead.

![image](https://user-images.githubusercontent.com/8107459/73989238-743dce00-4945-11ea-803f-5ae5fd7032f0.png)
