### ISSUE TITLE
Chat sanitizer explodes when sending only a smiley over radio.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#6104]
## Description
Steps to reproduce:
1. Type `;lol`, `;:)`, `;:(` or any other smiley into chat.
2. Say command fails to execute!

```
[ERRO] con: localhost@JoeGenero: ExecuteError - say ";lol":
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at Content.Server.Chat.Managers.ChatManager.EntitySay(EntityUid source, String message, Boolean hideChat) in /home/vera/Projects/space-station-14/Content.Server/Chat/Managers/ChatManager.cs:line 169
   at Content.Server.Chat.Commands.SayCommand.Execute(IConsoleShell shell, String argStr, String[] args) in /home/vera/Projects/space-station-14/Content.Server/Chat/Commands/SayCommand.cs:line 68
   at Robust.Server.Console.ServerConsoleHost.ExecuteInShell(IConsoleShell shell, String command) in /home/vera/Projects/space-station-14/RobustToolbox/Robust.Server/Console/ServerConsoleHost.cs:line 100
```

This does not happen when you type things like `;haha lol` or just `lol` (or any other smiley) over local chat.

cc @moonheart08

**Comment by moonheart08** [comment]
wh
