### ISSUE TITLE
Putting human or slime on butcher spike causes crash

### ISSUE THREAD

**Issue by Peptide90** [space-wizards/space-station-14#6170]
## Description
TESTED ON LOCAL.

When putting a slime or human mob on a spike (the interaction is janky anyway and takes a few attemps) it will crash the game with a fatal error.

Error in console is related to pulled joints being deleted.
Scroll down for more relevant server fatal error as original stacktrace might be debug stuff.

stacktrace:
`Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 31
   at Robust.Shared.Physics.SharedBroadphaseSystem.FindNewContacts(MapId mapId) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Physics\SharedBroadphaseSystem.cs:line 232
   at Robust.Shared.Physics.Dynamics.SharedPhysicsMapComponent.Step(Single frameTime, Boolean prediction) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Physics\Dynamics\SharedPhysicsMapComponent.cs:line 227
   at Robust.Shared.GameObjects.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line 396
   at Robust.Server.GameObjects.PhysicsSystem.Update(Single frameTime) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\GameObjects\EntitySystems\PhysicsSystem.cs:line 50
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 277
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 116
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 141
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 618
   at Robust.Server.BaseServer.<SetupMainLoop>b__54_1(Object sender, FrameEventArgs args) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 488
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 192
   at Robust.Server.BaseServer.MainLoop() in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 509
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 72
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 43
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\Users\user\Documents\GitHub\space-station-14\Content.Server\Program.cs:line 9`

### Console error
`[DEBG] physics: Removed joint pull-joint-8575
[ERRO] physics: Deleted body 8575D made it to FindNewContacts; this should ne
ver happen!
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of ty
pe 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\Users\
user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Utility\D
ebugTools.cs:line 31
   at Robust.Shared.Physics.SharedBroadphaseSystem.FindNewContacts(MapId mapI
d) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.S
hared\Physics\SharedBroadphaseSystem.cs:line 232
   at Robust.Shared.Physics.Dynamics.SharedPhysicsMapComponent.Step(Single fr
ameTime, Boolean prediction) in C:\Users\user\Documents\GitHub\space-station
-14\RobustToolbox\Robust.Shared\Physics\Dynamics\SharedPhysicsMapComponent.cs
:line 227
   at Robust.Shared.GameObjects.SharedPhysicsSystem.SimulateWorld(Single delt
aTime, Boolean prediction) in C:\Users\user\Documents\GitHub\space-station-1
4\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line
 396
   at Robust.Server.GameObjects.PhysicsSystem.Update(Single frameTime) in C:\
Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\Gam
eObjects\EntitySystems\PhysicsSystem.cs:line 50
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTi
me, Boolean noPredictions) in C:\Users\user\Documents\GitHub\space-station-1
4\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 277
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Bo
olean noPredictions, Histogram histogram) in C:\Users\user\Documents\GitHub\
space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:lin
e 116
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTi
me, Boolean noPredictions, Histogram histogram) in C:\Users\user\Documents\G
itHub\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityMa
nager.cs:line 141
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Us
ers\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseS
erver.cs:line 618
   at Robust.Server.BaseServer.<SetupMainLoop>b__54_1(Object sender, FrameEve
ntArgs args) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbo
x\Robust.Server\BaseServer.cs:line 488
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\user\Documents\GitHub\
space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 192
   at Robust.Server.BaseServer.MainLoop() in C:\Users\user\Documents\GitHub\
space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 509
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentS
tart, ServerOptions options) in C:\Users\user\Documents\GitHub\space-station
-14\RobustToolbox\Robust.Server\Program.cs:line 72
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boole
an contentStart) in C:\Users\user\Documents\GitHub\space-station-14\RobustTo
olbox\Robust.Server\Program.cs:line 43
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\user\Docum
ents\GitHub\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line
 10
   at Content.Server.Program.Main(String[] args) in C:\Users\user\Documents\
GitHub\space-station-14\Content.Server\Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of
 type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\Users\
user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Shared\Utility\D
ebugTools.cs:line 31
   at Robust.Shared.Physics.SharedBroadphaseSystem.FindNewContacts(MapId mapI
d) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.S
hared\Physics\SharedBroadphaseSystem.cs:line 232
   at Robust.Shared.Physics.Dynamics.SharedPhysicsMapComponent.Step(Single fr
ameTime, Boolean prediction) in C:\Users\user\Documents\GitHub\space-station
-14\RobustToolbox\Robust.Shared\Physics\Dynamics\SharedPhysicsMapComponent.cs
:line 227
   at Robust.Shared.GameObjects.SharedPhysicsSystem.SimulateWorld(Single delt
aTime, Boolean prediction) in C:\Users\user\Documents\GitHub\space-station-1
4\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line
 396
   at Robust.Server.GameObjects.PhysicsSystem.Update(Single frameTime) in C:\
Users\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\Gam
eObjects\EntitySystems\PhysicsSystem.cs:line 50
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTi
me, Boolean noPredictions) in C:\Users\user\Documents\GitHub\space-station-1
4\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 277
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Bo
olean noPredictions, Histogram histogram) in C:\Users\user\Documents\GitHub\
space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:lin
e 116
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTi
me, Boolean noPredictions, Histogram histogram) in C:\Users\user\Documents\G
itHub\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityMa
nager.cs:line 141
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Us
ers\user\Documents\GitHub\space-station-14\RobustToolbox\Robust.Server\BaseS
erver.cs:line 618
   at Robust.Server.BaseServer.<SetupMainLoop>b__54_1(Object sender, FrameEve
ntArgs args) in C:\Users\user\Documents\GitHub\space-station-14\RobustToolbo
x\Robust.Server\BaseServer.cs:line 488
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\user\Documents\GitHub\
space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 192
   at Robust.Server.BaseServer.MainLoop() in C:\Users\user\Documents\GitHub\
space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 509
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentS
tart, ServerOptions options) in C:\Users\user\Documents\GitHub\space-station
-14\RobustToolbox\Robust.Server\Program.cs:line 72
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boole
an contentStart) in C:\Users\user\Documents\GitHub\space-station-14\RobustTo
olbox\Robust.Server\Program.cs:line 43
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\user\Docum
ents\GitHub\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line
 10
   at Content.Server.Program.Main(String[] args) in C:\Users\user\Documents\
GitHub\space-station-14\Content.Server\Program.cs:line 9
`

doafter stuck
![stuck](https://user-images.githubusercontent.com/78795277/149586653-18dc8fa9-8ca6-48db-a3b2-174854464bbf.PNG)

**Comment by Peptide90** [comment]
Yes just tested, fixed
