### ISSUE TITLE
InstrumentComponent resolve exception on client sitting in lobby

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#6330]
Was testing something and had my client sitting in the lobby of Spider. Following exception happened:

```
[ERRO] resolve: Can't resolve "Content.Shared.Instruments.SharedInstrumentComponent" on entity 4981!
   at Content.Client.Instruments.InstrumentSystem.EndRenderer(EntityUid uid, Boolean fromStateChange, SharedInstrumentComponent component) in /home/runner/work/space-station-14/space-station-14/Content.Client/Instruments/InstrumentSystem.cs:line 111
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 376
   at Robust.Client.GameObjects.ClientEntityManager.<Initialize>b__8_1(Object _, Object systemMsg) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 31
   at Robust.Client.GameObjects.ClientEntityManager.DispatchMsgEntity(MsgEntity message) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 154
   at Robust.Client.GameObjects.ClientEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 78
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 190
   at Robust.Client.GameController.<StartupContinue>b__47_0(Object sender, FrameEventArgs args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 171
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 197
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 129
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 114
   at Robust.Client.GameController.<>c__DisplayClass81_0.<Run>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 81
   at System.Threading.Thread.StartCallback()
```

No other exceptions in log.

**Comment by mirrorcult** [comment]
this was made to not throw
