### ISSUE TITLE
Vomit shouldn't have puddle visualizer

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/space-station-14#6526]
Or at least puddle visualizer has to be updated to not just force the sprite to some hard coded value. Currently it just tries to override the vomit visuals and will error.

```
[ERRO] go.comp.sprite: State 'smear-0' does not exist in set RSI. Trace:
   at System.Environment.get_StackTrace()
   at Robust.Client.GameObjects.SpriteComponent.Layer.SetRsi(RSI rsi) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Renderable\SpriteComponent.cs:line 1852
   at Robust.Client.GameObjects.SpriteComponent.LayerSetRSI(Int32 layer, RSI rsi) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Renderable\SpriteComponent.cs:line 918
   at Robust.Client.GameObjects.SpriteComponent.LayerSetRSI(Int32 layer, ResourcePath rsiPath) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Renderable\SpriteComponent.cs:line 950   at Robust.Client.GameObjects.SpriteComponent.LayerSetRSI(Int32 layer, String rsiPath) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\RobustToolbox\Robust.Client\GameObjects\Components\Renderable\SpriteComponent.cs:line 935
   at Content.Client.Fluids.PuddleVisualizer.UpdateVisual(AppearanceComponent component, SpriteComponent spriteComponent, Single cappedScale, Boolean forceWetFloorSprite) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\Content.Client\Fluids\PuddleVisualizer.cs:line 75
   at Content.Client.Fluids.PuddleVisualizer.OnChangeData(AppearanceComponent component) in C:\Users\ElectroSR\Documents\GitHub\space-station-14\Content.Client\Fluids\PuddleVisualizer.cs:line 5
```

**Comment by Willhelm53** [comment]
It was my stuff that broke this - I'll have a look at making puddle visuals more robust.

**Comment by Willhelm53** [comment]
![image](https://user-images.githubusercontent.com/97707302/153632097-dbfd9870-4cdc-43bc-a3f9-fe914ce50efb.png)

I think I'll mimic the general structure of Content.Client>ItemCabinetSystem.cs shown here. This'll give me more good experience working with things across Client/Shared/Server.

**Comment by Ygg01** [comment]
For future reference.

Before visualizer assumed that either the puddle is:
A) grayscale and color will be supplied externally (via color and opacity)
B) fully colored (only opacity)

IIRC Visualizers are flyweighted so altering them isn't as easy as other components

**Comment by Willhelm53** [comment]
An upcoming PR of mine solves other issues, but I believe this one was solved by @Elijahrane in #8349

**Comment by Willhelm53** [comment]
Or possibly by @themias in #9358
