### ISSUE TITLE
Crash on disconnect from server

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#667]
```
[ERRO] runtime: Caught exception in GameLoop Render: System.ArgumentException: Tried to draw an entity has been deleted. (Parameter 'entity')
   at Robust.Client.Graphics.Clyde.Clyde.RenderHandle.DrawEntity(IEntity entity, Vector2 position, Vector2 scale, Nullable`1 overrideDirection) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.RenderHandle.cs:line 82
   at Robust.Client.UserInterface.Controls.SpriteView.DrawInternal(IRenderHandle renderHandle) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/Controls/SpriteView.cs:line 52
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 494
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 494
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 494
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 494
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 494
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 494
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 494
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 494
   at Robust.Client.UserInterface.UserInterfaceManager._render(IRenderHandle renderHandle, Control control, Vector2i position, Color modulate, Nullable`1 scissorBox) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 494
   at Robust.Client.UserInterface.UserInterfaceManager.Render(IRenderHandle renderHandle) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 433
   at Robust.Client.Graphics.Clyde.Clyde.Render() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/Graphics/Clyde/Clyde.HLR.cs:line 123
   at Robust.Shared.Timing.GameLoop.Run() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 236
```

**Comment by Zumorica** [comment]
I don't think this is an issue anymore. At least, I can't replicate it.
