### ISSUE TITLE
Client complete death when warping

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#6805]
## Description

This is maybe a robust thing but cant repro outside of content methods so.

Steps to repro
- Join one of the live servers
- Repeatedly ghost warp to people out of range
- Die

Stacktrace
```
[ERRO] runtime: Caught exception in "GameLoop Update"
System.Collections.Generic.KeyNotFoundException: Entity 16534 does not have a component of type Robust.Shared.GameObjects.TransformComponent
   at Robust.Client.Placement.PlacementManager.CurrentMousePosition(ScreenCoordinates& coordinates) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Placement/PlacementManager.cs:line 507
   at Robust.Client.Placement.PlacementManager.FrameUpdate(FrameEventArgs e) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Placement/PlacementManager.cs:line 562
   at Robust.Client.GameController.<StartupContinue>b__47_3(Object sender, FrameEventArgs args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 195
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 238
[ERRO] runtime: Caught exception in "GameLoop Update"
System.Collections.Generic.KeyNotFoundException: Entity 16534 does not have a component of type Robust.Shared.GameObjects.TransformComponent
   at Robust.Client.Placement.PlacementManager.CurrentMousePosition(ScreenCoordinates& coordinates) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Placement/PlacementManager.cs:line 507
   at Robust.Client.Placement.PlacementManager.FrameUpdate(FrameEventArgs e) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Placement/PlacementManager.cs:line 562
   at Robust.Client.GameController.<StartupContinue>b__47_3(Object sender, FrameEventArgs args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 195
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 238
```

**Additional context**

**Comment by metalgearsloth** [comment]
To repro needs to specifically be an entity you've never seen before.
