### ISSUE TITLE
I cant play midi

### ISSUE THREAD

**Issue by Zuzuk-null** [space-wizards/space-station-14#6820]
[ERRO] runtime: Caught exception in "Async Queued Callback"
System.DllNotFoundException: Unable to load shared library '/home/nuxs/ss13/bin/loader/libswnfd.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /usr/lib/libbz2.so.1.0: undefined symbol: BZ2_hbMakeCodeLengths
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError)
   at SS14.Loader.Program.LoadContextOnResolvingUnmanaged(Assembly assembly, String unmanaged) in /home/runner/work/SS14.Launcher/SS14.Launcher/SS14.Loader/Program.cs:line 39
   at System.Runtime.Loader.AssemblyLoadContext.GetResolvedUnmanagedDll(Assembly assembly, String unmanagedDllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDllUsingEvent(String unmanagedDllName, Assembly assembly, IntPtr gchManagedAssemblyLoadContext)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at Robust.Client.Utility.ClientDllMap.<>c.<Initialize>b__0_0(String name, Assembly assembly, Nullable`1 path) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Utility/ClientDllMap.cs:line 20
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Robust.Client.UserInterface.FileDialogManager.sw_NFD_OpenDialog(Byte* filterList, Byte* defaultPath, Byte** outPath)
   at Robust.Client.UserInterface.FileDialogManager.<>c__DisplayClass8_0.<OpenFileNfd>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/FileDialogManager.cs:line 95
   at Robust.Client.UserInterface.FileDialogManager.<>c__DisplayClass11_0.<RunAsyncMaybe>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/FileDialogManager.cs:line 188
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Robust.Client.UserInterface.FileDialogManager.GetOpenFileName(FileDialogFilters filters) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/FileDialogManager.cs:line 51
   at Robust.Client.UserInterface.FileDialogManager.OpenFile(FileDialogFilters filters) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/UserInterface/FileDialogManager.cs:line 35
   at Content.Client.Instruments.UI.InstrumentMenu.MidiFileButtonOnOnPressed(ButtonEventArgs obj) in /home/runner/work/space-station-14/space-station-14/Content.Client/Instruments/UI/InstrumentMenu.xaml.cs:line 80
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at Robust.Shared.Asynchronous.RobustSynchronizationContext.ProcessPendingTasks() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Asynchronous/RobustSynchronizationContext.cs:line 57

**Comment by DubiousDoggo** [comment]
Could you give a bit more info on this?
Steps to reproduce?
What OS are you running?

**Comment by gradientvera** [comment]
Engine issue, transferring
