### ISSUE TITLE
game.map and game.mapforced are not well-documented.

### ISSUE THREAD

**Issue by phillipinman** [space-wizards/space-station-14#7023]
## Description

When editing the server config and adding game.map to the config.toml the server will start with an exception:

```
[DEBG] map: Starting...
[INFO] map: Creating new map 0
[FATL] unhandled: System.ArgumentException: Unknown map prototype /Maps/bagel.yml was selected!
   at Content.Server.Maps.GameMapManager.<Initialize>b__7_0(String value) in /home/runner/work/space-station-14/space-station-14/Content.Server/Maps/GameMapManager.cs:line 35
   at Robust.Shared.Configuration.ConfigurationManager.OnValueChanged[T](String name, Action`1 onValueChanged, Boolean invokeImmediately) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Configuration/ConfigurationManager.cs:line 265
   at Robust.Shared.Configuration.ConfigurationManager.OnValueChanged[T](CVarDef`1 cVar, Action`1 onValueChanged, Boolean invokeImmediately) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Configuration/ConfigurationManager.cs:line 250
   at Content.Server.Maps.GameMapManager.Initialize() in /home/runner/work/space-station-14/space-station-14/Content.Server/Maps/GameMapManager.cs:line 30
   at Content.Server.Entry.EntryPoint.PostInit() in /home/runner/work/space-station-14/space-station-14/Content.Server/Entry/EntryPoint.cs:line 124
   at Robust.Shared.ContentPack.BaseModLoader.BroadcastRunLevel(ModRunLevel level) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/ContentPack/BaseModLoader.cs:line 80
   at Robust.Server.BaseServer.Start(ServerOptions options, Func`1 logHandlerFactory) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 356
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 62
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 43
   at Robust.Server.Program.Main(String[] args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 24
Unhandled exception. System.ArgumentException: Unknown map prototype /Maps/bagel.yml was selected!
   at Content.Server.Maps.GameMapManager.<Initialize>b__7_0(String value) in /home/runner/work/space-station-14/space-station-14/Content.Server/Maps/GameMapManager.cs:line 35
   at Robust.Shared.Configuration.ConfigurationManager.OnValueChanged[T](String name, Action`1 onValueChanged, Boolean invokeImmediately) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Configuration/ConfigurationManager.cs:line 265
   at Robust.Shared.Configuration.ConfigurationManager.OnValueChanged[T](CVarDef`1 cVar, Action`1 onValueChanged, Boolean invokeImmediately) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Configuration/ConfigurationManager.cs:line 250
   at Content.Server.Maps.GameMapManager.Initialize() in /home/runner/work/space-station-14/space-station-14/Content.Server/Maps/GameMapManager.cs:line 30
   at Content.Server.Entry.EntryPoint.PostInit() in /home/runner/work/space-station-14/space-station-14/Content.Server/Entry/EntryPoint.cs:line 124
   at Robust.Shared.ContentPack.BaseModLoader.BroadcastRunLevel(ModRunLevel level) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/ContentPack/BaseModLoader.cs:line 80
   at Robust.Server.BaseServer.Start(ServerOptions options, Func`1 logHandlerFactory) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 356
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 62
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 43
   at Robust.Server.Program.Main(String[] args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 24
```

**Additional context**
Was trying to change the map to try out bagel as voting only shows 2 maps. Uncommenting it in the config reverts it back to working state. I did check ```bin/Resources/Prototypes/Maps/bagel.yml``` to see if I'm just an idiot and got something wrong but using the MapPath there also doesn't work.

I am using SS14.Watchdog FYI to run this but as far as I can tell that doesn't seem to matter.

Dump of the relevant config section:

```
[game]
hostname = "Binary Gaming Network"
map = "/Maps/bagel.yml"
maxplayers = 64
type = 1
welcomemsg = "Welcome to the server!"
lobbyenabled = true
```

I did a poor mans fix by renaming bagel.yml to saltern.yaml and that worked, but had other issues.

If instructions for loading a map on a server are written down somewhere then let me know and ill close this issue.

Insight appreciated :)

**Comment by metalgearsloth** [comment]
Isn't it `bagelstation`?

**Comment by mirrorcult** [comment]
`game.map` takes in a game map prototype ID (`bagelstation`, `saltern`, `packedstation`), not a file path

**Comment by moonheart08** [comment]
Check the prototypes in /Resources/Prototypes/Maps/game.yml for what maps you can load. It does not take a file path.

**Comment by mirrorcult** [comment]
i mean this is maybe still an issue in the sense that we need to specify that in docs better, doesnt the template server config still specify as path as an example

**Comment by moonheart08** [comment]
Ah good point, uhh

**Comment by phillipinman** [comment]
Hey thanks for the quick replies :)

I did indeed get the map as a path from the config. I added bagelstation to the config instead and can confirm it loads initially. (changes due to lack of players).

Many thanks for solving that :)

(Also love your work, this game is great.)
