### ISSUE TITLE
Exception whilst loading prototypes from /Prototypes/Cargo/products.yml

### ISSUE THREAD

**Issue by collinlunn** [space-wizards/space-station-14#747]
[ERRO] eng: Exception whilst loading prototypes from /Prototypes/Cargo/products.yml#0:
System.Collections.Generic.KeyNotFoundException: The given key 'state' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at YamlDotNet.RepresentationModel.YamlNode.get_Item(YamlNode key)
   at Robust.Shared.Utility.SpriteSpecifier.FromYaml(YamlNode node) in C:\Users\19252\Desktop\Rec\space-station-14\RobustToolbox\Robust.Shared\Utility\SpriteSpecifier.cs:line 28
   at Robust.Shared.Serialization.YamlObjectSerializer.SpriteSpecifierSerializer.NodeToType(Type type, YamlNode node, YamlObjectSerializer serializer) in C:\Users\19252\Desktop\Rec\space-station-14\RobustToolbox\Robust.Shared\Serialization\YamlObjectSerializer.cs:line 980
   at Robust.Shared.Serialization.YamlObjectSerializer.NodeToType(Type type, YamlNode node) in C:\Users\19252\Desktop\Rec\space-station-14\RobustToolbox\Robust.Shared\Serialization\YamlObjectSerializer.cs:line 478
   at Robust.Shared.Serialization.YamlObjectSerializer.DataField[T](T& value, String name, T defaultValue, Boolean alwaysWrite) in C:\Users\19252\Desktop\Rec\space-station-14\RobustToolbox\Robust.Shared\Serialization\YamlObjectSerializer.cs:line 121
   at Content.Shared.Prototypes.Cargo.CargoProductPrototype.LoadFrom(YamlMappingNode mapping) in C:\Users\19252\Desktop\Rec\space-station-14\Content.Shared\Prototypes\Cargo\CargoProductPrototype.cs:line 104
   at Robust.Shared.Prototypes.PrototypeManager.LoadFromDocument(YamlDocument document) in C:\Users\19252\Desktop\Rec\space-station-14\RobustToolbox\Robust.Shared\Prototypes\PrototypeManager.cs:line 315
   at Robust.Shared.Prototypes.PrototypeManager.LoadDirectory(ResourcePath path) in C:\Users\19252\Desktop\Rec\space-station-14\RobustToolbox\Robust.Shared\Prototypes\PrototypeManager.cs:line 235

**Comment by Moneyl** [comment]
Fixed by #742
