### ISSUE TITLE
Trying to walk out of a locker throws a physics exception on client

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#7472]
## Description

https://cdn.discordapp.com/attachments/790656972801572905/962108959702007848/clientcrash.mp4

reported by TheSorrowOfLife#0753

**Additional context**
```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 31
   at Robust.Shared.Physics.Dynamics.SharedPhysicsMapComponent.AddAwakeBody(PhysicsComponent body) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Physics\Dynamics\SharedPhysicsMapComponent.cs:line 143
   at Robust.Shared.GameObjects.SharedPhysicsSystem.HandleWakeMessage(PhysicsWakeMessage message) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line 243
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass8_0`1.<SubscribeEvent>b__0(Unit& ev) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 200
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.B
roadcast.cs:line 376
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity
EventBus.Directed.cs:line 164
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:lin
e 123
   at Robust.Shared.GameObjects.PhysicsComponent.SetAwake(Boolean value) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Collidable\PhysicsComponent.Physics.cs:line 171
   at Robust.Shared.GameObjects.PhysicsComponent.set_Awake(Boolean value) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Collidable\PhysicsComponent.Physics.cs:line 157
   at Robust.Shared.GameObjects.SharedPhysicsSystem.SetLinearVelocity(PhysicsComponent body, Vector2 velocity) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.Component
s.cs:line 14
   at Content.Shared.Movement.SharedMoverController.HandleMobMovement(IMoverComponent mover, PhysicsComponent physicsComponent, IMobMoverComponent mobMover, TransformComponent xform) in K:\github.com\mirrorcult\space-station-14\Conte
nt.Shared\Movement\SharedMoverController.cs:line 179
   at Content.Client.Physics.Controllers.MoverController.UpdateBeforeSolve(Boolean prediction, Single frameTime) in K:\github.com\mirrorcult\space-station-14\Content.Client\Physics\Controllers\MoverController.cs:line 74
   at Robust.Shared.Physics.Controllers.VirtualController.OnBeforeSolve(PhysicsUpdateBeforeSolveEvent& ev) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Physics\Controllers\VirtualController.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass10_0`1.<SubscribeEvent>b__0(Unit& ev) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 224
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, List`1 found) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 75
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventOrdered(EventSource source, Unit& eventArgs, Type eventType, Boolean byRef) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityE
ventBus.Ordering.cs:line 23
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.B
roadcast.cs:line 366
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T& toRaise) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 304
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[T](T& message) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 70
   at Robust.Shared.GameObjects.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line 298
   at Robust.Client.Physics.PhysicsSystem.FrameUpdate(Single frameTime) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\Physics\PhysicsSystem.cs:line 37
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 324
   at Robust.Shared.GameObjects.EntityManager.FrameUpdate(Single frameTime) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 147
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 489
   at Robust.Client.GameController.<StartupContinue>b__46_3(Object sender, FrameEventArgs args) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 194
   at Robust.Shared.Timing.GameLoop.Run() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 238
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 129
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 114
   at Robust.Client.GameController.<>c__DisplayClass80_0.<Run>b__0() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 81
   at System.Threading.Thread.StartCallback()
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 31
   at Robust.Shared.Physics.Dynamics.SharedPhysicsMapComponent.AddAwakeBody(PhysicsComponent body) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Physics\Dynamics\SharedPhysicsMapComponent.cs:line 143
   at Robust.Shared.GameObjects.SharedPhysicsSystem.HandleWakeMessage(PhysicsWakeMessage message) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line 243
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass8_0`1.<SubscribeEvent>b__0(Unit& ev) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 200
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.B
roadcast.cs:line 376
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Entity
EventBus.Directed.cs:line 164
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:lin
e 123
   at Robust.Shared.GameObjects.PhysicsComponent.SetAwake(Boolean value) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Collidable\PhysicsComponent.Physics.cs:line 171
   at Robust.Shared.GameObjects.PhysicsComponent.set_Awake(Boolean value) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Components\Collidable\PhysicsComponent.Physics.cs:line 157
   at Robust.Shared.GameObjects.SharedPhysicsSystem.SetLinearVelocity(PhysicsComponent body, Vector2 velocity) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.Component
s.cs:line 14
   at Content.Shared.Movement.SharedMoverController.HandleMobMovement(IMoverComponent mover, PhysicsComponent physicsComponent, IMobMoverComponent mobMover, TransformComponent xform) in K:\github.com\mirrorcult\space-station-14\Conte
nt.Shared\Movement\SharedMoverController.cs:line 179
   at Content.Client.Physics.Controllers.MoverController.UpdateBeforeSolve(Boolean prediction, Single frameTime) in K:\github.com\mirrorcult\space-station-14\Content.Client\Physics\Controllers\MoverController.cs:line 74
   at Robust.Shared.Physics.Controllers.VirtualController.OnBeforeSolve(PhysicsUpdateBeforeSolveEvent& ev) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Physics\Controllers\VirtualController.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass10_0`1.<SubscribeEvent>b__0(Unit& ev) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 224
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, List`1 found) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 75
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventOrdered(EventSource source, Unit& eventArgs, Type eventType, Boolean byRef) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityE
ventBus.Ordering.cs:line 23
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.B
roadcast.cs:line 366
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T& toRaise) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 304
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[T](T& message) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 70
   at Robust.Shared.GameObjects.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\Systems\SharedPhysicsSystem.cs:line 298
   at Robust.Client.Physics.PhysicsSystem.FrameUpdate(Single frameTime) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\Physics\PhysicsSystem.cs:line 37
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 324
   at Robust.Shared.GameObjects.EntityManager.FrameUpdate(Single frameTime) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 147
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 489
   at Robust.Client.GameController.<StartupContinue>b__46_3(Object sender, FrameEventArgs args) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 194
   at Robust.Shared.Timing.GameLoop.Run() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 238
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 129
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 114
   at Robust.Client.GameController.<>c__DisplayClass80_0.<Run>b__0() in K:\github.com\mirrorcult\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 81
   at System.Threading.Thread.StartCallback()
```

**Comment by ElectroJr** [comment]
Assuming this is the same issue that comes up when trying to walk while inside of a disposal unit (which it looks like from the error), then this will probably also get fixed by space-wizards/RobustToolbox/pull/2691
