### ISSUE TITLE
Crash when trying to inspect a prototype on view variables.  Null Reference Exception.

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#7900]
## Description

Reproduction:
View Variables > Client Variables > Prototype > Inspect

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Robust.Client.UserInterface.Controls.LineEdit.set_Text(String value) in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\UserInterface\Controls\LineEdit.cs:line 76
   at Robust.Client.ViewVariables.Editors.VVPropEditorString.MakeUI(Object value) in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\ViewVariables\Editors\VVPropEditorString.cs:line 10
   at Robust.Client.ViewVariables.VVPropEditor.Initialize(Object value, Boolean readOnly) in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\ViewVariables\VVPropEditor.cs:line 21
   at Robust.Client.ViewVariables.ViewVariablesPropertyControl.SetProperty(MemberData member) in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\ViewVariables\ViewVariablesPropertyControl.cs:line 100
   at Robust.Client.ViewVariables.ViewVariablesInstance.<>c__DisplayClass6_0.<LocalPropertyList>b__2(ValueTuple`5 tuple) in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\ViewVariables\ViewVariablesInstance.cs:line 107
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at Robust.Client.ViewVariables.Traits.ViewVariablesTraitMembers.Refresh() in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\ViewVariables\Traits\ViewVariablesTraitMembers.cs:line 43
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Robust.Shared.Asynchronous.RobustSynchronizationContext.ProcessPendingTasks() in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Shared\Asynchronous\RobustSynchronizationContext.cs:line 58
   at Robust.Shared.Asynchronous.TaskManager.ProcessPendingTasks() in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Shared\Asynchronous\TaskManager.cs:line 28
   at Robust.Client.GameController.Input(FrameEventArgs frameEventArgs) in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 455
   at Robust.Client.GameController.<StartupContinue>b__47_2(Object sender, FrameEventArgs args) in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 188
   at Robust.Shared.Timing.GameLoop.Run() in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 158
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 129
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 114
   at Robust.Client.GameController.<>c__DisplayClass81_0.<Run>b__0() in J:\Program Files\SS14CloneNew\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 81
   at System.Threading.Thread.StartCallback()`

**Screenshots**

**Additional context**

**Comment by metalgearsloth** [comment]
Was an engine issue and was fixed.
