### ISSUE TITLE
Camera breaks after firing 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#825]
See: https://cdn.discordapp.com/attachments/310555209753690112/701567784961703966/P.webm
Exception:
```
[ERRO] entsys: System.NullReferenceException: Object reference not set to an instance of an object.
   at Content.Client.GameObjects.Components.Mobs.CameraRecoilComponent._updateEye()
   at Content.Client.GameObjects.Components.Mobs.CameraRecoilComponent.FrameUpdate(Single frameTime)
   at Content.Client.GameObjects.EntitySystems.CameraRecoilSystem.FrameUpdate(Single frameTime)
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 175
```

**Comment by Zumorica** [comment]
Can't replicate locally on my end

**Comment by AJCM-git** [comment]
Try it on the server.
Maybe it has something to do with low fps / high latency?

**Comment by Acruid** [comment]
I can't replicate this bug, so I'm going to assume it was fixed.
