### ISSUE TITLE
Crash when editing enum with ViewVariables

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#838]
Steps I used to reproduce:
1. VV a human
2. Modify server-side HumanoidAppearanceComponent
3. Change Sex (which shows as string for some reason) to Female or Male
4. Crash!

```csharp
Unhandled exception. System.InvalidOperationException: Boolean TryParse(System.Type, System.String, System.Object ByRef) is not a GenericMethodDefinition. MakeGenericMethod may only be called on a method for which MethodBase.IsGenericMethodDefinition is true.
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at Robust.Shared.Utility.EnumHelper.TryParse(Type enumType, String value, Boolean ignoreCase, Object& enumValue) in /home/zumo/Projects/space-station-14/RobustToolbox/Robust.Shared/Utility/EnumHelper.cs:line 23
   at Robust.Client.ViewVariables.Editors.ViewVariablesPropertyEditorEnum.<>c__DisplayClass0_0.<MakeUI>b__0(LineEditEventArgs e) in /home/zumo/Projects/space-station-14/RobustToolbox/Robust.Client/ViewVariables/Editors/ViewVariablesPropertyEditorEnum.cs:line 48
```

**Comment by PaulRitter** [comment]
should be closed, was fixed
