### ISSUE TITLE
Shooting a gun through an open airlock repeatedly crashes the server

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#839]
Steps to reproduce:

1. Open an airlock.
2. Shoot it with a sub machine repeatedly
3. Crash!

```csharp
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Tried to get component on a deleted entity.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition, String message) in /home/zumo/Projects/space-station-14/RobustToolbox/Robust.Shared/Utility/DebugTools.cs:line 48
   at Robust.Shared.GameObjects.Entity.TryGetComponent[T](T& component) in /home/zumo/Projects/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Entity.cs:line 285
   at Robust.Server.GameObjects.EntitySystems.PhysicsSystem.GetFriction(ITileDefinitionManager tileDefinitionManager, IMapManager mapManager, IEntity entity) in /home/zumo/Projects/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs:line 202
   at Robust.Server.GameObjects.EntitySystems.PhysicsSystem.HandleMovement(IMapManager mapManager, ITileDefinitionManager tileDefinitionManager, IEntity entity, Single frameTime) in /home/zumo/Projects/space-station-14/RobustToolbox/Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs:line 111
```

**Comment by FL-OZ** [comment]
I also observed this same error when shooting a crate. When I began debugging it however, I stopped getting the error randomly.

**Comment by AJCM-git** [comment]
cant reproduce
