### ISSUE TITLE
Local error

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#886]
Since quite a while my client crashes when placing anything outside of the station. The branch where i tested it couldnt be more vanilla, dunno if anyone has the same issue

LOG
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Content.Server.GameObjects.EntitySystems.SharedInteractionSystem.InRangeUnobstructed(MapCoordinates coords, Vector2 otherCoords, Single range, Int32 collisionMask, Func`2 predicate, Boolean insideBlockerValid) in /home/maharba/Desarrollo/space-station-14/Content.Shared/GameObjects/EntitySystems/SharedInteractionSystem.cs:line 55
   at Content.Client.State.GameScreenBase.FrameUpdate(FrameEventArgs e) in /home/maharba/Desarrollo/space-station-14/Content.Client/State/GameScreenBase.cs:line 62
   at Robust.Client.State.StateManager.FrameUpdate(FrameEventArgs e) in /home/maharba/Desarrollo/space-station-14/RobustToolbox/Robust.Client/State/StateManager.cs:line 25
   at Robust.Client.GameController._frameProcessMain(FrameEventArgs frameEventArgs) in /home/maharba/Desarrollo/space-station-14/RobustToolbox/Robust.Client/GameController.cs:line 283
   at Robust.Client.GameController.<MainLoop>b__63_3(Object sender, FrameEventArgs args) in /home/maharba/Desarrollo/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106
   at Robust.Shared.Timing.GameLoop.Run() in /home/maharba/Desarrollo/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 222
   at Robust.Client.GameController.MainLoop(DisplayMode mode) in /home/maharba/Desarrollo/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 111
   at Robust.Client.GameController.ParsedMain(CommandLineArgs args, Boolean contentStart) in /home/maharba/Desarrollo/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 57
   at Robust.Client.GameController.Start(String[] args, Boolean contentStart) in /home/maharba/Desarrollo/space-station-14/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 37
   at Robust.Client.ContentStart.Start(String[] args) in /home/maharba/Desarrollo/space-station-14/RobustToolbox/Robust.Client/ContentStart.cs:line 10
   at Content.Client.Program.Main(String[] args) in /home/maharba/Desarrollo/space-station-14/Content.Client/Program.cs:line 9
```

**Comment by ComicIronic** [comment]
https://github.com/space-wizards/space-station-14/blob/55c54e415b53ed35b80a982bb52c625c9b1451f5/Content.Shared/GameObjects/EntitySystems/SharedInteractionSystem.cs#L55

For anyone interested in the line itself.
