### ISSUE TITLE
Client lags to hell when restarting/starting a round

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#932]
Logs:
```
[ERRO] runtime: Caught exception in GameLoop Tick: System.Collections.Generic.KeyNotFoundException: The given key '1202' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 124
   at Robust.Client.Player.PlayerManager.UpdateAttachedEntity(Nullable`1 entity) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/Player/PlayerManager.cs:line 136
   at Robust.Client.Player.PlayerManager.ApplyPlayerStates(IEnumerable`1 list) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/Player/PlayerManager.cs:line 101
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 344
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 179
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController.cs:line 276
   at Robust.Shared.Timing.GameLoop.Run() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 180

```

```
[ERRO] runtime: Caught exception in GameLoop Tick: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Robust.Client.GameObjects.ClientEntityManager.ApplyEntityStates(EntityState[] curEntStates, IEnumerable`1 deletions, EntityState[] nextEntStates) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 47
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState(GameState curState, GameState nextState) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 343
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 177
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController.cs:line 276
   at Robust.Shared.Timing.GameLoop.Run() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 180

```

**Comment by AJCM-git** [comment]
fixed by b8338bc

**Comment by AJCM-git** [comment]
Tried in my local and couldnt reproduce, but i think those only ocurred in the server, i will try this out once jenkins update.

**Comment by AJCM-git** [comment]
Yep, cant reproduce with the release build either, this is fixed
