### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#966]
Im getting this in my local when right-clicking: 
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: Type not found Robust.Shared.Utility.SpriteSpecifier+Texture
   at NetSerializer.TypeDictionary.get_Item(Type key)
   at NetSerializer.Serializer.GetTypeIdAndSerializer(Type type, SerializeDelegate`1& del)
   at NetSerializer.ObjectSerializer.Serialize(Serializer serializer, Stream stream, Object ob)
   at Serialize(Serializer serializer, Stream stream, NetVerbData value)
   at Serialize(Serializer serializer, Stream stream, NetVerbData[] value)
   at NetSerializer.ObjectSerializer.Serialize(Serializer serializer, Stream stream, Object ob)
   at Robust.Shared.Serialization.RobustSerializer.Serialize(Stream stream, Object toSerialize) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/Serialization/RobustSerializer.cs:line 61
   at Robust.Shared.Network.Messages.MsgEntity.WriteToBuffer(NetOutgoingMessage buffer) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/Network/Messages/MsgEntity.cs:line 80
   at Robust.Shared.Network.NetManager.BuildMessage(NetMessage message, NetPeer peer) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 782
   at Robust.Shared.Network.NetManager.ServerSendMessage(NetMessage message, INetChannel recipient) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 815
   at Robust.Server.GameObjects.ServerEntityNetworkManager.SendSystemNetworkMessage(EntitySystemMessage message, INetChannel targetConnection) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityNetworkManager.cs:line 104
   at Robust.Shared.GameObjects.Systems.EntitySystem.RaiseNetworkEvent(EntitySystemMessage message, INetChannel channel) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/Systems/EntitySystem.cs:line 97
   at Content.Server.GameObjects.EntitySystems.VerbSystem.RequestVerbs(RequestVerbsMessage req, EntitySessionEventArgs eventArgs) in /home/maharba/Git/Desarrollo/SS14/space-station-14/Content.Server/GameObjects/EntitySystems/VerbSystem.cs:line 122
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 23
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass7_0`1.<SubscribeEvent>b__0(Object ev) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.cs:line 151
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Object eventArgs) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.cs:line 285
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.cs:line 201
   at Robust.Shared.GameObjects.EntityManager.<Initialize>b__22_1(Object sender, Object systemMsg) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 66
   at Robust.Server.GameObjects.ServerEntityNetworkManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityNetworkManager.cs:line 155
   at Robust.Server.GameObjects.ServerEntityNetworkManager.HandleEntityNetworkMessage(MsgEntity message) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityNetworkManager.cs:line 120
   at Robust.Shared.Network.NetManager.<>c__DisplayClass72_0`1.<RegisterNetMessage>b__0(NetMessage msg) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 741
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 694
   at Robust.Shared.Network.NetManager.ProcessPackets() in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 325
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 395
   at Robust.Server.BaseServer.<MainLoop>b__35_0(Object sender, FrameEventArgs args) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 285
   at Robust.Shared.Timing.GameLoop.Run() in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 180
   at Robust.Server.BaseServer.MainLoop() in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 288
   at Robust.Server.Program.ParsedMain(CommandLineArgs args) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 64
   at Robust.Server.Program.Start(String[] args) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 34
   at Robust.Server.Program.Main(String[] args) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/Program.cs:line 20
   at Robust.Server.ContentStart.Start(String[] args) in /home/maharba/Git/Desarrollo/SS14/space-station-14/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/maharba/Git/Desarrollo/SS14/space-station-14/Content.Server/Program.cs:line 9
```

**Comment by PJB3005** [comment]
Fixed in engine.
